import {choose,setRepository} from "./helpers";
import {test,create,ready,open,panel,repo} from "./helpers";
import {expect} from "@playwright/test";
import * as fs from "node:fs";
import * as path from "node:path";
test("visual walkthrough of the production app with isolated fixture content",async({page,request},testInfo)=>{
 await page.setViewportSize(process.env.OPENADE_RECORD_VIDEO?{width:1480,height:920}:{width:2560,height:1080});await ready(page);await setRepository(page,repo);await choose(page,"Provider","codex");
 const capture=async(name:string)=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:testInfo.outputPath(name+".png"),animations:"disabled"});};
 await capture("composer");await page.getByLabel("Choose model").click();await capture("model-picker");await page.keyboard.press("Escape");
 const session=await create(request,"Review the local project",{prompt:"Explain the repository structure and verify worktree isolation."});await expect.poll(async()=> (await(await request.get(`http://127.0.0.1:7455/api/sessions/${session.id}`)).json()).status).toBe("completed");await open(page,"Review the local project");await expect(page.getByRole("heading",{name:"Native chat response",exact:true})).toBeVisible();await capture("native-chat");if(process.env.OPENADE_RECORD_VIDEO){await page.getByLabel("Filter projects",{exact:true}).click();await capture("project-picker");await page.keyboard.press("Escape");await page.getByLabel("Project display settings",{exact:true}).click();await capture("sidebar-display-menu");await page.keyboard.press("Escape");}
 fs.writeFileSync(path.join(session.worktree_path,"README.md"),"# Local project\n\nReviewed in an isolated worktree.\n");await panel(page,"Diffs");await expect(page.locator(".diff-document")).toHaveCount(1);await page.getByLabel("Toggle files panel").click();await expect(page.getByRole("treeitem",{name:"README.md",exact:true})).toBeVisible();await capture("chat-diffs-files");await page.getByRole("treeitem",{name:"README.md",exact:true}).click();await expect(page.getByLabel("Edit README.md")).toBeVisible();await capture("file-editor");await page.getByLabel("Open settings").click();
 for(const section of ["General","Appearance","Notifications","Shortcuts","Providers","Devices","Files","Archived sessions"]){await page.getByRole("tab",{name:section,exact:true}).click();await expect(page.locator(".settings-content h1")).toHaveText(section==="Shortcuts"?"Keyboard Shortcuts":section);await capture("settings-"+section.toLowerCase().replaceAll(" ","-"));if(section==="Appearance"&&process.env.OPENADE_RECORD_VIDEO){await page.getByLabel("Dark theme",{exact:true}).click();await capture("theme-library");await page.keyboard.press("Escape");await choose(page,"Dark theme","nord");await choose(page,"Glass","transparent");await capture("adjustable-transparency-browser-approximation");await choose(page,"Glass","liquid");await capture("liquid-option-browser-approximation");}}
});
