import { expect } from "@playwright/test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { ready, test, tmp, token } from "./helpers";
import {spawn,ChildProcess} from "node:child_process";

const nativeThemeId=(entryId:string,variantId:string)=>`native:${encodeURIComponent(entryId)}:${encodeURIComponent(variantId)}`;

test("alpha-accent snapshots survive restart and a damaged sibling",async({page})=>{
 await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();
 for(const name of ["Alpha survivor","Valid sibling"]){await page.getByLabel("Choose VS Code theme JSON file").setInputFiles({name:name+".json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({name,type:"dark",colors:{"editor.background":"#101822","button.background":"#abcdef80"}}))});}
 const row=page.locator(".custom-theme-item").filter({hasText:"Alpha survivor"});await row.getByRole("button",{name:"Apply",exact:true}).click();await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-alpha-survivor-dark");await expect(page.locator(".ade")).toHaveCSS("--accent-soft","#abcdef38");
 await page.evaluate(()=>{const key="openade.custom-themes.v1",items=JSON.parse(localStorage.getItem(key)!);items.push({id:"custom-broken-dark"});localStorage.setItem(key,JSON.stringify(items));});await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-alpha-survivor-dark");await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await expect(page.locator(".custom-theme-item")).toHaveCount(2);await expect(page.getByLabel("Remove Valid sibling")).toBeVisible();
});

test("linked selections restore before Settings, missing package variants retain palettes, and snapshot edits stay separate",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-theme-startup-"));const manifest=path.join(folder,"package.json");const declarations=[{label:"Startup Light",uiTheme:"vs",path:"light.json"},{label:"Startup Dark",uiTheme:"vs-dark",path:"dark.json"}];
 fs.writeFileSync(manifest,JSON.stringify({displayName:"Startup family",contributes:{themes:declarations}}));fs.writeFileSync(path.join(folder,"light.json"),fixture("Startup Light","light","#faf8f4","#8144d8","#b3261e"));fs.writeFileSync(path.join(folder,"dark.json"),fixture("Startup Dark","dark","#151e29","#b18cff","#dc5272"));
 const created=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:folder}});expect(created.status()).toBe(201);const entry=await created.json();const dark=entry.variants.find((variant:{appearance:string})=>variant.appearance==="dark");
 try{await page.addInitScript(({id})=>{if(localStorage.getItem("openade.preferences"))return;localStorage.setItem("openade.preferences",JSON.stringify({color_scheme:"dark",dark_theme:id}));},{id:dark.id});await ready(page);await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,dark.id));await expect.poll(async()=>{const stored=await page.evaluate(()=>localStorage.getItem("openade.preferences"));return JSON.parse(stored||"{}").dark_theme;}).toBe(nativeThemeId(entry.id,dark.id));await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const family=page.locator(".linked-theme-item").filter({hasText:"Startup family"});await family.locator(".custom-theme-item").filter({hasText:"Startup Dark"}).getByRole("button",{name:"Applied",exact:true}).click();await expect(page.locator(".ade")).toHaveCSS("--bg","#151e29");await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,dark.id));await expect(page.locator(".ade")).toHaveCSS("--bg","#151e29");
 await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();fs.writeFileSync(manifest,JSON.stringify({displayName:"Startup family",contributes:{themes:[declarations[0]]}}));await family.getByRole("button",{name:"Reload",exact:true}).click();await expect(family).toContainText("no longer contains selected theme variants");await expect(family.locator(".custom-theme-item")).toHaveCount(2);await expect(page.locator(".ade")).toHaveCSS("--bg","#151e29");await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,dark.id));await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await expect(page.getByRole("heading",{name:"Appearance",exact:true})).toBeVisible();
 await page.getByLabel("Choose VS Code theme JSON file").setInputFiles({name:"separate.json",mimeType:"application/json",buffer:Buffer.from(fixture("Separate snapshot","dark","#181818","#abcdef","#ff6670"))});await expect(page.getByLabel("Remove Separate snapshot")).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("openade.custom-themes.v1")!))).toHaveLength(1);await page.getByLabel("Remove Separate snapshot").click();await family.getByLabel("Remove Startup family").click();await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","zeron-dark");await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await expect(page.getByText("Startup Dark",{exact:true})).toHaveCount(0);
 }finally{await request.delete(`http://127.0.0.1:7455/api/themes/${entry.id}`);fs.rmSync(folder,{recursive:true,force:true});}
});

const fixture=(name:string,type:string,background:string,keyword:string,ansiRed:string)=>JSON.stringify({name,type,colors:{"editor.background":background,"editor.foreground":"#20242a","sideBar.background":"#e5e8ed","terminal.background":"#11151a","terminal.foreground":"#f2f4f8","terminal.ansiRed":ansiRed},tokenColors:[{scope:"keyword",settings:{foreground:keyword}}]});

test("linked renderer identity stays distinct from an active browser snapshot with the same raw ID",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-snapshot-native-id-"));fs.writeFileSync(path.join(folder,"package.json"),JSON.stringify({displayName:"Snapshot owner",contributes:{themes:[{label:"Variant",uiTheme:"vs-dark",path:"dark.json"}]}}));fs.writeFileSync(path.join(folder,"dark.json"),fixture("Linked palette","dark","#172433","#8844cc","#bb3344"));
 const created=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:folder}});expect(created.status()).toBe(201);const entry=await created.json() as {id:string;variants:{id:string}[]};const rawId=entry.variants[0].id,rendererId=nativeThemeId(entry.id,rawId);
 try{await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await page.getByRole("button",{name:"Dark",exact:true}).click();await page.getByLabel("Choose VS Code theme JSON file").setInputFiles({name:"snapshot-owner-variant.json",mimeType:"application/json",buffer:Buffer.from(fixture("Snapshot palette","dark","#2b2436","#d28cff","#e15278"))});await page.getByLabel("Remove Snapshot palette").waitFor();
  await page.evaluate(({rawId})=>{const key="openade.custom-themes.v1",items=JSON.parse(localStorage.getItem(key)!);items[0].id=rawId;items[0].familyId="snapshot-owner";localStorage.setItem(key,JSON.stringify(items));const prefKey="openade.preferences",prefs=JSON.parse(localStorage.getItem(prefKey)||"{}");localStorage.setItem(prefKey,JSON.stringify({...prefs,color_scheme:"dark",dark_theme:rawId}));},{rawId});
  await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",rawId);await expect(page.locator(".ade")).toHaveCSS("--bg","#2b2436");await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const row=page.locator(".linked-theme-item").filter({hasText:"Snapshot owner"});await expect(row).toBeVisible();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",rawId);await expect(page.locator(".ade")).toHaveCSS("--bg","#2b2436");
  await row.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",rendererId);await expect(page.locator(".ade")).toHaveCSS("--bg","#172433");await page.locator(".custom-theme-item").filter({hasText:"Snapshot palette"}).getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",rawId);await expect(page.locator(".ade")).toHaveCSS("--bg","#2b2436");
 }finally{await request.delete(`http://127.0.0.1:7455/api/themes/${entry.id}`);fs.rmSync(folder,{recursive:true,force:true});}
});

test("colliding raw daemon variant IDs keep family renderer identities and migrate to the registry winner",async({page,request})=>{
 const packageRoot=fs.mkdtempSync(path.join(os.tmpdir(),"openade-native-collision-package-")),standaloneRoot=fs.mkdtempSync(path.join(os.tmpdir(),"openade-native-collision-file-")),packageFile=path.join(packageRoot,"package.json"),packageTheme=path.join(packageRoot,"dark.json"),standalone=path.join(standaloneRoot,"theme.json");
 fs.writeFileSync(packageFile,JSON.stringify({displayName:"Collision",contributes:{themes:[{label:"Dark",uiTheme:"vs-dark",path:"dark.json"}]}}));fs.writeFileSync(packageTheme,JSON.stringify({name:"Package collision palette",type:"dark",colors:{"editor.background":"#121b28"},tokenColors:[{scope:"keyword",settings:{foreground:"#a142d1"}}]}));fs.writeFileSync(standalone,JSON.stringify({name:"Collision-dark",type:"dark",colors:{"editor.background":"#271923"},tokenColors:[{scope:"keyword",settings:{foreground:"#28a6ba"}}]}));
 const entries:{id:string;name:string;variants:{id:string}[]}[]=[];
 try{const packageResponse=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:packageRoot,name:"Collision"}});expect(packageResponse.status()).toBe(201);entries.push(await packageResponse.json() as typeof entries[number]);const fileResponse=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:standalone,name:"Collision-dark"}});expect(fileResponse.status()).toBe(201);entries.push(await fileResponse.json() as typeof entries[number]);
  const [packageEntry,fileEntry]=entries,rawId=packageEntry.variants[0].id;expect(rawId).toBe("custom-collision-dark");expect(fileEntry.variants[0].id).toBe(rawId);const packageRendererId=nativeThemeId(packageEntry.id,rawId),fileRendererId=nativeThemeId(fileEntry.id,rawId);expect(packageRendererId).not.toBe(fileRendererId);
  await page.addInitScript(({id})=>{if(localStorage.getItem("openade.preferences"))return;localStorage.setItem("openade.preferences",JSON.stringify({color_scheme:"dark",dark_theme:id}));},{id:rawId});await ready(page);await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",fileRendererId);await expect(page.locator(".ade")).toHaveCSS("--bg","#271923");await expect.poll(async()=>{const stored=await page.evaluate(()=>localStorage.getItem("openade.preferences"));return JSON.parse(stored||"{}").dark_theme;}).toBe(fileRendererId);
  await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const packageRow=page.locator(".linked-theme-item").filter({hasText:"Collision"}).filter({hasText:"linked package"});await packageRow.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",packageRendererId);await expect(page.locator(".ade")).toHaveCSS("--bg","#121b28");await expect(page.locator(".ade")).toHaveCSS("--syntax-keyword","#a142d1");
  const fileRow=page.locator(".linked-theme-item").filter({hasText:"Collision-dark"});await fileRow.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",fileRendererId);await expect(page.locator(".ade")).toHaveCSS("--bg","#271923");await expect(page.locator(".ade")).toHaveCSS("--syntax-keyword","#28a6ba");await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",fileRendererId);await expect(page.locator(".ade")).toHaveCSS("--bg","#271923");
 }finally{for(const entry of entries)await request.delete(`http://127.0.0.1:7455/api/themes/${entry.id}`);fs.rmSync(packageRoot,{recursive:true,force:true});fs.rmSync(standaloneRoot,{recursive:true,force:true});}
});

test("linked JSON5 includes preserve child rule order and semantic foreground overlays",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-theme-precedence-")),themes=path.join(folder,"themes");fs.mkdirSync(themes);fs.writeFileSync(path.join(folder,"package.json"),`{ displayName: 'Precedence family', contributes: { themes: [{ label: 'Precedence Dark', uiTheme: 'vs-dark', path: 'themes/dark.json' },], }, }`);
 fs.writeFileSync(path.join(themes,"base.json"),`{ colors: { 'editor.background': '#171b22', }, tokenColors: [{ scope: 'keyword.control', settings: { foreground: '#111111', }, }, { scope: 'string', settings: { foreground: '#222222' }, },], }`);
 fs.writeFileSync(path.join(themes,"dark.json"),`{ include: 'base.json', tokenColors: [{ scope: 'keyword.control', settings: { foreground: '#333333' }, }, { scope: 'string', settings: { foreground: '#444444' }, },], semanticTokenColors: { keyword: '#555555', function: { foreground: '#666666', }, }, }`);
 const response=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:folder,name:"Precedence family"}});expect(response.status()).toBe(201);const entry=await response.json() as {id:string;variants:{id:string}[]};
 try{await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const family=page.locator(".linked-theme-item").filter({hasText:"Precedence family"});await family.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,entry.variants[0].id));await expect(page.locator(".ade")).toHaveCSS("--syntax-string","#444444");await expect(page.locator(".ade")).toHaveCSS("--syntax-keyword","#555555");await expect(page.locator(".ade")).toHaveCSS("--syntax-function","#666666");}
 finally{await request.delete(`http://127.0.0.1:7455/api/themes/${entry.id}`);fs.rmSync(folder,{recursive:true,force:true});}
});

test("import, apply, persist, replace, reject invalid input and remove active VS Code themes",async({page})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-custom-themes-"));const themesDir=path.join(folder,"themes");fs.mkdirSync(themesDir);
 fs.writeFileSync(path.join(folder,"package.json"),JSON.stringify({name:"fixture-theme",displayName:"Fixture Theme Family",contributes:{themes:[{label:"Fixture Light",uiTheme:"vs",path:"themes/light.json"},{label:"Fixture Dark",uiTheme:"vs-dark",path:"themes/dark.json"}]}}));
 fs.writeFileSync(path.join(themesDir,"light.json"),fixture("Fixture Light","light","#f3f5f8","#8b30c9","#b3261e"));
 fs.writeFileSync(path.join(themesDir,"dark.json"),fixture("Fixture Dark","dark","#171b22","#d7a4ff","#ff6670"));
 await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();
 await page.getByRole("button",{name:"Light",exact:true}).click();
 await page.getByLabel("Choose VS Code extension folder").setInputFiles(folder);
 await expect(page.getByText("Fixture Light imported. Fixture Dark imported.",{exact:true})).toBeVisible();
 const lightRow=page.locator(".custom-theme-item").filter({hasText:"Fixture Light"});await lightRow.getByRole("button",{name:"Apply",exact:true}).click();
 await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-fixture-light-light");
 await expect.poll(()=>page.locator(".ade").evaluate(el=>getComputedStyle(el).getPropertyValue("--bg").trim())).toBe("#f3f5f8");
 await expect.poll(()=>page.locator(".ade").evaluate(el=>getComputedStyle(el).getPropertyValue("--syntax-keyword").trim())).toBe("#8b30c9");
 await expect.poll(()=>page.locator(".ade").evaluate(el=>getComputedStyle(el).getPropertyValue("--ansi-red").trim())).toBe("#b3261e");
 await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-fixture-light-light");await expect(page.locator(".ade")).toHaveCSS("--bg","#f3f5f8");await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();

 await page.getByLabel("Replace existing theme").click();await page.getByRole("option",{name:"Fixture Light · light",exact:true}).click();
 await page.getByLabel("Choose VS Code theme JSON file").setInputFiles({name:"replacement.json",mimeType:"application/json",buffer:Buffer.from(fixture("Fixture Light","light","#e3edf4","#9747ff","#a51e15"))});
 await expect(page.getByText("Fixture Light imported and replaced.",{exact:true})).toBeVisible();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-fixture-light-light");
 await expect.poll(()=>page.locator(".ade").evaluate(el=>getComputedStyle(el).getPropertyValue("--bg").trim())).toBe("#e3edf4");

 await page.getByLabel("Choose VS Code theme JSON file").setInputFiles({name:"invalid.json",mimeType:"application/json",buffer:Buffer.from('{"name":"Broken","colors":{"editor.background":"url(https://invalid.test)"}}')});
 await expect(page.getByRole("status").filter({hasText:"Unsupported color"})).toBeVisible();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-fixture-light-light");await expect(page.locator(".ade")).toHaveCSS("--bg","#e3edf4");
 await expect(page.getByLabel("Remove Zeron Light")).toHaveCount(0);
 await page.getByLabel("Remove Fixture Light").click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","zeron-light");await expect(page.locator(".ade")).toHaveCSS("--bg","#ffffff");
 await expect(page.locator(".custom-theme-item")).toHaveCount(1);await page.getByRole("button",{name:"Dark",exact:true}).click();const darkRow=page.locator(".custom-theme-item").filter({hasText:"Fixture Dark"});await darkRow.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-fixture-dark-dark");await expect(page.locator(".ade")).toHaveCSS("--bg","#171b22");await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","custom-fixture-dark-dark");await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await page.getByLabel("Remove Fixture Dark").click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","zeron-dark");
 fs.rmSync(folder,{recursive:true,force:true});
});

test("linked theme sources reload safely and retain compiled palettes",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-linked-themes-"));const packageRoot=path.join(folder,"extension");const themesDir=path.join(packageRoot,"themes");fs.mkdirSync(themesDir,{recursive:true});
 const write=(background:string)=>fs.writeFileSync(path.join(themesDir,"dark.json"),`{ // JSON5 source\n include: "base.json", colors: { "editor.background": "${background}", "terminal.ansiRed": "#c43e64" } }`);
 fs.writeFileSync(path.join(packageRoot,"package.json"),`{ name: "linked-e2e", displayName: "Linked E2E", contributes: { themes: [{ label: "Linked E2E Dark", uiTheme: "vs-dark", path: "themes/dark.json" }, { label: "Broken sibling", uiTheme: "vs-dark", path: "themes/broken.json" }] } }`);
 fs.writeFileSync(path.join(themesDir,"base.json"),String.raw`{ /* block comment is valid JSON5 */ description: 'first\
second', colors: { "editor.background": "#151922", "foreground": "#f4f5f8", "sideBar.background": "#202633" }, tokenColors: [{ scope: "keyword", settings: { foreground: "#ba7cff" } }] }`);fs.writeFileSync(path.join(themesDir,"broken.json"),`{ colors: { "editor.background": "url(https://invalid.test)" } }`);write("#151922");
 const api=(method:string,target:string,body?:unknown)=>request.fetch(`http://127.0.0.1:7455${target}`,{method,headers:{Authorization:"Bearer openade-e2e-synthetic-token-2026","Content-Type":"application/json"},data:body});
 const linked=await api("POST","/api/themes/link",{path:packageRoot,name:"E2E linked"});expect(linked.ok()).toBeTruthy();const entry=await linked.json() as {id:string;failures:{name:string}[];status:{state:string}};expect(entry.status.state).toBe("warning");expect(entry.failures).toHaveLength(1);expect(entry.failures[0].name).toBe("Broken sibling");
 await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const row=page.locator(".linked-theme-item").filter({hasText:"Linked E2E"});await expect(row).toBeVisible();await expect(row.getByRole("button",{name:"Reveal",exact:true})).toHaveCount(0);await row.getByRole("button",{name:"Apply",exact:true}).click();const nativeId=nativeThemeId(entry.id,`${entry.id}-linked-e2e-dark`);await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeId);await expect(page.locator(".ade")).toHaveCSS("--bg","#151922");
 fs.writeFileSync(path.join(themesDir,"broken.json"),`{ colors: { "editor.background": "#18202a", "foreground": "#f4f5f8" } }`);write("#252b36");await row.getByRole("button",{name:"Reload",exact:true}).click();await expect(page.locator(".ade")).toHaveCSS("--bg","#252b36");const repaired=await api("GET","/api/themes");expect(repaired.ok()).toBeTruthy();const repairedLibrary=await repaired.json() as {entries:{id:string;failures?:{name:string}[];variants:{id:string}[];status:{state:string}}[]};const repairedEntry=repairedLibrary.entries.find(value=>value.id===entry.id)!;expect(repairedEntry.status.state).toBe("ready");expect(repairedEntry.failures).toBeUndefined();expect(repairedEntry.variants).toHaveLength(1);expect(repairedEntry.variants[0].id).toBe(`${entry.id}-linked-e2e-dark`);
 fs.writeFileSync(path.join(themesDir,"dark.json"),`{ colors: { "editor.background": "url(https://invalid.test)" } }`);await row.getByRole("button",{name:"Reload",exact:true}).click();await expect(row.getByText("unsupported color",{exact:false})).toBeVisible();await expect(page.locator(".ade")).toHaveCSS("--bg","#252b36");
 const editable=await api("POST",`/api/themes/${entry.id}/duplicate`,{mode:"editable"});expect(editable.ok()).toBeTruthy();const snapshot=await api("POST",`/api/themes/${entry.id}/duplicate`,{mode:"snapshot"});expect(snapshot.ok()).toBeTruthy();await page.reload();await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const refreshedRow=page.locator(".linked-theme-item").filter({has:page.getByText("Linked E2E",{exact:true})});const editableRow=page.locator(".linked-theme-item").filter({hasText:"editable file"});await expect(editableRow.getByRole("button",{name:"Reload",exact:true})).toBeVisible();await editableRow.getByRole("button",{name:"Reload",exact:true}).click();await refreshedRow.getByRole("button",{name:"Unlink",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"now a snapshot"})).toBeVisible();await page.reload();await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await expect(page.locator(".linked-theme-item").filter({has:page.getByText("Linked E2E",{exact:true})})).toContainText("snapshot");expect((await api("POST",`/api/themes/${entry.id}/reload`)).ok()).toBeFalsy();
 const traversal=path.join(themesDir,"escape.json");fs.writeFileSync(traversal,`{ include: "../../outside.json", colors: { "editor.background": "#111111" } }`);fs.writeFileSync(path.join(folder,"outside.json"),`{ colors: { "editor.background": "#111111" } }`);expect((await api("POST","/api/themes/link",{path:traversal,name:"escape"})).ok()).toBeFalsy();
 const cycleA=path.join(themesDir,"cycle-a.json"),cycleB=path.join(themesDir,"cycle-b.json");fs.writeFileSync(cycleA,`{ include: "cycle-b.json" }`);fs.writeFileSync(cycleB,`{ include: "cycle-a.json" }`);expect((await api("POST","/api/themes/link",{path:cycleA,name:"cycle"})).ok()).toBeFalsy();
 const oversized=path.join(themesDir,"large.json");fs.writeFileSync(oversized,Buffer.alloc(2*1024*1024+1," "));expect((await api("POST","/api/themes/link",{path:oversized,name:"large"})).ok()).toBeFalsy();
 for(const id of [entry.id,((await editable.json()) as {id:string}).id,((await snapshot.json()) as {id:string}).id])expect((await api("DELETE",`/api/themes/${id}`)).ok()).toBeTruthy();fs.rmSync(folder,{recursive:true,force:true});
});

test("removing a linked family repairs both active appearance preferences",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-mixed-linked-themes-"));const themes=path.join(folder,"themes");fs.mkdirSync(themes);fs.writeFileSync(path.join(folder,"package.json"),JSON.stringify({displayName:"Mixed family",contributes:{themes:[{label:"Mixed Light",uiTheme:"vs",path:"themes/light.json"},{label:"Mixed Dark",uiTheme:"vs-dark",path:"themes/dark.json"}]}}));fs.writeFileSync(path.join(themes,"light.json"),fixture("Mixed Light","light","#f5f7fa","#8144d8","#b3261e"));fs.writeFileSync(path.join(themes,"dark.json"),fixture("Mixed Dark","dark","#151922","#b18cff","#dc5272"));
 const api=(method:string,target:string,body?:unknown)=>request.fetch(`http://127.0.0.1:7455${target}`,{method,headers:{Authorization:"Bearer openade-e2e-synthetic-token-2026","Content-Type":"application/json"},data:body});const created=await api("POST","/api/themes/link",{path:folder,name:"mixed family"});expect(created.ok()).toBeTruthy();const entry=await created.json() as {id:string};
 await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const row=page.locator(".linked-theme-item").filter({hasText:"Mixed family"});await expect(row).toBeVisible();await row.locator(".custom-theme-item").filter({hasText:"Mixed Light"}).getByRole("button",{name:"Apply",exact:true}).click();await row.locator(".custom-theme-item").filter({hasText:"Mixed Dark"}).getByRole("button",{name:"Apply",exact:true}).click();await row.getByLabel("Remove Mixed family").click();await expect(page.getByRole("status").filter({hasText:"Mixed family removed"})).toBeVisible();await page.getByRole("button",{name:"Light",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","zeron-light");await page.getByRole("button",{name:"Dark",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id","zeron-dark");expect((await api("DELETE",`/api/themes/${entry.id}`)).ok()).toBeFalsy();fs.rmSync(folder,{recursive:true,force:true});
});


test("theme library recovers when shutdown interrupts the replacement between its two renames",async({page})=>{
 const data=path.join(tmp,"theme-backup-recovery"),source=path.join(tmp,"backup-theme.json");fs.writeFileSync(source,fixture("Recovery Theme","dark","#121212","#abcdef","#f45678"));const base="http://127.0.0.1:7478";const start=()=>spawn(path.join(tmp,"openade-e2e"),["--daemon","--addr","127.0.0.1:7478","--data-dir",data],{env:{...process.env,OPENADE_AUTH_TOKEN:token},stdio:"pipe"});const stop=async(child:ChildProcess)=>{if(child.exitCode!==null)return;child.kill("SIGTERM");await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error("fixture engine did not stop")),5000);child.once("exit",()=>{clearTimeout(timer);resolve();});});};let child=start();const healthy=()=>expect.poll(async()=>{try{return(await fetch(base+"/api/health")).status;}catch{return 0;}}).toBe(200);
 try{await healthy();const response=await fetch(base+"/api/themes/link",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({path:source})});expect(response.status).toBe(201);const entry=await response.json();await stop(child);const library=path.join(data,"custom-themes/library.json");fs.renameSync(library,library+".bak");child=start();await healthy();const restored=await(await fetch(base+"/api/themes",{headers:{Authorization:`Bearer ${token}`}})).json();expect(restored.entries[0].id).toBe(entry.id);expect(restored.entries[0].variants[0].document.colors["editor.background"]).toBe("#121212");
 await page.addInitScript(({base,token})=>Object.assign(window,{go:{main:{App:{EngineConnection:async()=>({url:base,token})}}}}),{base,token});await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();const libraryUI=page.getByRole("region",{name:"Linked theme library"});await expect(libraryUI).toContainText("Recovery Theme");await libraryUI.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,entry.variants[0].id));
 }finally{await stop(child);}
});

test("within-family duplicate labels reserve later canonical IDs and reject editable duplicate IDs",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-duplicate-variant-"));const themes=path.join(folder,"themes");fs.mkdirSync(themes);const declarations=[{label:"Dark",uiTheme:"vs-dark",path:"themes/first.json"},{label:"Dark",uiTheme:"vs-dark",path:"themes/second.json"},{label:"Dark 2",uiTheme:"vs-dark",path:"themes/third.json"}];fs.writeFileSync(path.join(folder,"package.json"),JSON.stringify({displayName:"Duplicate labels",contributes:{themes:declarations}}));const palette=["#141820","#242830","#343840"];for(const [index,file] of ["first.json","second.json","third.json"].entries())fs.writeFileSync(path.join(themes,file),fixture(`Duplicate ${index+1}`,"dark",palette[index],"#aa66ff","#cc3355"));
 const created=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:folder,name:"duplicate labels"}});expect(created.status()).toBe(201);const entry=await created.json() as {id:string;variants:{id:string}[]};const ids=entry.variants.map(variant=>variant.id);expect(ids).toEqual([`${entry.id}-dark`,`${entry.id}-dark-3`,`${entry.id}-dark-2`]);expect(new Set(ids).size).toBe(3);
 try{await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await page.getByRole("button",{name:"Dark",exact:true}).click();const family=page.locator(".linked-theme-item").filter({hasText:"Duplicate labels"});await expect(family).toBeVisible();for(const [index,color] of palette.entries()){await family.locator(".custom-theme-item").nth(index).getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,ids[index]));await expect(page.locator(".ade")).toHaveCSS("--bg",color);}fs.writeFileSync(path.join(themes,"first.json"),fixture("Duplicate 1","dark","#454950","#aa66ff","#cc3355"));await family.getByRole("button",{name:"Reload",exact:true}).click();await family.locator(".custom-theme-item").nth(0).getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveCSS("--bg","#454950");const snapshot=await request.post(`http://127.0.0.1:7455/api/themes/${entry.id}/duplicate`,{data:{mode:"snapshot"}});expect(snapshot.status()).toBe(201);const editable=await request.post(`http://127.0.0.1:7455/api/themes/${entry.id}/duplicate`,{data:{mode:"editable"}});expect(editable.status()).toBe(201);const editableEntry=await editable.json() as {id:string;source:{path:string};variants:{id:string}[]};expect(new Set(editableEntry.variants.map(variant=>variant.id)).size).toBe(3);await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,ids[0]));const editableFile=JSON.parse(fs.readFileSync(editableEntry.source.path,"utf8"));editableFile.variants[1].id=editableFile.variants[0].id;fs.writeFileSync(editableEntry.source.path,JSON.stringify(editableFile));const rejected=await request.post(`http://127.0.0.1:7455/api/themes/${editableEntry.id}/reload`);expect(rejected.status()).toBe(400);const library=await request.get("http://127.0.0.1:7455/api/themes");const persisted=(await library.json() as {entries:{id:string;variants:{id:string}[];status:{state:string}}[]}).entries.find(value=>value.id===editableEntry.id)!;expect(persisted.status.state).toBe("warning");expect(new Set(persisted.variants.map(variant=>variant.id)).size).toBe(3);
 }finally{const entries=await request.get("http://127.0.0.1:7455/api/themes");for(const value of (await entries.json() as {entries:{id:string}[]}).entries.filter(value=>value.id===entry.id||value.id.startsWith(entry.id+"-copy")))await request.delete(`http://127.0.0.1:7455/api/themes/${value.id}`);fs.rmSync(folder,{recursive:true,force:true});}
});

test("broken duplicate declarations keep the selected sibling identity through repair and reject reordering",async({page,request})=>{
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),"openade-declaration-recovery-"));const manifest=path.join(folder,"package.json"),first=path.join(folder,"first.json"),second=path.join(folder,"second.json");const declarations=[{label:"Dark",uiTheme:"vs-dark",path:"first.json"},{label:"Dark",uiTheme:"vs-dark",path:"second.json"},{label:"Dark 2",uiTheme:"vs-dark"}];const writeManifest=(items=declarations)=>fs.writeFileSync(manifest,JSON.stringify({displayName:"Declaration recovery",contributes:{themes:items}}));writeManifest();fs.writeFileSync(first,`{ colors: { "editor.background": "url(https://invalid.test)" } }`);fs.writeFileSync(second,fixture("Selected sibling","dark","#253040","#b18cff","#dc5272"));
 const created=await request.post("http://127.0.0.1:7455/api/themes/link",{data:{path:folder,name:"declaration recovery"}});expect(created.status()).toBe(201);const entry=await created.json() as {id:string;variants:{id:string}[];failures:{id:string}[]};const selectedID=`${entry.id}-dark-3`;expect(entry.variants.map(variant=>variant.id)).toEqual([selectedID]);expect(entry.failures.map(failure=>failure.id)).toEqual([`${entry.id}-dark`,`${entry.id}-dark-2`]);
 try{await ready(page);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await page.getByRole("button",{name:"Dark",exact:true}).click();const family=page.locator(".linked-theme-item").filter({hasText:"Declaration recovery"});await family.getByRole("button",{name:"Apply",exact:true}).click();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,selectedID));await expect(page.locator(".ade")).toHaveCSS("--bg","#253040");fs.writeFileSync(first,fixture("Repaired first","dark","#4a1820","#b18cff","#dc5272"));await family.getByRole("button",{name:"Reload",exact:true}).click();await expect(page.locator(".ade")).toHaveCSS("--bg","#253040");const repaired=await request.get("http://127.0.0.1:7455/api/themes");const repairedEntry=(await repaired.json() as {entries:{id:string;variants:{id:string;document:{colors:{"editor.background":string}}}[]}[]}).entries.find(value=>value.id===entry.id)!;expect(repairedEntry.variants).toHaveLength(1);expect(repairedEntry.variants[0].id).toBe(selectedID);expect(repairedEntry.variants[0].document.colors["editor.background"]).toBe("#253040");await page.reload();await expect(page.locator(".ade")).toHaveAttribute("data-theme-id",nativeThemeId(entry.id,selectedID));await expect(page.locator(".ade")).toHaveCSS("--bg","#253040");writeManifest([declarations[1],declarations[0],declarations[2]]);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await page.locator(".linked-theme-item").filter({hasText:"Declaration recovery"}).getByRole("button",{name:"Reload",exact:true}).click();await expect(page.getByLabel("Linked theme library").getByRole("status").filter({hasText:"different source declaration"})).toBeVisible();await expect(page.locator(".ade")).toHaveCSS("--bg","#253040");
 }finally{await request.delete(`http://127.0.0.1:7455/api/themes/${entry.id}`);fs.rmSync(folder,{recursive:true,force:true});}
});
