import { test } from "./helpers";
import { expect } from "@playwright/test";
import * as fs from "node:fs";
import * as path from "node:path";
import { spawn,spawnSync,ChildProcess } from "node:child_process";
import { create,daemon,otherRepo,repo,status,tmp,token } from "./helpers";
test.describe.configure({mode:"serial"});
const headers={Authorization:`Bearer ${token}`,"Content-Type":"application/json"};
async function replay(url:string){return new Promise<{data:string;cursor:number;reset:boolean;offset:number}>((resolve,reject)=>{const ws=new WebSocket(url);const timeout=setTimeout(()=>{ws.close();reject(Error("stream timed out"));},5000);ws.onerror=()=>{clearTimeout(timeout);reject(Error("stream failed"));};ws.onmessage=event=>{const message=JSON.parse(String(event.data));if(message.type==="output"){clearTimeout(timeout);ws.close();resolve(message);}};});}
function start(port:number,data:string){const child=spawn(path.join(tmp,"openade-e2e"),["--daemon","--addr",`127.0.0.1:${port}`,"--data-dir",data],{env:{...process.env,OPENADE_AUTH_TOKEN:token,OPENADE_PROVIDER_HOME:path.join(tmp,"provider-home"),PATH:`${path.join(tmp,"bin")}:${process.env.PATH}`,SHELL:"/bin/sh"},stdio:"pipe"});return child;}
async function stopped(child:ChildProcess,signal:NodeJS.Signals="SIGTERM"){if(child.exitCode!==null)return;child.kill(signal);await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error("engine did not stop")),8000);child.once("exit",()=>{clearTimeout(timeout);resolve();});});}

test("local control requires authentication and rejects foreign origins and non-loopback binding",async({request})=>{
 expect((await request.get(`${daemon}/api/state`,{headers:{Authorization:""}})).status()).toBe(401);expect((await request.get(`${daemon}/api/state`,{headers:{Origin:"https://hostile.example"}})).status()).toBe(403);
 const result=spawnSync(path.join(tmp,"openade-e2e"),["--daemon","--addr","0.0.0.0:7468","--data-dir",path.join(tmp,"invalid-bind")],{encoding:"utf8",timeout:5000});expect(result.status).not.toBe(0);expect(result.stderr).toContain("loopback");
});
test("identically named repositories keep worktrees, branches, files, histories and terminals isolated",async({request})=>{
 const first=await create(request,"Multi repo first",{agent:"shell",prompt:"printf FIRST; sleep 5",ticket_key:"ADE-42"});const second=await create(request,"Multi repo second",{agent:"shell",prompt:"printf SECOND; sleep 5",repo_root:otherRepo});expect(first.worktree_path).not.toBe(second.worktree_path);expect(first.branch).toMatch(/^ade-42\//);
 fs.writeFileSync(path.join(first.worktree_path,"only-first.txt"),"FIRST");const secondFiles=(await (await request.get(`${daemon}/api/sessions/${second.id}/files`)).json()).files;expect(secondFiles).not.toContain("only-first.txt");expect(fs.existsSync(path.join(repo,"only-first.txt"))).toBe(false);
 for(const session of [first,second]){const terminal=await (await request.post(`${daemon}/api/sessions/${session.id}/terminals`,{data:{title:"Independent shell"}})).json();expect(terminal.cwd).toBe(session.worktree_path);expect(terminal.session_id).toBe(session.id);await request.post(`${daemon}/api/terminals/${terminal.id}/input`,{data:{data:"printf 'ROUND_TRIP\\n'\n"}});await expect.poll(async()=>{const result=await replay(`ws://127.0.0.1:7455/api/terminals/${terminal.id}/stream?token=${token}`);return result.data;}).toContain("ROUND_TRIP");await request.post(`${daemon}/api/terminals/${terminal.id}/stop`);await request.post(`${daemon}/api/sessions/${session.id}/stop`);}
});
test("native chat pipe and Direct TUI are exclusive transports; PTY input and resize round-trip",async({request})=>{
 const native=await create(request,"Transport native",{prompt:"wait-provider native"});expect((await request.post(`${daemon}/api/sessions/${native.id}/input`,{data:{data:"oops"}})).status()).toBe(409);expect((await request.post(`${daemon}/api/sessions/${native.id}/resize`,{data:{rows:28,cols:90}})).status()).toBe(409);
 const tui=await create(request,"Transport TUI",{mode:"tui"});expect((await request.post(`${daemon}/api/sessions/${tui.id}/resize`,{data:{rows:28,cols:90}})).status()).toBe(204);expect((await request.post(`${daemon}/api/sessions/${tui.id}/input`,{data:{data:"size\n"}})).status()).toBe(204);await expect.poll(async()=>{const result=await replay(`ws://127.0.0.1:7455/api/sessions/${tui.id}/stream?token=${token}`);return result.data;}).toContain("size:90x28");await request.post(`${daemon}/api/sessions/${native.id}/stop`);await request.post(`${daemon}/api/sessions/${tui.id}/stop`);
});
test("cancellation remains stopped even when a provider handles SIGTERM successfully; crashes remain failed",async({request})=>{
 const cancelled=await create(request,"Cancelled turn",{prompt:"wait-provider cancellation"});await request.post(`${daemon}/api/sessions/${cancelled.id}/stop`);await expect.poll(()=>status(request,cancelled.id)).toBe("stopped");const turn=(await (await request.get(`${daemon}/api/sessions/${cancelled.id}/turns`)).json()).turns[0];expect(turn.status).toBe("stopped");expect(turn.id).toBe(cancelled.current_turn_id);
 const failed=await create(request,"Failed turn",{prompt:"fail-provider"});await expect.poll(()=>status(request,failed.id)).toBe("failed");expect((await (await request.get(`${daemon}/api/sessions/${failed.id}`)).json()).exit_code).toBe(7);
 const killed=await create(request,"Killed provider",{prompt:"wait-provider death"});const runtime=await (await request.get(`${daemon}/api/sessions/${killed.id}`)).json();process.kill(runtime.pid,"SIGKILL");await expect.poll(()=>status(request,killed.id)).toBe("failed");
});
test("byte-cursor replay reconnects without duplicates, bounds stale replay and releases daemon subscribers",async({request})=>{
 const session=await create(request,"Byte replay",{agent:"shell",prompt:"printf REPLAY_MARK; sleep 20"});const url=`ws://127.0.0.1:7455/api/sessions/${session.id}/stream?token=${token}`;await expect.poll(async()=> (await replay(url)).data).toContain("REPLAY_MARK");const initial=await replay(url);expect(initial.data.split("REPLAY_MARK").length-1).toBe(1);const caughtUp=await replay(`${url}&after=${initial.cursor}`);expect(caughtUp.data).toBe("");expect(caughtUp.cursor).toBe(initial.cursor);const stale=await replay(`${url}&after=99999999`);expect(stale.reset).toBe(true);expect(stale.data).toContain("REPLAY_MARK");
 await expect.poll(async()=> (await (await request.get(`${daemon}/api/diagnostics`)).json()).stream_clients).toBe(0);await request.post(`${daemon}/api/sessions/${session.id}/stop`);
});
test("file editor rejects path escape, symlinks, binary and large files, and conflicting writes",async({request})=>{
 const session=await create(request,"File boundary");const endpoint=`${daemon}/api/sessions/${session.id}/file`;const outside=path.join(tmp,"outside.txt");fs.writeFileSync(outside,"outside");fs.symlinkSync(outside,path.join(session.worktree_path,"outside-link"));fs.writeFileSync(path.join(session.worktree_path,"binary.bin"),Buffer.from([0,1,2]));fs.writeFileSync(path.join(session.worktree_path,"large.txt"),"x".repeat(2*1024*1024+1));
 for(const name of ["../outside.txt","outside-link","binary.bin","large.txt",".git"]){expect((await request.get(`${endpoint}?path=${encodeURIComponent(name)}`)).status()).toBeGreaterThanOrEqual(400);}
 const original=(await (await request.get(`${endpoint}?path=README.md`)).json()).content;fs.writeFileSync(path.join(session.worktree_path,"README.md"),"agent changed this\n");expect((await request.put(`${endpoint}?path=README.md`,{data:{original,content:"overwrite"}})).status()).toBe(409);expect(fs.readFileSync(path.join(session.worktree_path,"README.md"),"utf8")).toBe("agent changed this\n");const largeOriginal="a".repeat(1700*1024);fs.writeFileSync(path.join(session.worktree_path,"README.md"),largeOriginal);expect((await request.put(`${endpoint}?path=README.md`,{data:{original:largeOriginal,content:"b".repeat(1700*1024)}})).status()).toBe(200);fs.writeFileSync(path.join(session.worktree_path,"README.md"),"x".repeat(5*1024*1024));const oversizedDiff=await request.get(`${daemon}/api/sessions/${session.id}/diff`);expect(oversizedDiff.status()).toBe(500);expect(await oversizedDiff.text()).toContain("preview limit");fs.writeFileSync(path.join(session.worktree_path,"README.md"),original);for(let i=0;i<5;i++)fs.writeFileSync(path.join(session.worktree_path,`untracked-${i}.txt`),"y".repeat(900*1024));const aggregatedDiff=await request.get(`${daemon}/api/sessions/${session.id}/diff`);expect(aggregatedDiff.status()).toBe(500);expect(await aggregatedDiff.text()).toContain("preview limit");
});
test("snapshot plus sequenced SSE reflects committed changes and rejects a competing profile owner",async({request})=>{
 const snapshot=await (await request.get(`${daemon}/api/state`)).json();const controller=new AbortController();const responsePromise=fetch(`${daemon}/api/events?after=${snapshot.sequence}&token=${token}`,{signal:controller.signal});
 // A heartbeat initially makes the stream observable even before state changes.
 const session=await create(request,"Transactional event");const response=await responsePromise;const reader=response.body!.getReader();let data="";while(!data.includes(session.id)){const part=await reader.read();if(part.done)break;data+=new TextDecoder().decode(part.value);}controller.abort();expect(data).toContain(session.id);const current=await (await request.get(`${daemon}/api/state`)).json();expect(current.sequence).toBeGreaterThan(snapshot.sequence);expect(current.sessions.some((s:{id:string})=>s.id===session.id)).toBe(true);
 const before=await status(request,session.id);const competing=spawnSync(path.join(tmp,"openade-e2e"),["--daemon","--addr","127.0.0.1:7468","--data-dir",path.join(tmp,"data")],{encoding:"utf8",timeout:5000,env:{...process.env,OPENADE_AUTH_TOKEN:token}});expect(competing.status).not.toBe(0);expect(competing.stderr).toContain("another engine owns this profile");expect(await status(request,session.id)).toBe(before);
});
test("engine death and restart preserve sessions, turns, transcripts and queued messages in an explicit profile",async()=>{
 const port=7467;const base=`http://127.0.0.1:${port}`;const data=path.join(tmp,"recovery-data");let child=start(port,data);
 try{await expect.poll(async()=>{try{return(await fetch(base+"/api/health")).status;}catch{return 0;}}).toBe(200);
 const session=await (await fetch(base+"/api/sessions",{method:"POST",headers,body:JSON.stringify({title:"Restart recovery",prompt:"wait-provider recovery",agent:"codex",repo_root:repo,base_branch:"main"})})).json();await fetch(`${base}/api/sessions/${session.id}/message-queue`,{method:"POST",headers,body:JSON.stringify({text:"queued after recovery"})});await stopped(child,"SIGKILL");child=start(port,data);await expect.poll(async()=>{try{return(await fetch(base+"/api/health")).status;}catch{return 0;}}).toBe(200);
 await expect.poll(async()=> (await (await fetch(`${base}/api/sessions/${session.id}`,{headers})).json()).generation).toBe(2);const turns=(await (await fetch(`${base}/api/sessions/${session.id}/turns`,{headers})).json()).turns;expect(turns.find((turn:{generation:number})=>turn.generation===1).status).toBe("interrupted");expect(turns.find((turn:{generation:number})=>turn.generation===2).queue_message_id).toBeTruthy();expect(fs.readFileSync(path.join(data,"transcripts",session.id+".log"),"utf8")).toContain("queued after recovery");
 }finally{await stopped(child);}
});

test("switching surfaces interrupts the old turn, resumes the same provider identity, and admits one next turn",async({request})=>{
 const session=await create(request,"Switch surface identity",{prompt:"wait-provider switching"});await expect.poll(()=>fs.readFileSync(path.join(tmp,"data/transcripts",session.id+".log"),"utf8")).toContain("thread.started");
 expect((await request.post(`${daemon}/api/sessions/${session.id}/surface`,{data:{mode:"tui"}})).status()).toBe(202);const turns=(await(await request.get(`${daemon}/api/sessions/${session.id}/turns`)).json()).turns;expect(turns.find((t:{generation:number})=>t.generation===1).status).toBe("interrupted");const transcript=await replay(`ws://127.0.0.1:7455/api/sessions/${session.id}/stream?token=${token}`);expect(transcript.data).toContain("codex-"+session.id);expect((await request.post(`${daemon}/api/sessions/${session.id}/surface`,{data:{mode:"chat"}})).status()).toBe(202);
 const results=await Promise.all([request.post(`${daemon}/api/sessions/${session.id}/messages`,{data:{text:"wait-provider first"}}),request.post(`${daemon}/api/sessions/${session.id}/messages`,{data:{text:"wait-provider competing"}})]);expect(results.map(result=>result.status()).sort()).toEqual([202,409]);await request.post(`${daemon}/api/sessions/${session.id}/stop`);
});

test("an engine-generated private token survives restart and authenticates only its own profile",async()=>{
 const data=path.join(tmp,"generated-token-profile");const base="http://127.0.0.1:7469";const launch=()=>{const env={...process.env};delete env.OPENADE_AUTH_TOKEN;return spawn(path.join(tmp,"openade-e2e"),["--daemon","--addr","127.0.0.1:7469","--data-dir",data],{env,stdio:"pipe"});};let child=launch();try{
 await expect.poll(async()=>{try{return(await fetch(base+"/api/health")).status;}catch{return 0;}}).toBe(200);const generated=fs.readFileSync(path.join(data,"engine.token"),"utf8");expect(generated).toMatch(/^[a-f0-9]{64}$/);expect(fs.statSync(path.join(data,"engine.token")).mode&0o777).toBe(0o600);expect((await fetch(base+"/api/state")).status).toBe(401);expect((await fetch(base+"/api/state",{headers:{Authorization:"Bearer "+generated}})).status).toBe(200);await stopped(child);child=launch();await expect.poll(async()=>{try{return(await fetch(base+"/api/health")).status;}catch{return 0;}}).toBe(200);expect(fs.readFileSync(path.join(data,"engine.token"),"utf8")).toBe(generated);expect(fs.readdirSync(data).filter(name=>name.startsWith(".engine-token-"))).toEqual([]);
 }finally{await stopped(child);}
});

test('terminal stop escalates when an interactive shell ignores termination and releases its PTY',async({request})=>{
 const session=await create(request,'Stubborn terminal cleanup');await expect.poll(()=>status(request,session.id)).toBe('completed');const terminal=await(await request.post(`${daemon}/api/sessions/${session.id}/terminals`,{data:{title:'Stubborn shell'}})).json();fs.writeFileSync(path.join(session.worktree_path,'.e2e-stubborn.sh'),"trap '' TERM\nprintf 'STUBBORN_READY\\n'\nwhile :; do sleep 1; done\n");await request.post(`${daemon}/api/terminals/${terminal.id}/input`,{data:{data:'sh .e2e-stubborn.sh\n'}});await expect.poll(async()=> (await replay(`ws://127.0.0.1:7455/api/terminals/${terminal.id}/stream?token=${token}`)).data).toContain('STUBBORN_READY');await request.post(`${daemon}/api/terminals/${terminal.id}/stop`);await expect.poll(async()=>{const list=await(await request.get(`${daemon}/api/sessions/${session.id}/terminals`)).json();return list.terminals.find((item:{id:string})=>item.id===terminal.id)?.status;}).toBe('stopped');await expect.poll(async()=>(await(await request.get(`${daemon}/api/diagnostics`)).json()).live_terminals).toBe(0);
});

test('registered projects survive an engine restart, normalize Git subfolders, and non-Git Codex turns keep their sandbox',async()=>{
 const os=await import('node:os');const folder=fs.mkdtempSync(path.join(os.tmpdir(),'openade-local-project-e2e-'));fs.writeFileSync(path.join(folder,'README.md'),'Local project fixture\n');const base='http://127.0.0.1:7470',data=path.join(tmp,'project-recovery');let child=start(7470,data);
 const send=(url:string,method='GET',body?:unknown)=>fetch(base+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});
 try{
 await expect.poll(async()=>{try{return(await fetch(base+'/api/health')).status;}catch{return 0;}}).toBe(200);
 expect((await send('/api/projects','POST',{path:folder})).status).toBe(201);
 const fifo=path.join(folder,'blocked-pipe');spawnSync('mkfifo',[fifo]);expect((await send('/api/projects/directories?path='+encodeURIComponent(fifo))).status).toBe(400);fs.unlinkSync(fifo);
 const normalized=await(await send('/api/projects','POST',{path:path.join(repo,'.agents')})).json();expect(normalized.path).toBe(fs.realpathSync(repo));
 expect((await send('/api/projects','POST',{path:path.join(tmp,'fixture-repo.git')})).status).toBe(400);
 const broken=path.join(folder,'broken-git');fs.mkdirSync(broken);fs.mkdirSync(path.join(broken,'.git'));const alias=path.join(folder,'git-alias');fs.symlinkSync(broken,alias);expect((await send('/api/projects','POST',{path:alias})).status).toBe(400);expect((await send('/api/sessions','POST',{title:'Reject broken Git alias',agent:'codex',prompt:'Do not run',checkout:'current',repo_root:alias})).status).toBeGreaterThanOrEqual(400);
 await stopped(child);child=start(7470,data);await expect.poll(async()=>{try{return(await fetch(base+'/api/health')).status;}catch{return 0;}}).toBe(200);
 const snapshot=await(await send('/api/state')).json();expect(snapshot.projects).toContain(fs.realpathSync(folder));expect(snapshot.projects).toContain(fs.realpathSync(repo));
 const session=await(await send('/api/sessions','POST',{title:'Folder round trip',prompt:'Folder first turn',agent:'codex',checkout:'current',repo_root:folder})).json();expect(session.branch).toBe('');expect(session.worktree_path).toBe(fs.realpathSync(folder));
 await expect.poll(async()=>(await(await send('/api/sessions/'+session.id)).json()).status).toBe('completed');
 const argsPath=path.join(tmp,'provider-home/args',session.id+'.json');const args=()=>JSON.parse(fs.readFileSync(argsPath,'utf8')) as string[];expect(args()).toContain('--skip-git-repo-check');expect(args().slice(0,5)).toEqual(['exec','--json','--sandbox','workspace-write','--skip-git-repo-check']);
 expect((await send('/api/sessions/'+session.id+'/messages','POST',{text:'Folder follow-up'})).status).toBe(202);await expect.poll(async()=>(await(await send('/api/sessions/'+session.id)).json()).status).toBe('completed');expect(args()).toContain('resume');expect(args()).toContain('--skip-git-repo-check');
 fs.symlinkSync(path.join(repo,'README.md'),path.join(folder,'outside-link'));const files=await(await send('/api/sessions/'+session.id+'/files')).json();expect(files.files).toContain('README.md');expect(files.files).not.toContain('outside-link');expect((await send('/api/sessions/'+session.id+'/file?path=outside-link')).status).toBeGreaterThanOrEqual(400);
 }finally{await stopped(child);fs.rmSync(folder,{recursive:true,force:true});}
});


test('optional model cache cannot stall metadata and recovers after invalid or nonregular files',async({request})=>{
 const cache=path.join(tmp,'provider-home/.codex/models_cache.json');const original=fs.readFileSync(cache);
 try{fs.unlinkSync(cache);expect(spawnSync('mkfifo',[cache]).status).toBe(0);const started=Date.now();const response=await request.get(`${daemon}/api/meta`,{timeout:2500});expect(response.status()).toBe(200);expect(Date.now()-started).toBeLessThan(2000);const meta=await response.json();expect(meta.agents.find((agent:{id:string})=>agent.id==='codex').models).toEqual([]);expect((await request.get(`${daemon}/api/health`)).status()).toBe(200);
 fs.unlinkSync(cache);fs.writeFileSync(cache,'x'.repeat(2*1024*1024+1));const oversized=await(await request.get(`${daemon}/api/meta`)).json();expect(oversized.agents.find((agent:{id:string})=>agent.id==='codex').models).toEqual([]);fs.writeFileSync(cache,original);await expect.poll(async()=>{const restored=await(await request.get(`${daemon}/api/meta`)).json();return restored.agents.find((agent:{id:string})=>agent.id==='codex').models.map((model:{id:string})=>model.id);}).toContain('fixture-sol');
 }finally{fs.rmSync(cache,{force:true});fs.writeFileSync(cache,original);}
});
