import {test,create,ready,open,daemon,status} from './helpers';
import {expect} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const png=fs.readFileSync(new URL('./fixtures/preview-grid.png',import.meta.url));

test('workspace image preview zooms and pans locally, Markdown preview preserves edits and undo',async({page,request})=>{
 const session=await create(request,'File preview parity audit');await expect.poll(()=>status(request,session.id)).toBe('completed');
 fs.mkdirSync(path.join(session.worktree_path,'docs'));fs.writeFileSync(path.join(session.worktree_path,'docs/grid.png'),png);fs.writeFileSync(path.join(session.worktree_path,'docs/guide.md'),'# Preview guide\n\n**This deliberately long emphasized description must wrap naturally in a narrow Markdown preview instead of inheriting the editor filename ellipsis and clipping the rest of its sentence.**\n\n![Workspace image](grid.png)\n\n![Outside image](../../outside.png)\n');
 await ready(page);await open(page,'File preview parity audit');await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'docs',exact:true}).click();await page.getByRole('treeitem',{name:'docs/grid.png',exact:true}).click();
 const viewport=page.getByRole('region',{name:'grid.png image viewport'});await expect(viewport).toBeVisible();await expect.poll(()=>viewport.locator('img').evaluate(node=>(node as HTMLImageElement).naturalWidth)).toBe(1200);expect(await page.getByLabel('Save file',{exact:true}).isEnabled()).toBe(false);
 await expect.poll(()=>viewport.evaluate(node=>node.clientWidth)).toBeGreaterThan(300);await expect.poll(()=>viewport.evaluate(node=>Math.abs(Number(node.getAttribute('data-scale'))-Math.min(node.clientWidth/1200,node.clientHeight/900,1)))).toBeLessThan(.002);const fitted=Number(await viewport.getAttribute('data-scale'));await viewport.evaluate(node=>{const r=node.getBoundingClientRect();node.dispatchEvent(new WheelEvent('wheel',{bubbles:true,cancelable:true,ctrlKey:true,deltaY:-500,clientX:r.x+r.width/2,clientY:r.y+r.height/2}));});await expect.poll(async()=>Number(await viewport.getAttribute('data-scale'))).toBeGreaterThan(fitted);
 const box=(await viewport.boundingBox())!;const before=await viewport.locator('img').evaluate(node=>(node as HTMLElement).style.left);await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+80,box.y+box.height/2+40);await page.mouse.up();expect(await viewport.locator('img').evaluate(node=>(node as HTMLElement).style.left)).not.toBe(before);
 await viewport.focus();await page.keyboard.press('0');await expect.poll(()=>viewport.evaluate(node=>Math.abs(Number(node.getAttribute('data-scale'))-Math.min(node.clientWidth/1200,node.clientHeight/900,1)))).toBeLessThan(.002);
 await page.getByRole('treeitem',{name:'docs/guide.md',exact:true}).click();const editor=page.getByRole('textbox',{name:'Edit docs/guide.md',exact:true});await editor.focus();await page.keyboard.press(process.platform==='darwin'?'Meta+End':'Control+End');await page.keyboard.type('\nUnsaved preview text');
 await page.getByLabel('Preview Markdown',{exact:true}).click();await expect(page.locator('.file-markdown-preview')).toContainText('Unsaved preview text');await expect(page.locator('.file-markdown-preview strong')).toHaveCSS('white-space','normal');expect(await page.locator('.file-markdown-preview strong').evaluate(node=>{const range=document.createRange();range.selectNodeContents(node);return range.getClientRects().length;})).toBeGreaterThan(1);await expect(page.getByText('Image unavailable: Outside image')).toBeVisible();const image=page.getByLabel('View Workspace image');await expect.poll(()=>image.locator('img').evaluate(node=>(node as HTMLImageElement).naturalWidth)).toBe(1200);await image.click();await expect(page.getByRole('dialog',{name:'Workspace image',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(image).toBeFocused();
 await page.getByLabel('Edit Markdown',{exact:true}).click();await expect(editor).toContainText('Unsaved preview text');await editor.focus();await page.keyboard.press(process.platform==='darwin'?'Meta+z':'Control+z');await expect(editor).not.toContainText('Unsaved preview text');
});

test('file media endpoint rejects traversal, links, non-images and unauthenticated access',async({request,page})=>{
 const session=await create(request,'File media boundaries');fs.writeFileSync(path.join(session.worktree_path,'grid.png'),png);fs.symlinkSync(path.join(session.worktree_path,'grid.png'),path.join(session.worktree_path,'link.png'));fs.writeFileSync(path.join(session.worktree_path,'unsafe.svg'),'<svg xmlns="http://www.w3.org/2000/svg"/>');
 const media=`${daemon}/api/sessions/${session.id}/file-media?path=`;const response=await request.get(media+'grid.png');expect(response.status()).toBe(200);expect(await response.body()).toEqual(png);
 for(const file of ['../grid.png','link.png','README.md','unsafe.svg','.git/config'])expect((await request.get(media+encodeURIComponent(file))).status()).toBeGreaterThanOrEqual(400);
 expect((await page.request.get(media+'grid.png')).status()).toBe(401);
});
