import {expect} from "@playwright/test";
import {execFileSync} from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import {create,daemon,open,panel,ready,test,tmp} from "./helpers";

test("history columns persist and a commit opens a read-only diff tab",async({page,request})=>{
 const session=await create(request,"History parity");
 const historyResponse=await request.get(`${daemon}/api/sessions/${session.id}/history`);
 expect(historyResponse.ok(),await historyResponse.text()).toBe(true);
 const {commits}=await historyResponse.json() as {commits:{sha:string;subject:string}[]};
 expect(commits.length).toBeGreaterThan(0);
 const sha=commits[0].sha;
 expect((await request.get(`${daemon}/api/sessions/${session.id}/diff?scope=commit&sha=not-a-sha`)).status()).toBe(400);
 expect((await request.get(`${daemon}/api/sessions/${session.id}/diff?scope=commit&sha=${"0".repeat(40)}`)).status()).toBe(404);
 const diffResponse=await request.get(`${daemon}/api/sessions/${session.id}/diff?scope=commit&sha=${sha}`);
 expect(diffResponse.ok(),await diffResponse.text()).toBe(true);
 expect((await diffResponse.json()).diff).toContain("diff --git");
 await ready(page);await open(page,"History parity");await panel(page,"History");
 await expect(page.getByLabel("Search history")).toBeVisible();
 await page.getByLabel("History columns").click();
 const menu=page.getByRole("menu",{name:"History columns"});
 await expect(menu).toBeVisible();
 await menu.getByRole("menuitemcheckbox",{name:"Date"}).click();
 await expect(page.getByRole("menuitemcheckbox",{name:"Date"})).toHaveAttribute("aria-checked","false");
 await page.keyboard.press("Escape");
 await expect(page.getByLabel("History columns")).toBeFocused();
 await page.getByRole("button",{name:"Author column"}).click();
 const authorMenu=page.getByRole("menu",{name:"Author display"});
 await authorMenu.getByRole("menuitemradio",{name:"Name"}).click();
 await expect(page.locator(".history-row .history-cell").first()).toContainText(/\S/);
 await page.reload();await expect(page.locator(".session-title h1")).toHaveText("History parity");
 await panel(page,"History");
 await expect(page.locator(".history-heading")).not.toContainText("Date");
 await expect(page.getByRole("button",{name:"Author column"})).toBeVisible();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("openade.preferences")!).history_author_display)).toBe("name");
 const resize=page.getByRole("separator",{name:"Resize Author column"});
 await resize.focus();await page.keyboard.press("ArrowRight");
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("openade.preferences")!).history_widths.author)).toBe(92);
 await page.getByRole("button",{name:"Author column"}).focus();await page.keyboard.press("Alt+ArrowRight");
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("openade.preferences")!).history_order)).toEqual(["date","author","sha"]);
 await page.getByRole("button",{name:"Author column"}).dragTo(page.getByRole("button",{name:"SHA column"}));
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("openade.preferences")!).history_order)).toEqual(["date","sha","author"]);
 await page.locator(".history-row").first().click();
 await expect(page.getByRole("tab",{name:`Commit ${sha.slice(0,7)}`})).toBeVisible();
 await expect(page.locator(".commit-diff-label")).toHaveText(`Commit ${sha.slice(0,7)}`);
 await expect(page.locator(".diff-document").first()).toBeVisible();
 await expect(page.getByLabel("Diff scope")).toHaveCount(0);
 await expect(page.getByRole("button",{name:"Commit",exact:true})).toHaveCount(0);
 await expect(page.getByRole("button",{name:"Stage",exact:true})).toHaveCount(0);
});

test("shell session panels fill the available workspace",async({page,request})=>{
 await create(request,"Shell history layout",{agent:"shell",mode:"chat"});
 await ready(page);await open(page,"Shell history layout");await panel(page,"History");
 await expect(page.getByLabel("Search history")).toBeVisible();
 const widths=await page.locator(".session-workspace, .work-panel-clip").evaluateAll(elements=>elements.map(element=>element.getBoundingClientRect().width));
 expect(widths[1]).toBeGreaterThan(widths[0]*.7);
 const positions=await page.locator(".session-header, .work-panel-clip").evaluateAll(elements=>elements.map(element=>({top:element.getBoundingClientRect().top,bottom:element.getBoundingClientRect().bottom})));
 expect(positions[1].top).toBeGreaterThanOrEqual(positions[0].bottom-1);
});

test("history pages and searches old commits, shows branch graph and fetches remote refs",async({page,request})=>{
 const root=fs.mkdtempSync(path.join(tmp,"history-many-")),remote=path.join(root,"remote.git"),checkout=path.join(root,"checkout"),publisher=path.join(root,"publisher");
 const git=(cwd:string,...args:string[])=>execFileSync("git",["-C",cwd,...args],{encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();
 execFileSync("git",["init","-q","-b","main",checkout]);
 git(checkout,"config","user.name","History Fixture");git(checkout,"config","user.email","fixture@example.invalid");
 git(checkout,"commit","--allow-empty","-qm","Needle-ancient-root");
 for(let index=1;index<=115;index++)git(checkout,"commit","--allow-empty","-qm",`Fixture commit ${index}`);
 git(checkout,"branch","feature-tip","HEAD~30");git(checkout,"tag","v0.1","HEAD~60");
 execFileSync("git",["init","--bare","-q","-b","main",remote]);git(checkout,"remote","add","origin",remote);git(checkout,"push","-q","-u","origin","main");
 execFileSync("git",["clone","-q",remote,publisher]);git(publisher,"config","user.name","Remote Fixture");git(publisher,"config","user.email","remote@example.invalid");git(publisher,"commit","--allow-empty","-qm","Remote-only commit");git(publisher,"push","-q","origin","main");
 const session=await create(request,"Paged history fixture",{repo_root:checkout,agent:"shell",mode:"chat"});
 const base=`${daemon}/api/sessions/${session.id}/history`;
 const first=await(await request.get(base)).json();expect(first.commits).toHaveLength(100);expect(first.next_cursor).toBe(100);expect(first.total_count).toBe(116);
 expect(first.branch_tips.some((commit:{refs:{label:string}[]})=>commit.refs.some(ref=>ref.label==="feature-tip"))).toBe(true);
 expect(first.commits.some((commit:{refs:{label:string}[]})=>commit.refs.some(ref=>ref.label==="main"))).toBe(true);
 expect((await request.get(`${base}?cursor=-1`)).status()).toBe(400);
 expect((await request.get(`${base}?limit=101`)).status()).toBe(400);
 const older=await(await request.get(`${base}?cursor=100`)).json();expect(older.commits).toHaveLength(16);expect(older.next_cursor).toBeNull();
 const search=await(await request.get(`${base}?q=Needle-ancient-root`)).json();expect(search.commits).toHaveLength(1);expect(search.commits[0].subject).toBe("Needle-ancient-root");
 const broad=await(await request.get(`${base}?q=Fixture%20commit`)).json();expect(broad.commits).toHaveLength(100);expect(broad.next_cursor).toBe(100);expect(broad.total_count).toBe(115);
 const broadOlder=await(await request.get(`${base}?q=Fixture%20commit&cursor=100`)).json();expect(broadOlder.commits).toHaveLength(15);expect(broadOlder.next_cursor).toBeNull();
 await ready(page);await open(page,"Paged history fixture");await panel(page,"History");
 await expect(page.locator(".history-row").first()).toContainText("Fixture commit 115");
 await page.locator(".history-row").first().focus();await page.keyboard.press("ArrowDown");
 await expect(page.locator(".history-row").nth(1)).toBeFocused();await page.keyboard.press("ArrowUp");
 await expect(page.locator(".history-row").first()).toBeFocused();
 expect(await page.locator(".history-row").count()).toBeLessThan(55);
 expect(await page.locator(".history-graph").count()).toBe(await page.locator(".history-row").count());
 expect(await page.locator(".history-graph path").count()).toBeGreaterThan(0);
 const expandedHeight=await page.locator(".history-table").evaluate(element=>element.scrollHeight);
 await page.locator(".history-table").evaluate(element=>element.scrollTop=30*36);
 await page.getByRole("button",{name:"Collapse feature-tip"}).click();
 await expect.poll(()=>page.locator(".history-table").evaluate(element=>element.scrollHeight)).toBeLessThan(expandedHeight);
 await page.getByRole("button",{name:/Expand feature-tip/}).click();
 await expect.poll(()=>page.locator(".history-table").evaluate(element=>element.scrollHeight)).toBe(expandedHeight);
 await page.getByRole("button",{name:"Load older"}).click();await expect(page.getByRole("button",{name:"Load older"})).toHaveCount(0);
 await expect.poll(()=>page.locator(".history-table").evaluate(element=>element.scrollHeight)).toBeGreaterThan(4000);
 await page.locator(".history-table").evaluate(element=>element.scrollTop=element.scrollHeight);
 await expect(page.locator(".history-row").last()).toContainText("Needle-ancient-root");
 await page.getByRole("button",{name:"Show branch tips"}).click();await expect(page.locator(".history-row")).toHaveCount(2);
 await page.getByRole("button",{name:"Show all commits"}).click();await expect(page.locator(".history-row").first()).toContainText("Fixture commit 115");
 await page.getByLabel("Search history").fill("Needle-ancient-root");await expect(page.locator(".history-row")).toHaveCount(1);
 await expect(page.locator(".history-row")).toContainText("Needle-ancient-root");
 await page.getByLabel("Search history").fill("Fixture commit");await expect(page.locator(".history-row").first()).toContainText("Fixture commit 115");
 await page.getByRole("button",{name:"Load older"}).click();await expect(page.getByRole("button",{name:"Load older"})).toHaveCount(0);
 await expect.poll(()=>page.locator(".history-table").evaluate(element=>element.scrollHeight)).toBeGreaterThan(4000);
 await page.locator(".history-table").evaluate(element=>element.scrollTop=element.scrollHeight);
 await expect(page.locator(".history-row").last()).toContainText("Fixture commit 1");
 await page.getByLabel("Search history").fill("");await expect(page.locator(".history-row").first()).toContainText("Fixture commit 115");
 const sha=first.commits[0].sha as string;
 await page.getByRole("button",{name:`Copy SHA ${sha.slice(0,7)}`}).click();
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(sha);
 await page.getByRole("button",{name:"Fetch all"}).click();
 await expect.poll(async()=>{const result=await(await request.get(base)).json();return result.commits.some((commit:{subject:string})=>commit.subject==="Remote-only commit");}).toBe(true);
 expect((await(await request.get(base)).json()).comparison).toEqual({base:"origin/main",ahead:0,behind:1});
 await expect(page.locator(".history-row").first()).toContainText("Remote-only commit");
});
