import { APIRequestContext, expect, Page, test as base } from "@playwright/test";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
export const tmp=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".tmp");
export const repo=path.join(tmp,"fixture-repo");export const otherRepo=path.join(tmp,"other/fixture-repo");
export const daemon="http://127.0.0.1:7455";export const token="openade-e2e-synthetic-token-2026";
export async function create(request:APIRequestContext,title:string,options:Record<string,unknown>={}){const provider=String(options.agent??"codex");if(["codex","claude","copilot","opencode","grok","devin","hermes","pi","antigravity"].includes(provider)){const meta=await(await request.get(`${daemon}/api/meta`)).json();const executable=({pi:"pi-acp",antigravity:"agy_acp_server"} as Record<string,string>)[provider]??provider;expect(meta.agents.find((agent:{id:string})=>agent.id===provider)?.path, "E2E must never run an installed provider").toBe(path.join(tmp,"bin",executable));}const response=await request.post(`${daemon}/api/sessions`,{data:{title,prompt:title,agent:"codex",mode:"chat",repo_root:repo,base_branch:"main",...options}});expect(response.status(),await response.text()).toBe(201);return response.json() as Promise<{id:string;worktree_path:string;branch:string;status:string;generation:number;current_turn_id:string}>;}
export async function open(page:Page,title:string){await page.getByRole("button",{name:new RegExp(title)}).first().click();await expect(page.locator(".session-title h1")).toHaveText(title);}
export async function ready(page:Page){await page.goto("/");await expect(page.locator(".ade")).toHaveAttribute("data-connected","true");}
export async function panel(page:Page,label:string){if(await page.getByLabel("Toggle right sidebar").getAttribute("aria-pressed")!=="true")await page.getByLabel("Toggle right sidebar").click();const tab=page.getByRole("tab",{name:label,exact:true});if(await tab.count()){await tab.click();return;}const choice=page.getByRole("button",{name:label,exact:true});if(await choice.count()){await choice.first().click();return;}await page.getByLabel("Add panel").click();await page.getByRole("menuitem",{name:label,exact:true}).click();}
export async function status(request:APIRequestContext,id:string){return (await (await request.get(`${daemon}/api/sessions/${id}`)).json()).status as string;}

export const test=base.extend({request:async({playwright},use)=>{const request=await playwright.request.newContext({extraHTTPHeaders:{Authorization:`Bearer ${token}`}});await use(request);await request.dispose();}});

export async function choose(page:Page,label:string,value:string){if(label==='Provider'){await page.getByLabel('Choose model',{exact:true}).click();await page.getByRole('tab',{name:({codex:'Codex',claude:'Claude Code',shell:'Shell',grok:'Grok'} as Record<string,string>)[value]||value,exact:true}).click();await page.keyboard.press('Escape');return;}await page.getByRole('combobox',{name:label,exact:true}).click();await page.locator(`.select-popover [role=option][data-value="${value}"]`).click();}
export async function setRepository(page:Page,value:string){await page.getByRole('combobox',{name:'Choose project',exact:true}).click();await page.getByLabel('Repository',{exact:true}).fill(value);await page.keyboard.press('Escape');}
