import {choose,setRepository} from "./helpers";
import {test,create,ready,open,panel,daemon,status,repo,tmp} from './helpers';
import {expect} from '@playwright/test';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {spawn,execFileSync} from 'node:child_process';

test('sidebar chat actions persist pinning, custom sections and archive recovery',async({page,request})=>{
 const session=await create(request,'Sidebar actions');await ready(page);const row=page.getByRole('button',{name:/Sidebar actions/}).first();await row.click({button:'right'});await page.getByRole('menuitem',{name:'Pin chat',exact:true}).click();await expect(page.locator('.custom-sidebar-section').filter({hasText:'Pinned'})).toContainText('Sidebar actions');await page.getByLabel('Project display settings').click();await page.getByRole('menuitem',{name:'Create Section',exact:true}).click();await page.getByLabel('New sidebar section').fill('Review');await page.getByRole('button',{name:'Add',exact:true}).click();await row.click({button:'right'});await page.getByRole('menuitem',{name:'Unpin chat',exact:true}).click();await row.click({button:'right'});await choose(page,"Move chat to section","Review");await expect(page.locator('.custom-sidebar-section').filter({hasText:'Review'})).toContainText('Sidebar actions');await page.reload();await expect(page.locator('.custom-sidebar-section').filter({hasText:'Review'})).toContainText('Sidebar actions');await row.click({button:'right'});await page.getByRole('menuitem',{name:'Archive chat',exact:true}).click();await expect(row).toHaveCount(0);await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Archived sessions',exact:true}).click();await page.locator('.preference-row').filter({hasText:'Sidebar actions'}).getByRole('button',{name:'Restore'}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await expect(row).toBeVisible();expect((await(await request.get(`${daemon}/api/sessions/${session.id}`)).json()).title).toBe('Sidebar actions');
});
test('favorite models, service tier and chat instructions affect real next-turn launch arguments',async({page,request})=>{
 const session=await create(request,'Catalog and instructions');await expect.poll(()=>status(request,session.id)).toBe('completed');await ready(page);await open(page,'Catalog and instructions');await page.getByLabel('Choose model').click();await expect(page.locator('.model-option-row [role=option]').first()).toHaveCSS('border-top-width','0px');await expect(page.locator('.model-option-row [role=option]>span').first()).toHaveCSS('display','flex');await page.getByLabel('Favorite Fixture Sol',{exact:true}).click();await page.getByRole('tab',{name:'Favorites',exact:true}).click();await expect(page.getByRole('option',{name:/Fixture Sol/})).toBeVisible();await page.getByRole('option',{name:/Fixture Sol/}).click();await page.getByLabel('Choose model').click();await choose(page,"Service tier","priority");await page.keyboard.press('Escape');await page.getByLabel('Session actions').click();await page.getByRole('menuitem',{name:'Chat instructions',exact:true}).click();await page.getByRole('textbox',{name:'Chat instructions',exact:true}).fill('Always report the files inspected.');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('Session message').fill('Next instructed turn');await page.getByLabel('Send message').click();await expect.poll(()=>JSON.parse(fs.readFileSync(path.join(tmp,'provider-home/args',session.id+'.json'),'utf8')).at(-1)).toContain('Conversation instructions:\nAlways report the files inspected.');const args=JSON.parse(fs.readFileSync(path.join(tmp,'provider-home/args',session.id+'.json'),'utf8'));expect(args).toContain('service_tier="priority"');await page.getByLabel('Session actions').click();await page.getByRole('menuitem',{name:'Rename chat',exact:true}).click();await page.getByLabel('Chat title').fill('Renamed conversation');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.session-title h1')).toHaveText('Renamed conversation');await page.reload();await expect(page.locator('.session-title h1')).toHaveText('Renamed conversation');
});
test('hierarchical files, syntax editor tabs, font changes and conflict handling',async({page,request})=>{
 const session=await create(request,'Editor tabs');fs.mkdirSync(path.join(session.worktree_path,'src'));fs.writeFileSync(path.join(session.worktree_path,'src/example.ts'),'const answer: number = 42;\n');await ready(page);await open(page,'Editor tabs');await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'src',exact:true}).click();await page.getByRole('treeitem',{name:'src/example.ts',exact:true}).click();await expect(page.getByLabel('Edit src/example.ts')).toContainText('const answer');await expect(page.locator('.cm-gutters')).toBeVisible();await expect(page.locator('.cm-content span').first()).toBeVisible();await page.getByRole('treeitem',{name:'README.md',exact:true}).click();await expect(page.getByRole('tab',{name:'example.ts',exact:true})).toBeVisible();await page.getByRole('tab',{name:'example.ts',exact:true}).click();await page.getByLabel('Edit src/example.ts').fill('const answer: number = 43;');fs.writeFileSync(path.join(session.worktree_path,'src/example.ts'),'const answer: number = 44;');await page.getByLabel('Save file',{exact:true}).click();await expect(page.getByRole('alert')).toContainText('changed on disk');expect(fs.readFileSync(path.join(session.worktree_path,'src/example.ts'),'utf8')).toContain('44');
});
test('latest-turn snapshots preserve staging; per-file stage and split folding work',async({page,request})=>{
 const session=await create(request,'Turn diff scopes');await expect.poll(()=>status(request,session.id)).toBe('completed');fs.writeFileSync(path.join(session.worktree_path,'README.md'),'Changed before next turn\n');execFileSync('git',['-C',session.worktree_path,'add','README.md']);await request.post(`${daemon}/api/sessions/${session.id}/messages`,{data:{text:'Capture second turn'}});await expect.poll(async()=>{const value=await(await request.get(`${daemon}/api/sessions/${session.id}`)).json();return value.generation===2&&value.status==='completed';}).toBe(true);expect(execFileSync('git',['-C',session.worktree_path,'diff','--cached','--name-only'],{encoding:'utf8'}).trim()).toBe('README.md');fs.writeFileSync(path.join(session.worktree_path,'README.md'),'Changed during latest turn\n');fs.writeFileSync(path.join(session.worktree_path,'new.txt'),'Added during latest turn\n');const latest=await(await request.get(`${daemon}/api/sessions/${session.id}/diff?scope=turn`)).json();expect(latest.diff).toContain('-Changed before next turn');expect(latest.diff).toContain('+Changed during latest turn');expect(latest.diff).toContain('new.txt');expect(execFileSync('git',['-C',session.worktree_path,'diff','--cached','--name-only'],{encoding:'utf8'}).trim()).toBe('README.md');await ready(page);await open(page,'Turn diff scopes');await panel(page,'Diffs');await choose(page,"Diff scope","turn");await expect(page.locator('.diff-document')).toHaveCount(2);await page.getByLabel('Show split diff').click();await expect(page.locator('.diff-split-line').first()).toBeVisible();await page.getByLabel('Fold all diffs').click();await expect(page.locator('.diff-lines')).toHaveCount(0);await page.getByLabel('Expand all diffs').click();await choose(page,"Diff scope","working");await page.locator('.diff-document').filter({hasText:'new.txt'}).getByRole('button',{name:'Stage',exact:true}).click();await choose(page,"Diff scope","staged");await expect(page.locator('.diff-document')).toHaveCount(2);await page.locator('.diff-document').filter({hasText:'new.txt'}).getByRole('button',{name:'Unstage',exact:true}).click();await expect(page.locator('.diff-document')).toHaveCount(1);await page.locator('.diff-document').getByRole('button',{name:'Unstage',exact:true}).click();await expect(page.getByText('No staged changes',{exact:true})).toBeVisible();await choose(page,'Diff scope','working');await page.getByLabel('Filter diffs').fill('not-a-real-fixture-file');await expect(page.getByText('No matching files',{exact:true})).toBeVisible();await expect(page.getByLabel('Next changed file')).toBeDisabled();await page.getByLabel('Filter diffs').fill('');await expect(page.locator('.diff-document')).toHaveCount(2);
});
test('composer current checkout uses the selected project without making another worktree',async({page,request})=>{
 await ready(page);await setRepository(page,repo);await choose(page,"Provider","codex");await page.getByLabel('Starting branch').click();await expect(page.getByRole('option',{name:'main',exact:true})).toBeVisible();await page.keyboard.press('Escape');await choose(page,"Checkout mode","current");await page.getByLabel('New session prompt').fill('Current checkout flow');await page.getByLabel('Start session').click();await expect(page.locator('.session-title h1')).toHaveText('Current checkout flow');const sessions=(await(await request.get(`${daemon}/api/sessions`)).json()).sessions;const session=sessions.find((s:{title:string})=>s.title==='Current checkout flow');expect(session.worktree_path).toBe(repo);expect(session.branch).toBe('main');
});
test('browser discovers the project server and supports back, forward and panel shortcuts',async({page,request})=>{
 const session=await create(request,'Local preview discovery');const server=spawn(process.execPath,['-e',`require('http').createServer((req,res)=>res.end('<h1>'+req.url+'</h1>')).listen(7475,'127.0.0.1')`],{cwd:session.worktree_path,stdio:'ignore'});try{await expect.poll(async()=>{try{return(await request.get('http://127.0.0.1:7475')).ok();}catch{return false;}}).toBe(true);await ready(page);await open(page,'Local preview discovery');await page.keyboard.press('Control+Shift+b');await expect(page.getByLabel('Website address')).toBeVisible();await page.getByLabel('Find local preview servers').click();await page.getByRole('button',{name:'7475',exact:true}).click();await expect(page.getByTitle('Workspace browser preview')).toHaveAttribute('src','http://127.0.0.1:7475/');await page.getByLabel('Website address').fill('http://127.0.0.1:7475/second');await page.getByRole('button',{name:'Go',exact:true}).click();await expect(page.getByTitle('Workspace browser preview')).toHaveAttribute('src',/second/);await page.getByLabel('Back in preview').click();await expect(page.getByTitle('Workspace browser preview')).toHaveAttribute('src','http://127.0.0.1:7475/');await page.getByLabel('Forward in preview').click();await expect(page.getByTitle('Workspace browser preview')).toHaveAttribute('src',/second/);await page.keyboard.press('Control+Shift+h');await expect(page.getByLabel('Search history')).toBeVisible();await page.keyboard.press('Control+Shift+d');await expect(page.getByLabel('Diff scope')).toBeVisible();}finally{server.kill();}
});
test('provider sign-in action opens an interactive daemon-hosted setup session',async({page,request})=>{
 await ready(page);await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Providers',exact:true}).click();const provider=page.locator('.provider-preferences').filter({has:page.getByText('Codex',{exact:true})});await provider.locator('summary').click();await provider.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('.session-title h1')).toHaveText('Sign in to codex');await expect(page.locator('.direct-tui-host')).toBeVisible();const sessions=(await(await request.get(`${daemon}/api/sessions`)).json()).sessions;const setup=sessions.find((s:{title:string})=>s.title==='Sign in to codex');expect(setup.mode).toBe('tui');expect(setup.agent).toBe('shell');await request.post(`${daemon}/api/sessions/${setup.id}/stop`);await expect.poll(()=>status(request,setup.id)).toBe('stopped');
});

test('startup failures are visible and retry starts a fresh provider conversation',async({page,request})=>{
 const session=await create(request,'fail-startup');await expect.poll(()=>status(request,session.id)).toBe('failed');await ready(page);await open(page,'fail-startup');await expect(page.locator('.activity-group > summary')).toContainText('env: node: No such file or directory');await page.getByLabel('Session message').fill('Retry startup safely');await page.getByLabel('Send message').click();await expect.poll(()=>status(request,session.id)).toBe('completed');const args=JSON.parse(fs.readFileSync(path.join(tmp,'provider-home/args',session.id+'.json'),'utf8'));expect(args).not.toContain('--last');expect(args).not.toContain('resume');expect(args.at(-1)).toBe('Retry startup safely');await expect(page.locator('.chat-assistant-turn').last()).toContainText('Retry startup safely');
});

test('custom choices support search, keyboard selection, focus return and unclipped menus',async({page})=>{
 await ready(page);await setRepository(page,repo);await expect(page.locator('select,datalist')).toHaveCount(0);await page.getByLabel('Choose project',{exact:true}).click();const pathInput=page.getByLabel('Repository',{exact:true});await pathInput.fill('');await pathInput.pressSequentially('/tmp/project with spaces');await expect(pathInput).toHaveValue('/tmp/project with spaces');await pathInput.press('Home');await pathInput.press('Tab');await expect(page.getByRole('button',{name:'Browse folders…',exact:true})).toBeFocused();await expect(page.locator('.select-popover')).toBeVisible();await pathInput.fill(repo);await page.keyboard.press('Escape');
 const branch=page.getByRole('combobox',{name:'Starting branch',exact:true});await branch.press('ArrowDown');await page.getByLabel('Search starting branch').fill('main');await expect(page.getByRole('option',{name:'main',exact:true})).toBeVisible();await page.getByLabel('Search starting branch').press('Enter');await expect(branch).toHaveAttribute('data-value','main');await expect(branch).toBeFocused();
 const checkout=page.getByRole('combobox',{name:'Checkout mode',exact:true});await checkout.press('Enter');await page.locator('.select-popover').press('End');await page.locator('.select-popover').press('Enter');await expect(checkout).toHaveAttribute('data-value','current');await expect(checkout).toBeFocused();await expect(branch).toBeDisabled();
 await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();const glass=page.getByRole('combobox',{name:'Glass',exact:true});await glass.click();const rect=await page.locator('.select-popover').boundingBox();expect(rect).not.toBeNull();expect(rect!.y).toBeGreaterThanOrEqual(8);expect(rect!.y+rect!.height).toBeLessThanOrEqual(page.viewportSize()!.height-7);await page.keyboard.press('Escape');await expect(glass).toBeFocused();await expect(page.locator('.select-popover')).toHaveCount(0);
});
test('Frosted applies through the canvas, chat, editor, terminal and popup surfaces',async({page,request})=>{
 const session=await create(request,'Material throughout workspace');await ready(page);await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await choose(page,'Glass','frosted');await expect(page.locator('.main-shell')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await page.getByRole('button',{name:'Back',exact:true}).click();await open(page,'Material throughout workspace');await expect(page.locator('.conversation')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await expect(page.locator('.session-composer')).toHaveCSS('backdrop-filter','none');expect(await page.locator('.session-composer').evaluate(el=>getComputedStyle(el,'::before').backdropFilter)).toBe('blur(16px)');await page.getByLabel('Toggle files panel').click();await expect(page.locator('.files-panel-clip')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await page.getByRole('treeitem',{name:'README.md',exact:true}).click();await expect(page.locator('.cm-editor')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await panel(page,'Diffs');await expect(page.locator('.zeron-diffs')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await panel(page,'Terminal');await page.getByLabel('New terminal',{exact:true}).click();await expect(page.locator('.terminal-workspace')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await expect(page.locator('.terminal-host').first()).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await page.locator('.terminal-workspace').getByRole('button',{name:/^Close Terminal/}).click();
});

test('skills and slash commands are discovered from the owning worktree',async({page,request})=>{
 const session=await create(request,'Worktree skill discovery');const skill=path.join(session.worktree_path,'.agents/skills/worktree-review');fs.mkdirSync(skill,{recursive:true});fs.writeFileSync(path.join(skill,'SKILL.md'),'---\nname: worktree-review\ndescription: Review this worktree only\n---\nRead local code.');await ready(page);await open(page,'Worktree skill discovery');await page.getByLabel('Session message').fill('$worktree');await page.getByRole('option',{name:/\$worktree-review/}).click();await expect(page.getByLabel('Session message')).toHaveValue('$worktree-review ');await page.getByLabel('Session message').fill('$worktree-review Read this worktree');await page.getByLabel('Send message').click();await expect.poll(()=>status(request,session.id)).toBe('completed');await expect.poll(()=>JSON.parse(fs.readFileSync(path.join(tmp,'provider-home/args',session.id+'.json'),'utf8')).at(-1)).toBe('$worktree-review Read this worktree');
});

test('a new-chat draft and its project/provider/checkout choices survive visiting settings',async({page})=>{
 await ready(page);await setRepository(page,repo);await choose(page,'Provider','codex');await choose(page,'Checkout mode','current');await page.getByLabel('New session prompt').fill('Keep this draft while adjusting appearance');await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await choose(page,'Glass','opaque');await page.getByRole('button',{name:'Back',exact:true}).click();await expect(page.getByLabel('New session prompt')).toHaveValue('Keep this draft while adjusting appearance');await expect(page.getByRole('combobox',{name:'Choose project',exact:true})).toHaveAttribute('data-value',repo);await expect(page.getByLabel('Choose model',{exact:true})).toHaveAttribute('data-provider','codex');await expect(page.getByRole('combobox',{name:'Checkout mode',exact:true})).toHaveAttribute('data-value','current');
});

test('custom font-size choices apply to the code editor and survive reload',async({page,request})=>{
 const session=await create(request,'Font appearance flow');await ready(page);await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await choose(page,'Code and diff font size','14.5');await choose(page,'Code and diff font','Menlo');await choose(page,'Terminal font size','15');await page.getByRole('button',{name:'Back',exact:true}).click();await open(page,'Font appearance flow');await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'README.md',exact:true}).click();await expect(page.locator('.cm-editor')).toHaveCSS('font-size','14.5px');await expect(page.locator('.cm-scroller')).toHaveCSS('font-family',/Menlo/);await page.reload();await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await expect(page.getByLabel('Code and diff font size')).toHaveAttribute('data-value','14.5');await expect(page.getByLabel('Terminal font size')).toHaveAttribute('data-value','15');
});

test('Liquid Glass persists and native accessibility changes restore solid surfaces without losing keyboard focus',async({page,request})=>{
 // This bridge fixture verifies client reaction; actual AppKit is checked in the native app.
 await page.addInitScript(()=>{
  Object.assign(window,{go:{main:{App:{SetAppearance:async(_scheme:string,material:string)=>material}}},runtime:{EventsOn:(_name:string,callback:(status:string)=>void)=>{Object.assign(window,{appearanceChanged:callback});return()=>{};}}});
 });
 await create(request,'Accessible glass workspace');await ready(page);
 await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();
 await choose(page,'Dark theme','gruvbox-dark');await choose(page,'Glass','default');await page.getByRole('button',{name:'System',exact:true}).click();
 await page.emulateMedia({colorScheme:'light'});await expect(page.locator('.ade')).toHaveClass(/default-frosted/);await expect(page.locator('.ade')).toHaveAttribute('data-native-material','frosted');
 await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('.ade')).toHaveClass(/default-opaque/);await expect(page.locator('.ade')).toHaveAttribute('data-native-material','opaque');
 await choose(page,'Dark theme','zeron-dark');await page.getByRole('button',{name:'Dark',exact:true}).click();
 await choose(page,'Glass','transparent');await expect(page.locator('.ade')).toHaveAttribute('data-native-material','transparent');
 await expect(page.getByText('Transparent native window — desktop visible, no native blur',{exact:true})).toBeVisible();
 await expect(page.locator('.ade')).toHaveCSS('opacity','1');
 expect(await page.locator('.ade').evaluate(el=>getComputedStyle(el).getPropertyValue('--shell-fill'))).toContain('50%');
 await expect(page.locator('html')).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await page.reload();await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();
 await expect(page.getByLabel('Glass',{exact:true})).toHaveAttribute('data-value','transparent');
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('reduced-transparency'));
 await expect(page.getByText('Solid surfaces — macOS Reduce Transparency is on',{exact:true})).toBeVisible();
 await expect(page.locator('.ade')).toHaveCSS('background-color','rgb(13, 13, 13)');
 await page.getByRole('button',{name:'Light',exact:true}).click();await expect(page.locator('.ade')).toHaveAttribute('data-native-material','transparent');
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('reduced-transparency'));
 await expect(page.locator('.ade')).toHaveCSS('text-shadow','none');
 await page.getByRole('button',{name:'Dark',exact:true}).click();
 await choose(page,'Glass','liquid');await expect(page.locator('.ade')).toHaveAttribute('data-native-material','liquid');
 await expect(page.getByText('Native macOS Liquid Glass',{exact:true})).toBeVisible();
 await expect(page.locator('.ade')).toHaveCSS('opacity','1');
 await choose(page,'Glass','default');expect(await page.locator('.ade').evaluate(el=>getComputedStyle(el).getPropertyValue('--shell-fill'))).toContain('50%');await choose(page,'Glass','liquid');
 const fill=await page.locator('.ade').evaluate(el=>getComputedStyle(el).getPropertyValue('--shell-fill'));
 expect(fill).toContain('50%');
 await page.reload();await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();
 await expect(page.getByLabel('Glass',{exact:true})).toHaveAttribute('data-value','liquid');
 await page.getByLabel('Glass',{exact:true}).focus();
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('reduced-transparency'));
 await expect(page.locator('.ade')).toHaveAttribute('data-native-material','reduced-transparency');
 await expect(page.getByText('Solid surfaces — macOS Reduce Transparency is on',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Glass',{exact:true})).toBeFocused();
 expect(await page.locator('.ade').evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(await page.locator('.ade').evaluate(el=>{const probe=document.createElement('span');probe.style.color='var(--sidebar)';el.append(probe);const color=getComputedStyle(probe).color;probe.remove();return color;}));
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('increased-contrast'));
 await expect(page.getByText('Solid surfaces — macOS Increase Contrast is on',{exact:true})).toBeVisible();
 expect(await page.locator('.ade').evaluate(el=>getComputedStyle(el).getPropertyValue('--line').trim())).toBe(await page.locator('.ade').evaluate(el=>getComputedStyle(el).getPropertyValue('--text').trim()));
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('liquid-fallback'));
 await expect(page.getByText('Frosted fallback — native Liquid Glass unavailable',{exact:true})).toBeVisible();
 await choose(page,'Glass','opaque');await expect(page.locator('.ade')).toHaveAttribute('data-native-material','opaque');
 await expect(page.locator('select,datalist')).toHaveCount(0);
 await choose(page,'Glass','liquid');await page.getByRole('button',{name:'Back',exact:true}).click();await open(page,'Accessible glass workspace');await page.getByLabel('Session message').focus();await expect(page.locator('.session-composer')).toHaveCSS('outline-width','2px');await panel(page,'Terminal');await page.getByLabel('New terminal',{exact:true}).click();
 const viewport=page.locator('.xterm-viewport').first();await expect(viewport).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await page.locator('.xterm-helper-textarea').first().focus();
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('reduced-transparency'));
 await expect(viewport).toHaveCSS('background-color','rgb(9, 9, 9)');await expect(page.locator('.xterm-helper-textarea').first()).toBeFocused();
 await page.evaluate(()=>(window as typeof window & {appearanceChanged:(status:string)=>void}).appearanceChanged('liquid'));
 await expect(viewport).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await page.locator('.terminal-workspace').getByRole('button',{name:/^Close Terminal/}).click();
});
