import { expect, Page, APIRequestContext } from '@playwright/test';
import { test, create, daemon, ready, tmp, status } from './helpers';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {execFileSync} from 'node:child_process';

// Destructive flows own unique folders, never the shared suite repository.
async function folder(request:APIRequestContext,name:string){const root=path.join(tmp,'sidebar-'+name);fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'README.md'),'owned source must survive\n');execFileSync('git',['-C',root,'init','-b','main'],{stdio:'pipe'});execFileSync('git',['-C',root,'-c','user.name=E2E','-c','user.email=e2e@example.com','add','.'],{stdio:'pipe'});execFileSync('git',['-C',root,'-c','user.name=E2E','-c','user.email=e2e@example.com','commit','-m','Owned fixture'],{stdio:'pipe'});expect((await request.post(daemon+'/api/projects',{data:{path:root}})).status()).toBe(201);return root;}
async function chat(request:APIRequestContext,root:string,title:string){const session=await create(request,title,{repo_root:root,checkout:'current',agent:'claude'});expect((await(await request.get(`${daemon}/api/sessions/${session.id}`)).json()).repo_root).toBe(root);await expect.poll(()=>status(request,session.id)).toBe('completed');return session;}
async function projectMenu(page:Page,root:string){const filter=page.getByRole('combobox',{name:'Filter projects',exact:true});if(await filter.getAttribute('aria-expanded')!=='true')await filter.click();const option=page.locator(`.select-popover [role=option][data-value="${root}"]`);await expect(option).toHaveCSS("user-select","none");await option.evaluate(el=>el.addEventListener('contextmenu',event=>{const e=event as MouseEvent;(window as any).__sidebarAnchor={x:e.clientX,y:e.clientY};},{once:true}));await option.click({button:'right'});const anchor=await page.evaluate(()=>(window as any).__sidebarAnchor as {x:number,y:number});const menu=page.getByRole('menu',{name:'Project actions',exact:true});await expect(menu).toBeVisible();expect(await menu.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBeTruthy();await expect.poll(async()=>{const b=(await menu.boundingBox())!,viewport=page.viewportSize()!;return Math.abs(b.x-Math.max(8,Math.min(anchor.x,viewport.width-b.width-8)))+Math.abs(b.y-Math.max(8,Math.min(anchor.y,viewport.height-b.height-8)));}).toBeLessThan(2);}
async function prefs(page:Page){return page.evaluate(()=>JSON.parse(localStorage.getItem('openade.preferences')||'{}'));}
async function section(page:Page,name:string){await page.getByLabel('Project display settings',{exact:true}).click();await page.getByRole('menuitem',{name:'Create Section',exact:true}).click();const dialog=page.getByRole('dialog',{name:'New section',exact:true});await expect(dialog.getByLabel('Name',{exact:true})).toBeFocused();await expect(dialog.getByPlaceholder('Section name',{exact:true})).toBeVisible();await expect(dialog.locator('..')).toHaveCSS('position','fixed');const b=(await dialog.boundingBox())!,v=page.viewportSize()!;expect(b.width).toBeCloseTo(360,0);expect(Math.abs(b.x+b.width/2-v.width/2)).toBeLessThan(2);expect(Math.abs(b.y+b.height/2-v.height/2)).toBeLessThan(2);expect(await dialog.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBeTruthy();await expect(dialog).toHaveCSS('opacity','1');await dialog.getByLabel('Name',{exact:true}).fill(name);await dialog.getByRole('button',{name:'Create section',exact:true}).click();await expect(dialog).toHaveCount(0);}
async function dragChatToProject(page:Page,row:ReturnType<Page['locator']>,target:ReturnType<Page['locator']>){
 await row.scrollIntoViewIfNeeded();
 const from=(await row.boundingBox())!,scroller=(await page.locator('.sidebar-scroll').boundingBox())!;
 await page.evaluate(()=>{(window as typeof window & {sidebarDragEvents?:string[]}).sidebarDragEvents=[];for(const name of ['dragstart','drop','dragend'])document.addEventListener(name,event=>{const list=(window as typeof window & {sidebarDragEvents?:string[]}).sidebarDragEvents!;list.push(`${name}:${(event.target as HTMLElement).className}`);},{capture:true,once:true});});
 await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();
 try{
  let reached=false;
  for(let step=0;step<150;step++){
   const to=await target.boundingBox();
   if(to&&to.y>=scroller.y+40&&to.y+to.height<=scroller.y+scroller.height-40){
    await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:18});
    const settled=(await target.boundingBox())!;
    await page.mouse.move(settled.x+settled.width/2,settled.y+settled.height/2,{steps:3});
    reached=true;break;
   }
   const below=!to||to.y+to.height>scroller.y+scroller.height-40;
   await page.mouse.move(scroller.x+scroller.width/2+(step%2?2:-2),below?scroller.y+scroller.height-10:scroller.y+10,{steps:4});
  }
  const location=await page.evaluate((selector)=>{const scroller=document.querySelector<HTMLElement>('.sidebar-scroll')!,target=document.querySelector<HTMLElement>(selector)!;const a=scroller.getBoundingClientRect(),b=target.getBoundingClientRect();return{scrollTop:scroller.scrollTop,maxScroll:scroller.scrollHeight-scroller.clientHeight,scroller:[a.top,a.bottom],target:[b.top,b.bottom],events:(window as typeof window & {sidebarDragEvents?:string[]}).sidebarDragEvents};},`.project-row[title="${(await target.getAttribute('title'))?.replaceAll('"','\\"')}"]`);
  expect(reached,`drag target should enter the scrollable sidebar: ${JSON.stringify(location)}`).toBe(true);
 }finally{await page.mouse.up();}
 const events=await page.evaluate(()=>(window as typeof window & {sidebarDragEvents?:string[]}).sidebarDragEvents||[]);
 expect(events,`drag events: ${events.join(', ')}`).toContainEqual(expect.stringMatching(/^drop:/));
}

test('project picker custom card has anchored geometry, keyboard navigation and persistent rename without changing paths',async({page,request,context})=>{
 const root=await folder(request,'rename');const session=await chat(request,root,'Rename project chat');await ready(page);const observer=await context.newPage();await ready(observer);await projectMenu(page,root);const menu=page.getByRole('menu',{name:'Project actions',exact:true});expect(await menu.evaluate(el=>Boolean(el.closest('.ade')))).toBeTruthy();const b=(await menu.boundingBox())!;expect(b.width).toBeCloseTo(170,0);expect(b.x).toBeGreaterThanOrEqual(8);expect(b.y+b.height).toBeLessThanOrEqual(920);await expect(page.getByRole('listbox',{name:'Filter projects',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(menu).toHaveCount(0);await expect(page.getByRole('listbox',{name:'Filter projects',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('listbox',{name:'Filter projects',exact:true})).toHaveCount(0);await projectMenu(page,root);await menu.getByRole('menuitem',{name:'Remove…',exact:true}).click();const cancelledRemoval=page.getByRole('dialog',{name:'Remove project',exact:true});await expect(cancelledRemoval.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(cancelledRemoval).toHaveCount(0);await expect(page.locator(`.select-popover [data-value=\"${root}\"]`)).toBeFocused();await expect(page.getByRole('listbox',{name:'Filter projects',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('listbox',{name:'Filter projects',exact:true})).toHaveCount(0);await projectMenu(page,root);
 await expect(menu.getByRole('menuitem',{name:'Rename…',exact:true})).toBeFocused();await page.keyboard.press('ArrowDown');await expect(menu.getByRole('menuitem',{name:'Remove…',exact:true})).toBeFocused();await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Rename project',exact:true});await expect(dialog.getByLabel('Name')).toBeFocused();await dialog.getByLabel('Name').fill('Source-style label');await dialog.getByRole('button',{name:'Rename',exact:true}).click();await expect(dialog).toHaveCount(0);await observer.getByLabel('Filter projects',{exact:true}).click();await expect(observer.locator(`.select-popover [data-value="${root}"]`)).toContainText('Source-style label');await observer.close();await page.reload();await page.getByLabel('Filter projects',{exact:true}).click();const option=page.locator(`.select-popover [data-value="${root}"]`);await expect(option).toContainText('Source-style label');await option.click();await page.locator(`[data-session-id="${session.id}"]`).click();await expect(page.locator('.session-title p')).toContainText('Source-style label');await expect(page.getByRole('button',{name:'Sessions',exact:true})).toHaveAttribute('aria-current','page');await page.reload();await expect(page.locator('.session-title h1')).toHaveText('Rename project chat');await expect(page.getByRole('button',{name:'Sessions',exact:true})).toHaveAttribute('aria-current','page');await page.getByLabel('Search commands and chats',{exact:true}).click();await page.getByRole('combobox',{name:'Search commands and chats',exact:true}).fill('Source-style label');await expect(page.getByRole('option',{name:/Rename project chat/})).toBeVisible();await expect(page.getByRole('option',{name:/Rename project chat/})).toContainText('Source-style label');await page.keyboard.press('Escape');expect((await(await request.get(`${daemon}/api/sessions/${session.id}`)).json()).repo_root).toBe(root);expect((await(await request.get(daemon+'/api/projects')).json()).project_names[root]).toBe('Source-style label');expect(fs.readFileSync(path.join(root,'README.md'),'utf8')).toBe('owned source must survive\n');
});

test('removal freezes archived and visible chat IDs, cancels safely, rejects stale confirmation and keeps source files',async({page,request})=>{
 const root=await folder(request,'remove');const first=await chat(request,root,'Remove visible chat');const archived=await chat(request,root,'Remove archived chat');await page.addInitScript(id=>localStorage.setItem('openade.preferences',JSON.stringify({archived_sessions:[id]})),archived.id);await ready(page);await projectMenu(page,root);await page.getByRole('menuitem',{name:'Remove…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Remove project',exact:true});await expect(dialog).toContainText('permanently removes 2 local OpenADE chats');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'Close dialog',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'Remove',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);expect((await request.get(`${daemon}/api/sessions/${first.id}`)).status()).toBe(200);
 await projectMenu(page,root);await page.getByRole('menuitem',{name:'Remove…',exact:true}).click();const late=await chat(request,root,'Created after confirmation');await expect(dialog).toContainText('permanently removes 2 local OpenADE chats');await dialog.getByRole('button',{name:'Remove',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText(/changed|reopen/i);for(const id of [first.id,archived.id,late.id])expect((await request.get(`${daemon}/api/sessions/${id}`)).status()).toBe(200);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.reload();await projectMenu(page,root);await page.getByRole('menuitem',{name:'Remove…',exact:true}).click();await expect(dialog).toContainText('permanently removes 3 local OpenADE chats');await dialog.getByRole('button',{name:'Remove',exact:true}).click();await expect(dialog).toHaveCount(0);for(const id of [first.id,archived.id,late.id])expect((await request.get(`${daemon}/api/sessions/${id}`)).status()).toBe(404);expect((await(await request.get(daemon+'/api/projects')).json()).projects).not.toContain(root);const scan=await request.post(daemon+'/api/projects/scan',{data:{root:tmp}});expect((await scan.json()).projects).not.toContain(root);expect(fs.readFileSync(path.join(root,'README.md'),'utf8')).toBe('owned source must survive\n');expect((await request.post(daemon+'/api/projects',{data:{path:root}})).status()).toBe(201);expect((await(await request.get(daemon+'/api/projects')).json()).projects).toContain(root);
});

test('chat deletion closes its real terminal while cancellation and repository files stay safe',async({page,request,context})=>{
 const root=await folder(request,'delete');const session=await chat(request,root,'Delete owned chat');const terminal=await request.post(`${daemon}/api/sessions/${session.id}/terminals`,{data:{kind:'shell',title:'Owned deletion terminal'}});expect(terminal.status(),await terminal.text()).toBe(201);await ready(page);const observer=await context.newPage();await ready(observer);await expect(observer.locator(`[data-session-id="${session.id}"]`)).toBeVisible();const row=page.locator(`[data-session-id="${session.id}"]`);await row.click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Delete chat',exact:true});await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(row).toBeVisible();await expect(row).toBeFocused();await row.click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(row).toHaveCount(0);await expect(observer.locator(`[data-session-id="${session.id}"]`)).toHaveCount(0);await observer.close();expect((await request.get(`${daemon}/api/sessions/${session.id}`)).status()).toBe(404);expect((await request.post(`${daemon}/api/sessions/${session.id}/terminals`,{data:{kind:'shell'}})).ok()).toBeFalsy();expect(fs.existsSync(session.worktree_path)).toBeTruthy();
});

test('Copy replaces the same anchored card, copies conversation identity and resets for a different chat',async({page,request})=>{
 const root=await folder(request,'copy');const first=await create(request,'Copy first chat',{repo_root:root,checkout:'worktree',agent:'claude'});await expect.poll(()=>status(request,first.id)).toBe('completed');expect(first.worktree_path).not.toBe(root);const second=await chat(request,root,'Copy second chat');await ready(page);await page.locator(`[data-session-id="${first.id}"]`).click({button:'right'});const menu=page.getByRole('menu',{name:'Chat actions',exact:true});const before=(await menu.boundingBox())!;const rename=menu.getByRole('menuitem',{name:'Rename…',exact:true});await expect(rename).toHaveCSS('appearance','none');await expect(rename).toHaveCSS('border-top-width','0px');await expect(menu.getByRole('menuitem',{name:'Pin',exact:true})).toHaveCSS('background-color','rgba(0, 0, 0, 0)');const icon=(await rename.locator('svg').boundingBox())!;expect(icon.width).toBe(16);expect(icon.x-before.x).toBeLessThan(20);const separator=(await menu.locator('hr').boundingBox())!;expect(separator.width).toBeGreaterThan(190);expect(separator.height).toBe(1);const danger=menu.getByRole('menuitem',{name:'Delete…',exact:true});expect(await danger.evaluate(el=>getComputedStyle(el).color)).not.toBe(await rename.evaluate(el=>getComputedStyle(el).color));await menu.getByRole('menuitem',{name:'Copy',exact:true}).click();await expect(menu.getByRole('menuitem',{name:'Back',exact:true})).toBeFocused();await page.keyboard.press('ArrowLeft');await expect(menu.getByRole('menuitem',{name:'Copy',exact:true})).toBeFocused();await page.keyboard.press('ArrowRight');await expect(menu.getByRole('menuitem',{name:'Back',exact:true})).toBeFocused();await expect(menu.getByRole('menuitem',{name:'Rename…',exact:true})).toHaveCount(0);const after=(await menu.boundingBox())!;expect(after.x).toBe(before.x);expect(after.y).toBe(before.y);expect(after.width).toBe(before.width);expect(after.width).toBeCloseTo(216,0);await menu.getByRole('menuitem',{name:'Path',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(first.worktree_path);await page.locator(`[data-session-id="${first.id}"]`).click({button:'right'});await menu.getByRole('menuitem',{name:'Copy',exact:true}).click();await menu.getByRole('menuitem',{name:'Harness session ID',exact:true}).click();const identity=(await(await request.get(`${daemon}/api/sessions/${first.id}`)).json()).provider_session_id;expect(identity).toBe('claude-'+first.id);expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(identity);await page.locator(`[data-session-id="${second.id}"]`).click({button:'right'});await expect(menu.getByRole('menuitem',{name:'Copy',exact:true})).toBeVisible();await expect(menu.getByRole('menuitem',{name:'Back',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.locator(`[data-session-id="${second.id}"]`)).toBeFocused();
});

test('duplicate section names have stable identity through movement, collapse, edit, reorder and deletion',async({page,request})=>{
 const root=await folder(request,'sections');const session=await chat(request,root,'Section membership chat');await ready(page);await section(page,'Inbox');await section(page,'Inbox');const initial=await prefs(page);expect(new Set(initial.sidebar_sections.map((s:{id:string})=>s.id)).size).toBe(2);const [first,second]=initial.sidebar_sections;const row=page.locator(`[data-session-id="${session.id}"]`);await row.focus();await page.keyboard.press('Alt+Shift+ArrowDown');await expect(row).toBeFocused();await expect.poll(async()=>(await prefs(page)).session_sections[session.id]).toBe(first.id);await page.keyboard.press('Alt+Shift+ArrowDown');await expect(row).toBeFocused();await expect.poll(async()=>(await prefs(page)).session_sections[session.id]).toBe(second.id);const group=page.locator('.custom-sidebar-section').filter({has:row});await expect(group).toContainText('Inbox');const collapse=group.getByRole('button',{name:'Collapse Inbox',exact:true});await collapse.focus();await page.keyboard.press('Alt+ArrowUp');await expect.poll(async()=>(await prefs(page)).sidebar_sections.map((s:{id:string})=>s.id)).toEqual([second.id,first.id]);await collapse.click();await expect(row).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'Expand Inbox',exact:true}).click();await expect(row).toBeVisible();const projectRow=page.locator(`.project-row[title="${root}"]`);if(await projectRow.count()===0)await page.getByRole('button',{name:/^Show \d+ more projects$/}).click();if(await projectRow.getAttribute('aria-expanded')!=='true')await projectRow.click();await group.getByLabel('Section actions for Inbox',{exact:true}).click();await page.getByRole('menuitem',{name:'Edit section',exact:true}).click();const edit=page.getByRole('dialog',{name:'Edit section',exact:true});await edit.getByLabel('Name').fill('Review');await edit.getByRole('button',{name:'Save',exact:true}).click();await expect(group).toContainText('Review');await expect(group.getByLabel('Section actions for Review',{exact:true})).toBeFocused();await row.click({button:'right'});await expect(page.getByRole('menu',{name:'Chat actions',exact:true})).toBeVisible();await expect(page.getByRole('menu',{name:'Section actions',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await group.getByLabel('Section actions for Review',{exact:true}).click();await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await expect(row).toBeVisible();const final=await prefs(page);expect(final.session_sections[session.id]).toBeUndefined();expect(final.sidebar_sections.map((s:{id:string})=>s.id)).toEqual([first.id]);expect((await request.get(`${daemon}/api/sessions/${session.id}`)).status()).toBe(200);
});

test('archived shelf follows the project filter, pages rows, restores across clients, and opens without restoring',async({page,request,context})=>{
 test.setTimeout(120000);
 const own=await folder(request,'archive-shelf-own'),other=await folder(request,'archive-shelf-other');
 const ids:string[]=[];
 for(let i=0;i<11;i++)ids.push((await chat(request,own,`Shelf chat ${String(i).padStart(2,'0')}`)).id);
 const outside=(await chat(request,other,'Other project archive')).id;
 await ready(page);
 const observer=await context.newPage();await ready(observer);
 await page.getByRole('combobox',{name:'Filter projects',exact:true}).click();
 await page.locator(`.select-popover [data-value="${own}"]`).click();
 const row=page.locator(`[data-session-id="${ids[10]}"]`);
 await row.click({button:'right'});
 await page.getByRole('menuitem',{name:'Archive',exact:true}).click();
 await expect(page.locator('.archived-disclosure')).toBeVisible();
 for(const id of [...ids.slice(0,10),outside])expect((await request.patch(`${daemon}/api/sessions/${id}/archive`,{data:{archived:true}})).status()).toBe(204);
 await expect(page.locator('.archived-disclosure .archived-session-row')).toHaveCount(10);
 await observer.getByRole('combobox',{name:'Filter projects',exact:true}).click();
 await observer.locator(`.select-popover [data-value="${own}"]`).click();
 await expect(observer.locator('.archived-disclosure .archived-session-row')).toHaveCount(10);
 await page.getByRole('button',{name:'Show 1 more',exact:true}).click();
 await expect(page.locator('.archived-disclosure .archived-session-row')).toHaveCount(11);
 await page.getByRole('button',{name:'Archived',exact:true}).click();
 await expect(page.getByRole('button',{name:'Archived (11)',exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('button',{name:'Archived',exact:true})).toHaveAttribute('aria-expanded','true');
 await expect(page.locator('.archived-disclosure .archived-session-row')).toHaveCount(10);
 await page.getByRole('combobox',{name:'Filter projects',exact:true}).click();
 await page.locator(`.select-popover [data-value="${other}"]`).click();
 await expect(page.locator('.archived-disclosure .archived-session-row')).toHaveCount(1);
 await page.locator(`[data-session-id="${outside}"]`).click();
 await expect(page.locator('.session-title h1')).toHaveText('Other project archive');
 expect((await(await request.get(`${daemon}/api/sessions/${outside}`)).json()).archived).toBe(true);
 await page.locator(`[data-session-id="${outside}"]`).hover();
 await page.getByRole('button',{name:'Unarchive Other project archive',exact:true}).click();
 await expect(page.locator('.archived-disclosure')).toHaveCount(0);
 await observer.getByRole('combobox',{name:'Filter projects',exact:true}).click();
 await observer.locator(`.select-popover [data-value="${other}"]`).click();
 await expect(observer.locator(`[data-session-id="${outside}"]`)).toBeVisible();
 expect((await(await request.get(`${daemon}/api/sessions/${outside}`)).json()).archived).toBe(false);
 await observer.close();
});

test('legacy local archived IDs migrate into durable daemon state and remain visible in a fresh client',async({page,request,context})=>{
 const root=await folder(request,'archive-legacy');const session=await chat(request,root,'Legacy archived chat');
 await page.addInitScript(id=>localStorage.setItem('openade.preferences',JSON.stringify({archived_sessions:[id]})),session.id);
 await ready(page);
 await expect.poll(async()=>(await(await request.get(`${daemon}/api/sessions/${session.id}`)).json()).archived).toBe(true);
 await expect.poll(async()=>(await prefs(page)).archived_sessions).toEqual([]);
 await expect(page.locator('.archived-disclosure .archived-session-row').filter({has:page.locator(`[data-session-id="${session.id}"]`)})).toBeVisible();
 const fresh=await context.newPage();await ready(fresh);
 await expect(fresh.locator('.archived-disclosure .archived-session-row').filter({has:fresh.locator(`[data-session-id="${session.id}"]`)})).toBeVisible();
 await fresh.close();
});

test('legacy duplicate labels migrate with real membership and archive-all can be restored',async({page,request})=>{
 const root=await folder(request,'legacy');const session=await chat(request,root,'Legacy section chat');await page.addInitScript(id=>localStorage.setItem('openade.preferences',JSON.stringify({sidebar_sections:['Inbox','Inbox'],session_sections:{[id]:'Inbox'}})),session.id);await ready(page);const row=page.locator(`[data-session-id="${session.id}"]`);const stored=await prefs(page);expect(stored.sidebar_sections.every((s:{id:string})=>s.id.startsWith('legacy-'))).toBeTruthy();expect(stored.session_sections[session.id]).toBe(stored.sidebar_sections[0].id);const group=page.locator('.custom-sidebar-section').filter({has:row});await group.getByLabel('Section actions for Inbox',{exact:true}).click();await page.getByRole('menuitem',{name:'Archive all',exact:true}).click();await expect(group.locator(`[data-session-id="${session.id}"]`)).toHaveCount(0);await expect(page.locator('.archived-disclosure .archived-session-row').filter({has:row})).toBeVisible();await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Archived sessions',exact:true}).click();await page.locator('.preference-row').filter({hasText:'Legacy section chat'}).getByRole('button',{name:'Restore',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await expect(row).toBeVisible();
});

test('idle persistent clients close on delete, overlapping removals roll back and concurrent starts cannot escape deletion',async({request})=>{
 test.setTimeout(90_000);
 const program=path.join(tmp,'bin/codex'),original=fs.readFileSync(program);
 fs.writeFileSync(program,'#!/usr/bin/env python3\n'+fs.readFileSync(path.join(tmp,'../codex-app-server-fixture.py'),'utf8'),{mode:0o755});fs.chmodSync(program,0o755);
 const root=await folder(request,'race');const ids:string[]=[];
 try{
  const a=await create(request,'Fence first',{repo_root:root,checkout:'current'}),b=await create(request,'Fence second',{repo_root:root,checkout:'current'});ids.push(a.id,b.id);
  for(const id of ids)await expect.poll(()=>status(request,id)).toBe('completed');
  const providerPIDs=ids.map(id=>{
   const frames=fs.readFileSync(path.join(tmp,'provider-home/rpc-log',id+'.jsonl'),'utf8').trim().split('\n').map(line=>JSON.parse(line) as {pid?:number});
   const pid=frames.find(frame=>frame.pid)?.pid;expect(pid).toBeGreaterThan(0);return pid!;
  });
  const ordered=[...ids].sort(),free=ordered[0],held=ordered[1];
  const queue=await request.post(`${daemon}/api/sessions/${held}/message-queue`,{data:{text:'hold-start-ack wait'}});expect(queue.status()).toBe(202);
  const log=path.join(tmp,'provider-home/rpc-log',held+'.jsonl');await expect.poll(()=>fs.readFileSync(log,'utf8').includes('"holdAck": true')).toBe(true);
  const deleting=request.delete(`${daemon}/api/sessions/${held}`);
  await expect.poll(async()=>{const response=await request.post(`${daemon}/api/sessions/${held}/terminals`,{data:{kind:'shell'}});return (await response.text()).includes('being removed');}).toBe(true);
  const overlap=await request.post(daemon+'/api/projects/remove',{data:{path:root,session_ids:ordered,confirm:true}});expect(overlap.status()).toBe(409);
  // A failed multi-ID removal must not leave the earlier ID permanently fenced.
  expect((await request.post(`${daemon}/api/sessions/${free}/messages`,{data:{text:'Still usable after overlap'}})).status()).toBe(202);
  await expect.poll(()=>status(request,free)).toBe('completed');expect((await deleting).status()).toBe(409);
  await request.post(`${daemon}/api/sessions/${held}/stop`);await expect.poll(()=>status(request,held),{timeout:25_000}).not.toBe('running');
  for(const id of ids)expect((await request.delete(`${daemon}/api/sessions/${id}`)).status()).toBe(204);
  for(const pid of providerPIDs)await expect.poll(()=>{try{process.kill(pid,0);return true;}catch{return false;}}).toBe(false);
  for(const id of ids){expect((await request.post(`${daemon}/api/sessions/${id}/messages`,{data:{text:'Late stale request'}})).ok()).toBeFalsy();expect((await request.post(`${daemon}/api/sessions/${id}/terminals`,{data:{kind:'shell'}})).ok()).toBeFalsy();}
  const diag=await(await request.get(daemon+'/api/diagnostics')).json();expect(diag.live_sessions).toBe(0);expect(diag.live_terminals).toBe(0);expect(diag.provider_connections).toBe(0);
  for(let i=0;i<6;i++){
   const s=await create(request,'Concurrent deletion '+i,{repo_root:root,checkout:'current'});await expect.poll(()=>status(request,s.id)).toBe('completed');
   const results=await Promise.all([request.delete(`${daemon}/api/sessions/${s.id}`),request.post(`${daemon}/api/sessions/${s.id}/messages`,{data:{text:'wait concurrent'}}),request.post(`${daemon}/api/sessions/${s.id}/terminals`,{data:{kind:'shell'}})]);
   expect(results[0].status()).toBe(204);expect((await request.get(`${daemon}/api/sessions/${s.id}`)).status()).toBe(404);
   await expect.poll(async()=>{const d=await(await request.get(daemon+'/api/diagnostics')).json();return [d.live_sessions,d.live_terminals,d.provider_connections];}).toEqual([0,0,0]);
  }
 }finally{for(const id of ids)await request.delete(`${daemon}/api/sessions/${id}`);fs.writeFileSync(program,original,{mode:0o755});fs.chmodSync(program,0o755);}
});

test('successful metadata deletion reports a transcript cleanup failure without offering a repeat deletion',async({page,request})=>{
 const root=await folder(request,'cleanup-warning');const session=await chat(request,root,'Cleanup warning chat');const transcript=path.join(tmp,'data/transcripts',session.id+'.log'),backup=transcript+'.owned-backup';fs.renameSync(transcript,backup);fs.mkdirSync(transcript);fs.writeFileSync(path.join(transcript,'owned-blocker'),'failure fixture');
 try{await ready(page);await page.locator(`[data-session-id="${session.id}"]`).click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();await page.getByRole('dialog',{name:'Delete chat',exact:true}).getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByRole('dialog',{name:'Delete chat',exact:true})).toHaveCount(0);await expect(page.getByRole('status').filter({hasText:/cleanup|transcript/i})).toBeVisible();expect((await request.get(`${daemon}/api/sessions/${session.id}`)).status()).toBe(404);expect(fs.readFileSync(path.join(root,'README.md'),'utf8')).toBe('owned source must survive\n');}finally{fs.rmSync(transcript,{recursive:true,force:true});fs.unlinkSync(backup);}
});

test('actual drag-and-drop moves chats into collapsed sections, pins and default groups under the normal sort',async({page,request})=>{
 const root=await folder(request,'drag');const session=await chat(request,root,'Drag membership chat');for(let i=0;i<80;i++){const decoy=path.join(tmp,'drag-decoys',String(i).padStart(2,'0'));fs.mkdirSync(decoy,{recursive:true});expect((await request.post(daemon+'/api/projects',{data:{path:decoy}})).status()).toBe(201);}await ready(page);await section(page,'First drag section');await section(page,'Second drag section');const row=page.locator(`[data-session-id="${session.id}"]`);
 await page.getByRole('button',{name:'Collapse Second drag section',exact:true}).click();
 await row.dragTo(page.getByRole('button',{name:'Expand Second drag section',exact:true}));
 const initial=await prefs(page),first=initial.sidebar_sections[0],second=initial.sidebar_sections[1];expect(initial.session_sections[session.id]).toBe(second.id);
 await page.getByRole('button',{name:'Expand Second drag section',exact:true}).click();await expect(row).toBeVisible();await row.dragTo(page.getByRole('button',{name:'Collapse First drag section',exact:true}));expect((await prefs(page)).session_sections[session.id]).toBe(first.id);expect((await prefs(page)).sidebar_sections.map((s:{id:string})=>s.id)).toEqual([first.id,second.id]);
 await row.click({button:'right'});await page.getByRole('menuitem',{name:'Pin',exact:true}).click();await expect(page.locator('.custom-sidebar-section').filter({hasText:'Pinned'})).toContainText('Drag membership chat');
 await row.dragTo(page.getByRole('button',{name:'Collapse Second drag section',exact:true}));expect((await prefs(page)).pinned_sessions).not.toContain(session.id);expect((await prefs(page)).session_sections[session.id]).toBe(second.id);
 const projectRow=page.locator(`.project-row[title="${root}"]`);if(await projectRow.count()===0)await page.getByRole('button',{name:/^Show \d+ more projects$/}).click();if(await projectRow.getAttribute('aria-expanded')!=='true')await projectRow.click();await dragChatToProject(page,row,projectRow);await expect.poll(async()=>(await prefs(page)).session_sections[session.id]).toBeUndefined();await expect(row).toBeVisible();
 const firstHeader=page.getByRole('button',{name:'Collapse First drag section',exact:true}),secondHeader=page.getByRole('button',{name:'Collapse Second drag section',exact:true});await firstHeader.dragTo(secondHeader);expect((await prefs(page)).sidebar_sections.map((s:{id:string})=>s.id)).toEqual([second.id,first.id]);await page.reload();expect((await prefs(page)).sidebar_sections.map((s:{id:string})=>s.id)).toEqual([second.id,first.id]);
});

test('pending deletion cannot close or submit twice; the confirmed action finishes once',async({page,request})=>{
 const root=await folder(request,'busy');const session=await chat(request,root,'Pending deletion chat');await ready(page);await page.locator(`[data-session-id="${session.id}"]`).click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Delete chat',exact:true});let calls=0,release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);
 await page.route(`**/api/sessions/${session.id}`,async route=>{if(route.request().method()!=='DELETE'){await route.continue();return;}calls++;await gate;await route.continue();});
 try{await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect.poll(()=>calls).toBe(1);for(const name of ['Cancel','Delete','Close dialog'])await expect(dialog.getByRole('button',{name,exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();expect((await request.get(`${daemon}/api/sessions/${session.id}`)).status()).toBe(200);release();await expect(dialog).toHaveCount(0);expect(calls).toBe(1);expect((await request.get(`${daemon}/api/sessions/${session.id}`)).status()).toBe(404);}finally{release();await page.unrouteAll({behavior:'wait'});}
});

test('project filtering applies to pinned and custom-section chats without destroying their memberships',async({page,request})=>{
 const aroot=await folder(request,'filter-a'),broot=await folder(request,'filter-b');const a=await chat(request,aroot,'Filtered section chat'),b=await chat(request,broot,'Filtered pinned chat');
 await page.addInitScript(({aid,bid})=>localStorage.setItem('openade.preferences',JSON.stringify({sidebar_sections:[{id:'owned-filter-section',name:'Project filter section',collapsed:false}],session_sections:{[aid]:'owned-filter-section'},pinned_sessions:[bid]})),{aid:a.id,bid:b.id});await ready(page);await expect(page.locator(`[data-session-id="${a.id}"]`)).toBeVisible();await expect(page.locator(`[data-session-id="${b.id}"]`)).toBeVisible();await page.getByLabel('Filter projects',{exact:true}).click();await page.locator(`.select-popover [data-value="${aroot}"]`).click();await expect(page.locator(`[data-session-id="${a.id}"]`)).toBeVisible();await expect(page.locator(`[data-session-id="${b.id}"]`)).toHaveCount(0);expect((await prefs(page)).pinned_sessions).toContain(b.id);expect((await prefs(page)).session_sections[a.id]).toBe('owned-filter-section');await page.getByLabel('Filter projects',{exact:true}).click();await page.locator('.select-popover [data-value=""]').click();await expect(page.locator(`[data-session-id="${b.id}"]`)).toBeVisible();
});

test('removing a scanned project prunes cached picker rows and invalidates its Home project choice while retaining the draft',async({page,request})=>{
 const root=await folder(request,'scan-root/project'),parent=path.dirname(root);const session=await chat(request,root,'Scanned removal chat');await page.addInitScript(value=>localStorage.setItem('openade.preferences',JSON.stringify({project_root:value})),parent);await ready(page);await page.getByRole('combobox',{name:'Choose project',exact:true}).click();await page.locator(`.select-popover [data-value="${root}"]`).click();await page.getByLabel('New session prompt',{exact:true}).fill('Keep this unsent prompt');await projectMenu(page,root);await page.getByRole('menuitem',{name:'Remove…',exact:true}).click();await page.getByRole('dialog',{name:'Remove project',exact:true}).getByRole('button',{name:'Remove',exact:true}).click();await expect(page.getByRole('dialog',{name:'Remove project',exact:true})).toHaveCount(0);expect((await request.get(`${daemon}/api/sessions/${session.id}`)).status()).toBe(404);await expect(page.locator(`.project-row[title="${root}"]`)).toHaveCount(0);const filter=page.getByRole('combobox',{name:'Filter projects',exact:true});if(await filter.getAttribute('aria-expanded')!=='true')await filter.click();await expect(page.locator(`.select-popover [data-value="${root}"]`)).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.getByRole('combobox',{name:'Choose project',exact:true})).toContainText('No project');await expect(page.getByLabel('New session prompt',{exact:true})).toHaveValue('Keep this unsent prompt');expect(fs.existsSync(path.join(root,'README.md'))).toBeTruthy();const unknown=await request.post(daemon+'/api/projects/remove',{data:{path:path.join(parent,'never-added'),session_ids:[],confirm:true}});expect(unknown.status()).toBe(404);expect((await request.post(daemon+'/api/projects',{data:{path:root}})).status()).toBe(201);await expect.poll(async()=>(await(await request.get(daemon+'/api/state')).json()).removed_projects).not.toContain(root);
});

test('chat and project deletion preserve dirty editor work, while an unrelated chat can still be removed',async({page,request})=>{
 const root=await folder(request,'dirty-delete'),other=await folder(request,'dirty-unrelated');const selected=await chat(request,root,'Dirty deletion guard'),unrelated=await chat(request,other,'Unrelated deletion');await ready(page);await page.locator(`[data-session-id="${selected.id}"]`).click();await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'README.md',exact:true}).click();const editor=page.getByRole('textbox',{name:'Edit README.md',exact:true});await editor.focus();await page.keyboard.press('End');await page.keyboard.insertText(' — retained unsaved deletion text');await expect(page.getByLabel('Unsaved changes')).toBeVisible();
 let deletions=0;await page.route(`**/api/sessions/${selected.id}`,async route=>{if(route.request().method()==='DELETE')deletions++;await route.continue();});await page.locator(`[data-session-id="${selected.id}"]`).click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Delete chat',exact:true});await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText(/Save or discard/i);expect(deletions).toBe(0);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(editor).toContainText('retained unsaved deletion text');
 await projectMenu(page,root);await page.getByRole('menuitem',{name:'Remove…',exact:true}).click();const removal=page.getByRole('dialog',{name:'Remove project',exact:true});await removal.getByRole('button',{name:'Remove',exact:true}).click();await expect(removal.getByRole('alert')).toContainText(/Save or discard/i);expect((await request.get(`${daemon}/api/sessions/${selected.id}`)).status()).toBe(200);await removal.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.locator(`[data-session-id="${unrelated.id}"]`).click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(editor).toContainText('retained unsaved deletion text');expect((await request.get(`${daemon}/api/sessions/${unrelated.id}`)).status()).toBe(404);await page.getByLabel('Save file',{exact:true}).click();await expect(page.getByLabel('Unsaved changes')).toHaveCount(0);expect(fs.readFileSync(path.join(root,'README.md'),'utf8')).toContain('retained unsaved deletion text');
 await page.locator(`[data-session-id="${selected.id}"]`).click({button:'right'});await page.getByRole('menuitem',{name:'Delete…',exact:true}).click();await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByLabel('New session prompt',{exact:true})).toBeVisible();expect(deletions).toBe(1);expect(fs.readFileSync(path.join(root,'README.md'),'utf8')).toContain('retained unsaved deletion text');
});

test('another client deleting a chat retains unsaved editor text and draft until recovery; clean deleted selection restores Home keyboard focus',async({page,request})=>{
 const root=await folder(request,'remote-delete');const selected=await chat(request,root,'Other client deletion');await ready(page);await page.locator(`[data-session-id="${selected.id}"]`).click();await page.getByLabel('Session message',{exact:true}).fill('Unsent deleted-chat draft');await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'README.md',exact:true}).click();const editor=page.getByRole('textbox',{name:'Edit README.md',exact:true});await editor.focus();await page.keyboard.press('End');await page.keyboard.insertText(' — recover this buffer');expect((await request.delete(`${daemon}/api/sessions/${selected.id}`)).status()).toBe(204);await expect(page.getByRole('alert').filter({hasText:/removed|deleted/i})).toBeVisible();await expect(editor).toContainText('recover this buffer');await expect(page.getByLabel('Session message',{exact:true})).toHaveValue('Unsent deleted-chat draft');
 await editor.focus();await page.keyboard.press(process.platform==='darwin'?'Meta+a':'Control+a');await page.keyboard.press(process.platform==='darwin'?'Meta+c':'Control+c');expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('recover this buffer');await page.keyboard.press(process.platform==='darwin'?'Meta+z':'Control+z');await expect(page.getByLabel('New session prompt',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>localStorage.getItem('openade.selected-session'))).toBeNull();await page.getByLabel('Search commands and chats',{exact:true}).focus();await page.keyboard.press(process.platform==='darwin'?'Meta+l':'Control+l');await expect(page.getByLabel('New session prompt',{exact:true})).toBeFocused();expect(fs.readFileSync(path.join(root,'README.md'),'utf8')).toBe('owned source must survive\n');
 const clean=await chat(request,root,'Clean other-client deletion');await page.locator(`[data-session-id="${clean.id}"]`).click();expect((await request.delete(`${daemon}/api/sessions/${clean.id}`)).status()).toBe(204);await expect(page.getByLabel('New session prompt',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>localStorage.getItem('openade.selected-session'))).toBeNull();
});
