import {expect} from "@playwright/test";
import {test,create,daemon,tmp,status,ready,open} from "./helpers";
import fs from "node:fs";
import path from "node:path";

test("forked and fresh child chats own provider history and share the checkout",async({request})=>{
  const source=await create(request,"Fork source");
  await expect.poll(()=>status(request,source.id)).toBe("completed");
  const invalid=await request.post(`${daemon}/api/sessions/${source.id}/fork`,{data:{mode:"unknown"}});
  expect(invalid.status()).toBe(400);
  const forkResponse=await request.post(`${daemon}/api/sessions/${source.id}/fork`,{data:{mode:"fork"}});
  expect(forkResponse.status(),await forkResponse.text()).toBe(201);
  const fork=await forkResponse.json();
  expect(fork.parent_session_id).toBe(source.id);
  expect(fork.fork_source_id).toBe(source.id);
  expect(fork.worktree_path).toBe(source.worktree_path);
  expect(fork.provider_session_id).toBe("");
  const prefix=fs.readFileSync(path.join(tmp,"data/transcripts",fork.id+".log"),"utf8");
  expect(prefix.match(/openade\.user_message/g)).toHaveLength(1);
  expect(prefix.match(/openade\.agent_message/g)).toHaveLength(1);
  expect(prefix).not.toContain("thread_id");
  expect(prefix).not.toContain("provider_session");
  expect((await request.post(`${daemon}/api/sessions/${fork.id}/messages`,{data:{text:"Different direction"}})).status()).toBe(202);
  await expect.poll(()=>status(request,fork.id)).toBe("completed");
  const args=JSON.parse(fs.readFileSync(path.join(tmp,"provider-home/args",fork.id+".json"),"utf8")) as string[];
  expect(args.at(-1)).toContain("Fork source");
  expect(args.at(-1)).toContain("New user message:\nDifferent direction");
  expect(args).not.toContain("resume");
  const childTranscript=fs.readFileSync(path.join(tmp,"data/transcripts",fork.id+".log"),"utf8");
  expect(childTranscript).toContain("Different direction");
  expect(fs.readFileSync(path.join(tmp,"data/transcripts",source.id+".log"),"utf8")).not.toContain("Different direction");

  const freshResponse=await request.post(`${daemon}/api/sessions/${source.id}/fork`,{data:{mode:"fresh"}});
  expect(freshResponse.status(),await freshResponse.text()).toBe(201);
  const fresh=await freshResponse.json();
  expect(fresh.parent_session_id).toBe(source.id);
  expect(fresh.fork_source_id).toBeUndefined();
  expect(fresh.worktree_path).toBe(source.worktree_path);
  expect(fs.readFileSync(path.join(tmp,"data/transcripts",fresh.id+".log"),"utf8")).toBe("");
  expect((await request.post(`${daemon}/api/sessions/${fresh.id}/messages`,{data:{text:"Brand new branch of thought"}})).status()).toBe(202);
  await expect.poll(()=>status(request,fresh.id)).toBe("completed");
  const freshArgs=JSON.parse(fs.readFileSync(path.join(tmp,"provider-home/args",fresh.id+".json"),"utf8")) as string[];
  expect(freshArgs.at(-1)).toContain("Brand new branch of thought");
  expect(freshArgs.at(-1)).not.toContain("Fork source");
  expect((await request.delete(`${daemon}/api/sessions/${source.id}`)).status()).toBe(204);
  expect((await(await request.get(`${daemon}/api/sessions/${fork.id}`)).json()).parent_session_id).toBeUndefined();
  expect((await(await request.get(`${daemon}/api/sessions/${fresh.id}`)).json()).parent_session_id).toBeUndefined();
});

test("native-shaped controls open child tabs, preserve drafts and keep transcripts separate",async({request,page})=>{
  const source=await create(request,"Side chat controls");
  await expect.poll(()=>status(request,source.id)).toBe("completed");
  await ready(page);await open(page,"Side chat controls");
  await page.getByRole("button",{name:"Toggle files panel"}).click();
  await expect(page.getByRole("region",{name:"Side chats"})).toContainText("Side chats will appear here");
  await page.locator(".session-header").getByRole("button",{name:"Fork this chat"}).click();
  const pane=page.locator(".side-chat-pane");
  await expect(pane).toBeVisible();
  await expect.poll(()=>pane.evaluate(node=>Math.round(node.getBoundingClientRect().width))).toBeGreaterThan(330);
  await expect(pane.locator(".chat-user-turn")).toContainText("Side chat controls");
  await expect(pane.getByRole("note")).toContainText("Forked from Side chat controls");
  await pane.getByRole("textbox",{name:"Side chat message"}).click();
  await page.keyboard.press("Meta+/");
  await expect(page.locator(".model-menu")).toHaveCount(1);
  await page.keyboard.press("Escape");
  await expect(page.locator(".model-menu")).toHaveCount(0);
  await page.keyboard.press("Meta+l");
  await expect(pane.getByRole("textbox",{name:"Side chat message"})).toBeFocused();
  if(process.env.OPENADE_SIDE_CHAT_CAPTURE_PATH)await page.screenshot({path:process.env.OPENADE_SIDE_CHAT_CAPTURE_PATH});
  await expect(page.getByRole("region",{name:"Side chats"}).getByRole("button",{name:"Open side chat New side chat"})).toBeVisible();
  await pane.getByRole("textbox",{name:"Side chat message"}).fill("Keep this child draft");
  await page.getByRole("button",{name:"Close Side chat tab"}).click();
  await expect(pane).toHaveCount(0);
  await page.getByRole("region",{name:"Side chats"}).getByRole("button",{name:"Open side chat New side chat"}).click();
  await expect(pane.getByRole("textbox",{name:"Side chat message"})).toHaveValue("Keep this child draft");
  await page.getByRole("button",{name:"Add panel"}).click();await page.getByRole("menuitem",{name:"Diffs"}).click();
  await page.getByRole("region",{name:"Side chats"}).getByRole("button",{name:"Open side chat New side chat"}).click();
  await expect(pane.getByRole("textbox",{name:"Side chat message"})).toHaveValue("Keep this child draft");
  await pane.getByRole("button",{name:"Send side chat message"}).click();
  const sessions=(await(await request.get(`${daemon}/api/sessions`)).json()).sessions as {id:string;parent_session_id?:string}[];
  const childID=sessions.find(item=>item.parent_session_id===source.id)!.id;
  await expect.poll(()=>status(request,childID)).toBe("completed");
  await expect(pane.locator(".chat-assistant-turn").last()).toContainText("Keep this child draft");
  await expect(page.locator(".conversation .chat-assistant-turn").last()).not.toContainText("Keep this child draft");
  await pane.getByRole("button",{name:"Fork this side chat"}).click();
  await expect.poll(async()=>((await(await request.get(`${daemon}/api/sessions`)).json()).sessions as {parent_session_id?:string}[]).filter(item=>item.parent_session_id===source.id).length).toBe(2);
  const siblingSessions=(await(await request.get(`${daemon}/api/sessions`)).json()).sessions as {id:string;parent_session_id?:string;fork_source_id?:string}[];
  expect(siblingSessions.find(item=>item.fork_source_id===childID)?.parent_session_id).toBe(source.id);
  await page.locator(".session-header").getByRole("button",{name:"New side chat"}).click();
  await expect.poll(async()=>((await(await request.get(`${daemon}/api/sessions`)).json()).sessions as {parent_session_id?:string}[]).filter(item=>item.parent_session_id===source.id).length).toBe(3);
  await expect(page.getByRole("region",{name:"Side chats"}).getByRole("button",{name:/Open side chat/})).toHaveCount(3);
});

test("fork freezes the last completed response while the parent continues working",async({request})=>{
  const source=await create(request,"Earlier completed answer");
  await expect.poll(()=>status(request,source.id)).toBe("completed");
  expect((await request.post(`${daemon}/api/sessions/${source.id}/messages`,{data:{text:"wait-provider incomplete follow-up"}})).status()).toBe(202);
  await expect.poll(()=>status(request,source.id)).toBe("running");
  const response=await request.post(`${daemon}/api/sessions/${source.id}/fork`,{data:{mode:"fork"}});
  expect(response.status(),await response.text()).toBe(201);
  const child=await response.json();
  const transcript=fs.readFileSync(path.join(tmp,"data/transcripts",child.id+".log"),"utf8");
  expect(transcript).toContain("Earlier completed answer");
  expect(transcript).not.toContain("incomplete follow-up");
  const fresh=await request.post(`${daemon}/api/sessions/${source.id}/fork`,{data:{mode:"fresh"}});
  expect(fresh.status(),await fresh.text()).toBe(201);
  await request.post(`${daemon}/api/sessions/${source.id}/stop`);
});
