import {execFileSync} from 'node:child_process';
import {test,create,ready,open,status,choose,panel} from './helpers';import {expect} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';
test('chat code fences and workspace Rust use semantic theme colors while preserving copy and undo',async({page,request})=>{
 const code='fn main() {\n    let answer = "hello"; // Comment\n    println!("{}", answer);\n}\n';const session=await create(request,'Syntax parity audit',{prompt:'Inspect this code:\n\n```rust\n'+code+'```'});await expect.poll(()=>status(request,session.id)).toBe('completed');fs.writeFileSync(path.join(session.worktree_path,'main.rs'),code);await ready(page);await open(page,'Syntax parity audit');const fence=page.locator('.markdown-code-block').filter({has:page.locator('code.language-rust')});await expect(fence.locator('.syntax-keyword').first()).toHaveText('fn');await expect(fence.locator('.syntax-string').first()).toContainText('hello');await fence.getByRole('button',{name:'Copy code',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(code.trimEnd());
 const prior=await fence.locator('.syntax-keyword').first().evaluate(node=>getComputedStyle(node).color);await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await choose(page,'Code and diff font size','14.5');await choose(page,'Code and diff font','Menlo');await choose(page,'Dark theme','gruvbox-dark');await page.getByRole('button',{name:'Back',exact:true}).click();await expect(fence.locator('pre')).toHaveCSS('font-size','14.5px');await expect(fence.locator('pre')).toHaveCSS('font-family',/Menlo/);expect(await fence.locator('.syntax-keyword').first().evaluate(node=>getComputedStyle(node).color)).not.toBe(prior);
 await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'main.rs',exact:true}).click();const editor=page.getByRole('textbox',{name:'Edit main.rs',exact:true});await expect(editor).toContainText('fn main()');expect(await editor.locator('span').count()).toBeGreaterThan(3);await editor.focus();await page.keyboard.press('End');await page.keyboard.type(' // Changed');await page.keyboard.press(process.platform==='darwin'?'Meta+z':'Control+z');await expect(page.getByLabel('Unsaved changes')).toHaveCount(0);
});


test('unified and split diffs use current theme syntax without changing file contents or staging',async({page,request})=>{
 const session=await create(request,'Diff syntax parity audit');await expect.poll(()=>status(request,session.id)).toBe('completed');const file=path.join(session.worktree_path,'main.rs');const before='fn main() {\n    let message = "before"; // Original\n}\n';const after=before.replace('"before"','"after"');fs.writeFileSync(file,before);execFileSync('git',['-C',session.worktree_path,'add','main.rs']);execFileSync('git',['-C',session.worktree_path,'commit','-m','Rust diff fixture'],{stdio:'pipe'});fs.writeFileSync(file,after);
 await ready(page);await open(page,'Diff syntax parity audit');await panel(page,'Diffs');const diff=page.locator('.diff-document').filter({has:page.locator('header strong',{hasText:'main.rs'})});await expect(diff.locator('.syntax-keyword').first()).toHaveText('fn');await expect(diff.locator('.addition .syntax-string')).toHaveText('"after"');await expect(diff.locator('.deletion .syntax-string')).toHaveText('"before"');const color=await diff.locator('.syntax-keyword').first().evaluate(node=>getComputedStyle(node).color);
 await page.getByLabel('Show split diff').click();await expect(diff).toHaveClass(/split-diff/);await expect(diff.locator('.addition .new-code .syntax-string')).toHaveText('"after"');await expect(diff.locator('.deletion .old-code .syntax-string')).toHaveText('"before"');await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await choose(page,'Dark theme','gruvbox-dark');await page.getByRole('button',{name:'Back',exact:true}).click();expect(await diff.locator('.syntax-keyword').first().evaluate(node=>getComputedStyle(node).color)).not.toBe(color);expect(fs.readFileSync(file,'utf8')).toBe(after);expect(execFileSync('git',['-C',session.worktree_path,'diff','--cached'],{encoding:'utf8'})).toBe('');
});


test('large split diffs keep plain text and sign-free cell content without parsing every row',async({page,request})=>{
 const session=await create(request,'Large diff syntax fallback');await expect.poll(()=>status(request,session.id)).toBe('completed');const file=path.join(session.worktree_path,'large.rs');const lines=Array.from({length:2101},(_,index)=>`let value_${index} = "large diff";`).join('\n')+'\n';fs.writeFileSync(file,lines);await ready(page);await open(page,'Large diff syntax fallback');await panel(page,'Diffs');const diff=page.locator('.diff-document').filter({has:page.locator('header strong',{hasText:'large.rs'})});await expect(diff).toBeVisible();await expect(diff.locator('.syntax-keyword')).toHaveCount(0);await page.getByLabel('Show split diff').click();await expect(diff.locator('.new-code').first()).toHaveText('let value_0 = "large diff";');await expect(diff.locator('.old-code').first()).toHaveText('');await page.getByLabel('Session message').fill('Composer remains available');await expect(page.getByLabel('Session message')).toHaveValue('Composer remains available');expect(fs.readFileSync(file,'utf8')).toBe(lines);
});
