import {test,create,ready,open,status,panel,choose} from './helpers';
import {expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';

test('chat web links use the embedded browser and the external-link preference survives reload',async({page,request})=>{
 const server=http.createServer((_req,res)=>res.end('<h1>Workspace link fixture</h1>'));await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const url=`http://127.0.0.1:${(server.address() as {port:number}).port}/guide`;
 try{const session=await create(request,'Web link routing parity',{prompt:`Read [Local guide](${url})`});await expect.poll(()=>status(request,session.id)).toBe('completed');await ready(page);await open(page,'Web link routing parity');await page.locator('.chat-assistant-turn').getByRole('link',{name:'Local guide',exact:true}).click();await expect(page.getByLabel('Website address')).toHaveValue(url);await expect(page.getByTitle('Workspace browser preview')).toHaveAttribute('src',url);await expect(page.frameLocator('iframe').getByRole('heading',{name:'Workspace link fixture'})).toBeVisible();
 await page.getByLabel('Open settings').click();await page.getByRole('switch',{name:'Open web links in OpenADE',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();const popup=page.waitForEvent('popup');await page.locator('.chat-assistant-turn').getByRole('link',{name:'Local guide',exact:true}).click();const external=await popup;await external.waitForLoadState();expect(external.url()).toBe(url);await external.close();await page.reload();await page.getByLabel('Open settings').click();await expect(page.getByRole('switch',{name:'Open web links in OpenADE',exact:true})).toHaveAttribute('aria-checked','false');
 }finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
});

test('diff wrap/split and configurable autosave delay persist and affect actual workspace files',async({page,request})=>{
 const session=await create(request,'Workspace preference parity');await expect.poll(()=>status(request,session.id)).toBe('completed');fs.writeFileSync(path.join(session.worktree_path,'README.md'),'# Changed\n'+'Long wrapping line '.repeat(80)+'\n');await ready(page);await open(page,'Workspace preference parity');await panel(page,'Diffs');await page.getByLabel('Wrap diff lines',{exact:true}).click();await expect(page.locator('.zeron-diffs')).toHaveClass(/wrap-diffs/);await expect.poll(()=>page.locator('.diff-lines').first().evaluate(node=>node.scrollWidth-node.clientWidth)).toBeLessThan(2);await page.getByLabel('Show split diff').click();await expect(page.locator('.split-diff')).toHaveCount(1);await page.reload();await panel(page,'Diffs');await expect(page.getByLabel('Wrap diff lines',{exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByLabel('Show unified diff')).toHaveAttribute('aria-pressed','true');
 await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Files',exact:true}).click();await expect(page.getByLabel('Autosave delay',{exact:true})).toBeDisabled();await page.getByRole('switch',{name:'Autosave',exact:true}).click();await choose(page,'Autosave delay','3000');await page.getByRole('button',{name:'Back',exact:true}).click();await page.getByLabel('Toggle files panel').click();await page.getByRole('treeitem',{name:'README.md',exact:true}).click();const editor=page.getByRole('textbox',{name:'Edit README.md',exact:true});const original=fs.readFileSync(path.join(session.worktree_path,'README.md'),'utf8');await editor.fill('# Timed autosave\n');await page.waitForTimeout(1100);expect(fs.readFileSync(path.join(session.worktree_path,'README.md'),'utf8')).toBe(original);await expect.poll(()=>fs.readFileSync(path.join(session.worktree_path,'README.md'),'utf8'),{timeout:6000}).toBe('# Timed autosave\n');await expect(page.getByLabel('Unsaved changes')).toHaveCount(0);await page.reload();await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Files',exact:true}).click();await expect(page.getByLabel('Autosave delay',{exact:true})).toHaveAttribute('data-value','3000');
});


test('last Settings section persists and unknown saved sections recover to General',async({page})=>{
 await ready(page);await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await page.reload();await page.getByLabel('Open settings').click();await expect(page.getByRole('tab',{name:'Appearance',exact:true})).toHaveAttribute('aria-selected','true');
 await page.getByRole('tab',{name:'Files',exact:true}).click();await page.reload();await page.getByLabel('Open settings').click();await expect(page.getByRole('tab',{name:'Files',exact:true})).toHaveAttribute('aria-selected','true');
 await page.evaluate(()=>{const key='openade.preferences',prefs=JSON.parse(localStorage.getItem(key)!);prefs.settings_section='Unknown section';localStorage.setItem(key,JSON.stringify(prefs));});await page.reload();await page.getByLabel('Open settings').click();await expect(page.getByRole('tab',{name:'General',exact:true})).toHaveAttribute('aria-selected','true');
});

test('session jump hints follow visible rows, exact modifiers, rebinding and popup ownership',async({page,request})=>{
 const one=await create(request,'Jump hint first'),two=await create(request,'Jump hint second');await expect.poll(()=>status(request,one.id)).toBe('completed');await expect.poll(()=>status(request,two.id)).toBe('completed');await ready(page);
 const primary=await page.evaluate(()=>/Mac|iPhone|iPad/.test(navigator.platform)?'Meta':'Control');const hints=page.locator('.session-jump-hint');const count=Math.min(9,await page.locator('.sidebar-chat-row').count());await page.keyboard.down(primary);await expect(hints).toHaveCount(count);const first=page.locator('.sidebar-chat-row').first();const firstId=await first.getAttribute('data-session-id');await page.keyboard.down('Shift');await expect(hints).toHaveCount(0);await page.keyboard.up('Shift');await expect(hints).toHaveCount(count);await page.keyboard.up(primary);await expect(hints).toHaveCount(0);
 await page.getByLabel('Project display settings').click();await page.keyboard.down(primary);await expect(hints).toHaveCount(0);await page.keyboard.up(primary);await page.keyboard.press('Escape');await page.keyboard.press(`${primary}+1`);await expect.poll(()=>page.evaluate(()=>localStorage.getItem('openade.selected-session'))).toBe(firstId);
 for(const trigger of ['Session actions','Add panel']){if(trigger==='Add panel'&&await page.getByLabel('Toggle right sidebar').getAttribute('aria-pressed')!=='true')await page.getByLabel('Toggle right sidebar').click();await page.getByLabel(trigger,{exact:true}).click();const menu=page.locator(trigger==='Session actions'?'.session-actions':'.panel-tab-menu');const firstChoice=menu.getByRole('menuitem').first();await expect(firstChoice).toBeFocused();await page.keyboard.down(primary);await expect(hints).toHaveCount(0);await page.keyboard.press('1');await page.keyboard.up(primary);await page.keyboard.press('Control+Tab');await expect(firstChoice).toBeFocused();await expect(menu).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('openade.selected-session'))).toBe(firstId);await page.keyboard.press('Escape');await expect(page.getByLabel(trigger,{exact:true})).toBeFocused();}
 await page.getByLabel('Open settings').click();await page.getByRole('tab',{name:'Shortcuts',exact:true}).click();await page.getByLabel('Change jump1 shortcut').click();await page.keyboard.press(`${primary}+Alt+1`);await expect(page.getByLabel('Change jump1 shortcut')).not.toHaveText('Press keys…');await page.getByRole('button',{name:'Back',exact:true}).click();await page.keyboard.down(primary);await expect(hints).toHaveCount(Math.min(9,await page.locator('.sidebar-chat-row:visible').count()));await page.keyboard.down('Alt');await expect(hints).toHaveCount(Math.min(9,await page.locator('.sidebar-chat-row:visible').count()));await expect(hints.first()).toContainText(/⌥|ALT/);await page.keyboard.up('Alt');await page.keyboard.up(primary);await page.reload();await page.keyboard.press(`${primary}+Alt+1`);await expect.poll(()=>page.evaluate(()=>localStorage.getItem('openade.selected-session'))).toBe(firstId);
});


test('sidebar expansion survives Settings and collapsing the last group stays collapsed',async({page,request})=>{
 const session=await create(request,'Sidebar expansion continuity');await expect.poll(()=>status(request,session.id)).toBe('completed');await ready(page);const row=page.locator(`.sidebar-chat-row[data-session-id="${session.id}"]`);await expect(row).toBeVisible();const root=await row.locator('xpath=ancestor::section[contains(@class,"project-group")]').locator('.project-row').getAttribute('title');const toggle=page.locator(`.project-row[title=${JSON.stringify(root)}]`);await toggle.click();await expect(row).toHaveCount(0);await page.getByLabel('Open settings').click();await page.getByRole('button',{name:'Back',exact:true}).click();await expect(row).toHaveCount(0);await toggle.click();await expect(row).toBeVisible();await page.getByLabel('Open settings').click();await page.getByRole('button',{name:'Back',exact:true}).click();await expect(row).toBeVisible();
});
