import {choose,setRepository} from "./helpers";
import { test } from "./helpers";
import { expect } from "@playwright/test";
import * as fs from "node:fs";
import * as path from "node:path";
import { create,daemon,open,panel,ready,repo,status,tmp } from "./helpers";
test.describe.configure({mode:"serial"});
test("centered composer, settings sections, keyboard navigation and persistent appearance",async({page})=>{
 await ready(page);await expect(page.getByLabel("New session prompt")).toBeVisible();
 await page.getByLabel("Open settings").click();
 for(const section of ["General","Appearance","Notifications","Shortcuts","Providers","Devices","Files","Archived sessions"]){await page.getByRole("tab",{name:section,exact:true}).click();await expect(page.locator(".settings-content h1")).toHaveText(section==="Shortcuts"?"Keyboard Shortcuts":section);}
 await page.getByRole("tab",{name:"Appearance",exact:true}).click();await page.getByRole("button",{name:"Dark",exact:true}).click();await choose(page,"Dark theme","dusk");await choose(page,"Glass","opaque");await expect(page.locator(".ade")).toHaveClass(/material-opaque/);await choose(page,"Glass","frosted");await expect(page.locator(".ade")).toHaveClass(/material-frosted/);await choose(page,"Interface font size","18");await page.getByLabel("Blue",{exact:true}).click();
 await page.reload();await expect(page.locator(".ade")).toHaveClass(/theme-dusk/);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Appearance",exact:true}).click();await expect(page.getByLabel("Interface font size",{exact:true})).toHaveAttribute("data-value","18");await expect(page.getByLabel("Blue",{exact:true})).toHaveAttribute("aria-pressed","true");
 await page.getByRole("button",{name:"Back",exact:true}).click();await page.keyboard.press("Control+b");await expect(page.locator(".ade")).toHaveClass(/sidebar-collapsed/);await page.reload();await expect(page.locator(".ade")).toHaveClass(/sidebar-collapsed/);await page.keyboard.press("Control+b");await expect(page.getByLabel("Open settings")).toBeVisible();
 await page.getByLabel("Project display settings").click();await choose(page,"Organize sidebar","list");await page.getByLabel("Project display settings").click();await choose(page,"Sort chats","updated");await page.reload();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("openade.preferences")!).project_organization)).toBe("list");
});
test("launch native chat through the composer and render Markdown, activities, copy and commands",async({page})=>{
 await ready(page);await setRepository(page,repo);await choose(page,"Provider","codex");await page.getByLabel("New session prompt").fill("Native launch through composer");await page.getByLabel("Start session").click();
 await expect(page.getByRole("heading",{name:"Native chat response",exact:true})).toBeVisible();await expect(page.getByText("worktree isolation",{exact:true})).toBeVisible();await expect(page.locator(".activity-group")).toBeVisible();
 await page.locator(".activity-group > summary").first().click();await expect(page.getByText("git status",{exact:false}).first()).toBeVisible();
 await page.getByRole("button",{name:"Copy",exact:true}).first().click();await expect(page.getByRole("button",{name:"Copied",exact:true}).first()).toBeVisible();
 await page.getByLabel("Session message").fill("$fix");await expect(page.getByRole("listbox",{name:"Skills and commands"})).toBeVisible();await page.getByRole("option",{name:/\$fix-ci/}).click();await expect(page.getByLabel("Session message")).toHaveValue("$fix-ci ");await page.keyboard.press("Escape");
 await page.getByLabel("Session message").fill("Follow up from native chat");await page.getByLabel("Send message").click();await expect(page.getByText("Follow up from native chat",{exact:true}).first()).toBeVisible();await expect(page.getByRole("heading",{name:"Native chat response",exact:true})).toHaveCount(2);
});
test("queue remains attached to the session and turn; edit, remove and send-next are explicit",async({page,request})=>{
 const session=await create(request,"Queue interaction",{prompt:"wait-controlled initial"});await ready(page);await open(page,"Queue interaction");
 for(const text of ["queued first","queued second","queued remove"]){await page.getByLabel("Session message").fill(text);await page.getByLabel("Send message").click();}
 await page.getByLabel("Remove queued message 3").click();await page.getByLabel("Edit queued message 2").click();await expect(page.getByLabel("Session message")).toHaveValue("queued second");await page.getByLabel("Session message").fill("queued second edited");await page.getByLabel("Send message").click();await expect(page.getByRole("region",{name:"Queued messages"}).getByText("queued second edited",{exact:true})).toBeVisible();await page.locator(".queue-item").filter({has:page.getByText("queued second edited",{exact:true})}).getByRole("button",{name:"Send next",exact:true}).click();
 await expect.poll(async()=>{const response=await request.get(`${daemon}/api/sessions/${session.id}/message-queue`);return (await response.json()).messages[0]?.text;}).toBe("queued second edited");fs.writeFileSync(path.join(session.worktree_path,".e2e-release"),"");
 await expect.poll(async()=>{const response=await request.get(`${daemon}/api/sessions/${session.id}/turns`);return (await response.json()).turns.length;}).toBe(3);
 const turns=(await (await request.get(`${daemon}/api/sessions/${session.id}/turns`)).json()).turns.reverse();expect(turns.map((turn:{prompt:string})=>turn.prompt)).toEqual(["wait-controlled initial","queued second edited","queued first"]);expect(turns[1].queue_message_id).toBeTruthy();expect(new Set(turns.map((turn:{id:string})=>turn.id)).size).toBe(3);await expect.poll(()=>status(request,session.id)).toBe("completed");
});
test("independent diff/history/browser tabs, guarded file edits, commit and draft delivery",async({page,request})=>{
 const session=await create(request,"Review and edit flow");await ready(page);await open(page,"Review and edit flow");await page.getByLabel("Toggle files panel").click();await page.getByRole("treeitem",{name:"README.md",exact:true}).click();const editor=page.getByLabel("Edit README.md");await expect(editor).toContainText("fixture");await editor.fill("# Changed by the file editor\n");await page.getByRole("button",{name:"Home",exact:true}).click();await expect(page.getByText("Save or discard file changes before leaving this session.")).toBeVisible();await page.getByLabel("Save file",{exact:true}).click();await expect(page.getByLabel("Unsaved changes")).toHaveCount(0);expect(fs.readFileSync(path.join(session.worktree_path,"README.md"),"utf8")).toContain("Changed by the file editor");
 fs.writeFileSync(path.join(session.worktree_path,"added.txt"),"new text\n");fs.unlinkSync(path.join(session.worktree_path,"remove.txt"));await panel(page,"Diffs");await expect(page.locator(".diff-document")).toHaveCount(3);await expect(page.getByText("added.txt",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Commit",exact:true}).click();await page.getByLabel("Commit message").fill("Reviewable fixture changes");await page.getByRole("button",{name:"Commit all changes",exact:true}).click();await expect(page.getByText("No uncommitted changes",{exact:true})).toBeVisible();await choose(page,"Diff scope","branch");await expect(page.locator(".diff-document")).toHaveCount(3);
 await page.getByLabel("Add panel").click();await page.getByRole("menuitem",{name:"History",exact:true}).click();await expect(page.getByText("Reviewable fixture changes",{exact:true})).toBeVisible();await page.getByLabel("Add panel").click();await page.getByRole("menuitem",{name:"Browser",exact:true}).click();await page.getByLabel("Website address").fill("http://127.0.0.1:5199");await page.getByRole("button",{name:"Go",exact:true}).click();await expect(page.getByTitle("Workspace browser preview")).toHaveAttribute("src","http://127.0.0.1:5199/");await page.getByLabel("Close Browser tab").click();
 await page.getByLabel("Add panel").click();await page.getByRole("menuitem",{name:"Pull request",exact:true}).click();await page.getByRole("button",{name:"Push branch and create draft PR",exact:true}).click();await expect(page.getByText("Draft pull request created",{exact:true})).toBeVisible();expect((await (await request.get(`${daemon}/api/sessions/${session.id}`)).json()).pr_url).toBe("https://github.com/acme/fixture/pull/8");
});
test("archive and restore without stopping agents or losing their worktree",async({page,request})=>{
 const session=await create(request,"Archive durable session");await ready(page);await open(page,"Archive durable session");await page.getByLabel("Session actions").click();await page.getByRole("menuitem",{name:"Archive session",exact:true}).click();await expect(page.getByRole("button",{name:/Archive durable session/})).toHaveCount(0);await page.getByLabel("Open settings").click();await page.getByRole("tab",{name:"Archived sessions",exact:true}).click();await page.getByRole("button",{name:"Restore",exact:true}).click();await page.getByRole("button",{name:"Back",exact:true}).click();await open(page,"Archive durable session");expect((await (await request.get(`${daemon}/api/sessions/${session.id}`)).json()).worktree_path).toBe(session.worktree_path);
});
test("project discovery and adoption keep imported conversations in their owning repository",async({page,request})=>{
 await ready(page);await page.getByLabel("Open settings").click();await page.getByLabel("Workspace folder path").fill(tmp);await page.getByRole("button",{name:"Back",exact:true}).click();const group=page.locator(".project-group").filter({has:page.locator(`.project-row[title="${repo}"]`)});const row=group.locator(".project-row");if(await row.getAttribute("aria-expanded")==="false")await row.click();const more=group.getByRole("button",{name:/Show .* more/});if(await more.count())await more.click();await page.getByRole("button",{name:/Imported Codex conversation/}).first().click();await expect(page.locator(".session-title h1")).toHaveText("Imported Codex conversation");await page.getByLabel("Session message").fill("Continue adopted conversation");await page.getByLabel("Send message").click();await expect(page.getByText("Continue adopted conversation",{exact:true}).first()).toBeVisible();
 const sessions=(await (await request.get(`${daemon}/api/sessions`)).json()).sessions;const adopted=sessions.find((s:{title:string})=>s.title==="Imported Codex conversation");expect(adopted.repo_root).toBe(repo);expect(adopted.worktree_path).not.toBe(repo);
});

test("model selection reaches the provider, persists next-turn preferences and restores the selected session",async({page,request})=>{
 await ready(page);await setRepository(page,repo);await choose(page,"Provider","codex");await page.getByLabel("Choose model").click();await page.getByRole("option",{name:/Fixture Sol/}).click();await page.getByLabel("Choose model").click();await choose(page,"Reasoning effort","high");await page.keyboard.press("Escape");await page.getByLabel("New session prompt").fill("Model selection flow");await page.getByLabel("Start session").click();await expect(page.locator(".session-title h1")).toHaveText("Model selection flow");
 const sessions=(await(await request.get(`${daemon}/api/sessions`)).json()).sessions;const session=sessions.find((s:{title:string})=>s.title==="Model selection flow");await expect.poll(()=>fs.existsSync(path.join(tmp,"provider-home/args",session.id+".json"))).toBe(true);const args=JSON.parse(fs.readFileSync(path.join(tmp,"provider-home/args",session.id+".json"),"utf8"));expect(args.slice(0,4)).toEqual(["--model","fixture-sol","-c",'model_reasoning_effort="high"']);await page.reload();await expect(page.locator(".session-title h1")).toHaveText("Model selection flow");await page.getByLabel("Choose model").click();await choose(page,"Reasoning effort","low");await page.keyboard.press("Escape");await expect.poll(async()=> (await(await request.get(`${daemon}/api/sessions/${session.id}`)).json()).effort).toBe("low");await page.getByLabel("Session message").fill("Next model turn");await page.getByLabel("Send message").click();await expect.poll(()=>JSON.parse(fs.readFileSync(path.join(tmp,"provider-home/args",session.id+".json"),"utf8"))[3]).toBe('model_reasoning_effort="low"');
});
