import {Paperclip,X,ArrowClockwise} from "@phosphor-icons/react";
import {createPortal} from "react-dom";
import {useEffect,useLayoutEffect,useRef,useState} from "react";
import type {ClipboardEvent,DragEvent,SetStateAction} from "react";
import {Attachment,attachmentMediaURL,fetchMedia,uploadAttachment} from "./api";
import "./attachments.css";

function readAttachmentDraft(key:string):Attachment[]{try{const value=JSON.parse(localStorage.getItem(`openade.attachments.${key}`)||"[]");return Array.isArray(value)?value.filter(item=>typeof item?.id==="string"&&typeof item?.path==="string"&&typeof item?.name==="string"):[];}catch{return [];}}
function saveAttachmentDraft(key:string,images:Attachment[]){if(images.length)localStorage.setItem(`openade.attachments.${key}`,JSON.stringify(images));else localStorage.removeItem(`openade.attachments.${key}`);window.dispatchEvent(new CustomEvent("openade-attachment-draft",{detail:{key,images}}));}

export function withAttachments(text:string,images:Attachment[]){return images.length?`${text.trim()||"See the attached image(s)."}\n\nAttached images (local files — open them to view):\n${images.map(image=>`- ${image.path}`).join("\n")}`:text.trim();}
export function parseAttachments(text:string){
 const marker="\n\nAttached images (local files — open them to view):\n";const at=text.lastIndexOf(marker);
 if(at<0)return{text,images:[] as Attachment[]};
 const lines=text.slice(at+marker.length).split("\n");const images:Attachment[]=[];
 for(const line of lines){const path=line.startsWith("- ")?line.slice(2):"";const match=path.match(/\/attachments\/([0-9a-f-]{36})\.(png|jpg|gif)$/);if(!match)return{text,images:[] as Attachment[]};images.push({id:match[1],path,name:`Image ${images.length+1}`,mime:`image/${match[2]}`,size:0});}
 return{text:text.slice(0,at)==="See the attached image(s)."?"":text.slice(0,at),images};
}
export function useAttachments(key:string){
 const [images,updateImages]=useState<Attachment[]>(()=>readAttachmentDraft(key));const currentImages=useRef(images);
 const [uploading,setUploading]=useState(false),[error,setError]=useState("");const alive=useRef(true),locked=useRef(false);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const setImages=(action:SetStateAction<Attachment[]>)=>{const next=typeof action==="function"?action(readAttachmentDraft(key)):action;currentImages.current=next;if(alive.current)updateImages(next);try{saveAttachmentDraft(key,next);}catch{if(alive.current)setError("Unable to save this attachment draft.");}};
 useEffect(()=>{const changed=(event:Event)=>{const detail=(event as CustomEvent<{key:string;images:Attachment[]}>).detail;if(detail.key===key&&detail.images!==currentImages.current){currentImages.current=detail.images;updateImages(detail.images);}};window.addEventListener("openade-attachment-draft",changed);return()=>window.removeEventListener("openade-attachment-draft",changed);},[key]);
 const add=async(files:File[])=>{
  if(locked.current)return;locked.current=true;setUploading(true);setError("");
  try{for(const file of files){if(file.size>24*1024*1024)throw new Error("Choose an image no larger than 24 MiB.");const image=await uploadAttachment(file);if(alive.current)setImages(current=>[...current,image]);else saveAttachmentDraft(key,[...readAttachmentDraft(key),image]);}}
  catch(reason){if(alive.current)setError(reason instanceof Error?reason.message:String(reason));}
  finally{locked.current=false;if(alive.current)setUploading(false);}
 };
 const paste=(event:ClipboardEvent)=>{const files=[...event.clipboardData.files];if(files.length){event.preventDefault();void add(files);}};
 const drop=(event:DragEvent)=>{event.preventDefault();void add([...event.dataTransfer.files]);};
 return{images,setImages,uploading,error,input,add,paste,drop,clear:()=>setImages([]),pick:()=>input.current?.click()};
}
export function AttachmentPicker({draft}:{draft:ReturnType<typeof useAttachments>}){
 return <><button type="button" className="command-trigger attachment-picker" disabled={draft.uploading} aria-label="Attach images" title="Attach images" onClick={draft.pick}><Paperclip/></button><input hidden ref={draft.input} type="file" accept="image/png,image/jpeg,image/gif" multiple aria-label="Choose image attachments" onChange={event=>{void draft.add([...event.target.files||[]]);event.target.value="";}}/></>;
}
export function AttachmentStrip({draft}:{draft:ReturnType<typeof useAttachments>}){
 return <>{draft.images.length>0&&<div className="attachment-strip" aria-label="Draft attachments">{draft.images.map((image,index)=><div key={`${image.id}-${index}`}><AttachmentImage image={image}/><button type="button" aria-label={`Remove ${image.name}`} onClick={()=>draft.setImages(current=>current.filter((_,i)=>i!==index))}><X/></button></div>)}</div>}{draft.uploading&&<div className="attachment-status" role="status">Adding images…</div>}{draft.error&&<div className="attachment-error" role="alert">{draft.error}</div>}</>;
}
export function AttachmentImage({image,sourceURL,className=""}:{image:Attachment;sourceURL?:string;className?:string}){
 const [visible,setVisible]=useState(false);const [open,setOpen]=useState(false),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0),[zoom,setZoom]=useState(false);const trigger=useRef<HTMLButtonElement>(null),close=useRef<HTMLButtonElement>(null),dialog=useRef<HTMLDivElement>(null);const focusViewport=useRef(false);
 useEffect(()=>{if(!open)return;close.current?.focus();const root=document.querySelector(".ade");root?.classList.add("has-image-overlay");return()=>root?.classList.remove("has-image-overlay");},[open]);
 useLayoutEffect(()=>{if(open&&focusViewport.current){focusViewport.current=false;(dialog.current?.querySelector<HTMLElement>('.image-viewport')||close.current)?.focus();}},[open,zoom,retry]);
 useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();event.stopImmediatePropagation();setOpen(false);setZoom(false);trigger.current?.focus();}};window.addEventListener("keydown",escape,true);return()=>window.removeEventListener("keydown",escape,true);},[open]);
 const dismiss=()=>{setOpen(false);setZoom(false);trigger.current?.focus();};
 useEffect(()=>{const node=trigger.current;if(!node)return;if(!window.IntersectionObserver){setVisible(true);return;}const observer=new IntersectionObserver(entries=>setVisible(entries.some(entry=>entry.isIntersecting)),{rootMargin:"200px"});observer.observe(node);return()=>observer.disconnect();},[]);
 const base=sourceURL||attachmentMediaURL(image.id);const resource=useImageResource(base+(retry?`${base.includes("?")?"&":"?"}retry=${retry}`:""),visible||open);const url=resource.url;
 useEffect(()=>{if(resource.error)setFailed(true);},[resource.error]);
 useEffect(()=>{setFailed(false);},[image.id,url]);
 return <><button ref={trigger} type="button" className={`attachment-thumbnail ${className}`} aria-label={`View ${image.name}`} onClick={()=>setOpen(true)}>{failed?<span>Image unavailable</span>:<img referrerPolicy="no-referrer" src={url||undefined} alt={image.name} loading="lazy" onError={()=>setFailed(true)}/>}</button>{open&&createPortal(<div ref={dialog} className="attachment-lightbox" role="dialog" aria-modal="true" aria-label={image.name} onClick={dismiss} onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();event.stopPropagation();dismiss();}if(event.key==="Tab"){const controls=[...event.currentTarget.querySelectorAll<HTMLElement>('button,[tabindex="0"]')];const first=controls[0],last=controls.at(-1);if(event.shiftKey&&event.target===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&event.target===last){event.preventDefault();first?.focus();}}}}><div className="attachment-lightbox-body" onClick={event=>event.stopPropagation()}><header><strong>{image.name}</strong><button type="button" aria-label="Retry image" onClick={()=>{focusViewport.current=true;setFailed(false);setRetry(value=>value+1);}}><ArrowClockwise/></button><button type="button" aria-label={zoom?"Fit image":"Actual image size"} onClick={()=>{focusViewport.current=true;setZoom(value=>!value);}}>{zoom?"Fit":"100%"}</button><button type="button" ref={close} aria-label="Close image" onClick={dismiss}><X/></button></header>{failed?<p role="alert">Image unavailable. Retry to load it again.</p>:<ImageViewport key={`${retry}-${zoom}`} url={url} name={image.name} actual={zoom} onFit={()=>{focusViewport.current=true;setZoom(false);}} onError={()=>setFailed(true)}/>}</div></div>,document.querySelector(".ade")||document.body)}</>;
}

// Source ImageView geometry: fit at most 100%, cursor-anchored Control/pinch
// zoom, bounded pan, and a four-pixel drag threshold. Only this viewport updates.
export function ImageViewport({url,name,actual=false,onError,onFit}:{url:string;name:string;actual?:boolean;onError?:()=>void;onFit?:()=>void}) {
 const host=useRef<HTMLDivElement>(null),picture=useRef<HTMLImageElement>(null);const [,draw]=useState(0);
 const geometry=useRef({width:1,height:1,vw:1,vh:1,scale:1,x:0,y:0,fitted:!actual});const drag=useRef<{x:number;y:number;panX:number;panY:number}|null>(null);
 const fit=()=>Math.min(geometry.current.vw/geometry.current.width,geometry.current.vh/geometry.current.height,1);
 const clamp=()=>{const g=geometry.current;const lx=Math.max(0,(g.width*g.scale-g.vw)/2),ly=Math.max(0,(g.height*g.scale-g.vh)/2);g.x=Math.max(-lx,Math.min(lx,g.x));g.y=Math.max(-ly,Math.min(ly,g.y));};
 const measure=()=>{const node=host.current,img=picture.current;if(!node||!img||!img.naturalWidth)return;const g=geometry.current;g.width=img.naturalWidth;g.height=img.naturalHeight;g.vw=node.clientWidth;g.vh=node.clientHeight;if(g.fitted){g.scale=fit();g.x=0;g.y=0;}clamp();draw(value=>value+1);};
 useEffect(()=>{const node=host.current;if(!node)return;const observer=new ResizeObserver(measure);observer.observe(node);const wheel=(event:WheelEvent)=>{const g=geometry.current;if(event.ctrlKey){event.preventDefault();event.stopPropagation();const rect=node.getBoundingClientRect(),anchorX=event.clientX-rect.left-g.vw/2,anchorY=event.clientY-rect.top-g.vh/2;const maximum=Math.max(fit(),Math.min(32,131072/Math.max(g.width,g.height)));const next=Math.max(Math.min(fit(),.01),Math.min(maximum,g.scale*Math.exp(Math.max(-2,Math.min(2,-event.deltaY*(event.deltaMode===1?40:1)*.0025)))));const ratio=next/g.scale;g.x=anchorX-(anchorX-g.x)*ratio;g.y=anchorY-(anchorY-g.y)*ratio;g.scale=next;g.fitted=false;clamp();draw(value=>value+1);}else{const oldX=g.x,oldY=g.y;g.x-=event.deltaX;g.y-=event.deltaY;clamp();if(g.x!==oldX||g.y!==oldY){event.preventDefault();event.stopPropagation();draw(value=>value+1);}}};node.addEventListener("wheel",wheel,{passive:false});measure();return()=>{observer.disconnect();node.removeEventListener("wheel",wheel);};},[url]);
 const g=geometry.current;return <div className="image-viewport" ref={host} tabIndex={0} role="region" aria-label={`${name} image viewport`} data-scale={g.scale.toFixed(3)} onDoubleClick={()=>{g.fitted=true;measure();onFit?.();}} onPointerDown={event=>{if(event.button!==0)return;event.currentTarget.focus();event.currentTarget.setPointerCapture(event.pointerId);drag.current={x:event.clientX,y:event.clientY,panX:g.x,panY:g.y};}} onPointerMove={event=>{const start=drag.current;if(!start||Math.hypot(event.clientX-start.x,event.clientY-start.y)<4)return;g.x=start.panX+event.clientX-start.x;g.y=start.panY+event.clientY-start.y;clamp();draw(value=>value+1);}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={event=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key)){event.preventDefault();g.x+=event.key==="ArrowLeft"?40:event.key==="ArrowRight"?-40:0;g.y+=event.key==="ArrowUp"?40:event.key==="ArrowDown"?-40:0;clamp();draw(value=>value+1);}else if(event.key==="0"){event.preventDefault();g.fitted=true;measure();onFit?.();}}}><img referrerPolicy="no-referrer" ref={picture} src={url||undefined} alt={name} draggable={false} onLoad={measure} onError={onError} style={{width:g.width*g.scale,height:g.height*g.scale,left:(g.vw-g.width*g.scale)/2+g.x,top:(g.vh-g.height*g.scale)/2+g.y}}/></div>;
}
export function WorkspaceImage({url,name}:{url:string;name:string}){const host=useRef<HTMLDivElement>(null),focusViewport=useRef(false);const [failed,setFailed]=useState(false),[retry,setRetry]=useState(0),[actual,setActual]=useState(false);const resource=useImageResource(url+`&retry=${retry}`);useEffect(()=>{if(resource.error)setFailed(true);},[resource.error]);useLayoutEffect(()=>{if(focusViewport.current){focusViewport.current=false;host.current?.querySelector<HTMLElement>('.image-viewport')?.focus();}},[actual,retry]);return <div ref={host} className="workspace-image"><div className="image-toolbar"><span>{name}</span><button aria-label="Retry image" onClick={()=>{focusViewport.current=true;setFailed(false);setRetry(value=>value+1);}}>Retry</button><button aria-label={actual?"Fit image":"Actual image size"} onClick={()=>{focusViewport.current=true;setActual(value=>!value);}}>{actual?"Fit":"100%"}</button></div>{failed?<p role="alert">Image unavailable. Retry to load it again.</p>:<ImageViewport key={`${retry}-${actual}`} url={resource.url} name={name} actual={actual} onFit={()=>{focusViewport.current=true;setActual(false);}} onError={()=>setFailed(true)}/>}</div>;}

interface ImageResource{refs:number;controller:AbortController;promise:Promise<string>;url?:string}
const imageResources=new Map<string,ImageResource>();
function useImageResource(source:string,enabled=true){const privateMedia=/^\/api\/(?:attachments\/[^/]+\/media|sessions\/[^/]+\/file-media)(?:\?|$)/.test(source);const [state,setState]=useState({source,url:privateMedia?"":source,error:false});useEffect(()=>{if(privateMedia&&!enabled){setState({source,url:"",error:false});return;}if(!privateMedia){setState({source,url:source,error:false});return;}let active=true;setState({source,url:"",error:false});let resource=imageResources.get(source);if(!resource){const controller=new AbortController();const entry:ImageResource={refs:0,controller,promise:Promise.resolve("")};entry.promise=fetchMedia(source,controller.signal).then(blob=>{if(!entry.refs)throw Error("Image request cancelled.");entry.url=URL.createObjectURL(blob);return entry.url;});resource=entry;imageResources.set(source,entry);}resource.refs++;const owned=resource;void owned.promise.then(url=>{if(active)setState({source,url,error:false});}).catch(()=>{if(active)setState({source,url:"",error:true});});return()=>{active=false;if(--owned.refs===0){owned.controller.abort();if(owned.url)URL.revokeObjectURL(owned.url);imageResources.delete(source);}};},[source,privateMedia,enabled]);return state.source===source&&(!privateMedia||enabled)?state:{source,url:"",error:false};}
