import {Language,StreamLanguage} from '@codemirror/language';
import {javascript} from '@codemirror/lang-javascript';import {json} from '@codemirror/lang-json';import {css} from '@codemirror/lang-css';import {html} from '@codemirror/lang-html';import {python} from '@codemirror/lang-python';import {markdown} from '@codemirror/lang-markdown';
import {go} from '@codemirror/legacy-modes/mode/go';import {rust} from '@codemirror/legacy-modes/mode/rust';import {swift} from '@codemirror/legacy-modes/mode/swift';import {shell} from '@codemirror/legacy-modes/mode/shell';import {yaml} from '@codemirror/legacy-modes/mode/yaml';import {toml} from '@codemirror/legacy-modes/mode/toml';import {standardSQL} from '@codemirror/legacy-modes/mode/sql';import {ruby} from '@codemirror/legacy-modes/mode/ruby';import {c,cpp,java,csharp,kotlin,scala,dart,objectiveC} from '@codemirror/legacy-modes/mode/clike';
import {highlightTree,tagHighlighter,tags} from '@lezer/highlight';
const modes:Record<string,Language>={go:StreamLanguage.define(go),rs:StreamLanguage.define(rust),rust:StreamLanguage.define(rust),swift:StreamLanguage.define(swift),sh:StreamLanguage.define(shell),bash:StreamLanguage.define(shell),zsh:StreamLanguage.define(shell),yaml:StreamLanguage.define(yaml),yml:StreamLanguage.define(yaml),toml:StreamLanguage.define(toml),sql:StreamLanguage.define(standardSQL),rb:StreamLanguage.define(ruby),ruby:StreamLanguage.define(ruby),c:StreamLanguage.define(c),h:StreamLanguage.define(c),cpp:StreamLanguage.define(cpp),cc:StreamLanguage.define(cpp),hpp:StreamLanguage.define(cpp),java:StreamLanguage.define(java),cs:StreamLanguage.define(csharp),csharp:StreamLanguage.define(csharp),kt:StreamLanguage.define(kotlin),kotlin:StreamLanguage.define(kotlin),scala:StreamLanguage.define(scala),dart:StreamLanguage.define(dart),m:StreamLanguage.define(objectiveC)};
const aliases:Record<string,string>={javascript:'js',typescript:'ts',python:'py',md:'markdown',htm:'html',cxx:'cpp',cplus:'cpp',objectivec:'m','objective-c':'m'};
const parsed=new Map<string,Language>();
export function codeLanguage(value:string):Language|undefined {let language=value.toLowerCase().replace(/^language-/, '');language=aliases[language]||language;if(modes[language])return modes[language];if(parsed.has(language))return parsed.get(language);let result:Language|undefined;if(['js','ts','tsx','jsx'].includes(language))result=javascript({typescript:language==='ts'||language==='tsx',jsx:language==='tsx'||language==='jsx'}).language;else if(language==='json'||language==='jsonc')result=json().language;else if(language==='html')result=html().language;else if(language==='css')result=css().language;else if(language==='py')result=python().language;else if(language==='markdown')result=markdown().language;if(result)parsed.set(language,result);return result;}
const highlighter=tagHighlighter([{tag:tags.keyword,class:'syntax-keyword'},{tag:[tags.string,tags.regexp],class:'syntax-string'},{tag:[tags.number,tags.bool,tags.null],class:'syntax-number'},{tag:[tags.typeName,tags.className],class:'syntax-type'},{tag:tags.variableName,class:'syntax-variable'},{tag:tags.propertyName,class:'syntax-property'},{tag:tags.punctuation,class:'syntax-punctuation'},{tag:tags.tagName,class:'syntax-tag'},{tag:tags.attributeName,class:'syntax-attribute'},{tag:tags.invalid,class:'syntax-invalid'},{tag:tags.comment,class:'syntax-comment'},{tag:tags.function(tags.variableName),class:'syntax-function'}]);
export interface CodeSpan{from:number;to:number;className:string}
const cache=new Map<string,CodeSpan[]>();
export function highlightCode(text:string,language:string):CodeSpan[]{if(text.length>100_000)return [];const key=language+'\0'+text;const hit=cache.get(key);if(hit)return hit;const parser=codeLanguage(language)?.parser;if(!parser)return [];const spans:CodeSpan[]=[];highlightTree(parser.parse(text),highlighter,(from,to,className)=>{if(spans.length<20_000)spans.push({from,to,className});});cache.set(key,spans);if(cache.size>32)cache.delete(cache.keys().next().value!);return spans;}
