import {HighlightStyle,syntaxHighlighting} from "@codemirror/language";
import {tags} from "@lezer/highlight";
import {createPortal} from "react-dom";
import {ReviewComment,ReviewCommentCard,ReviewCommentDraft} from "./ReviewComments";
import {Dispatch,SetStateAction} from "react";
import {copyText,readText} from "./clipboard";
import {markCustomMenu,menuKeys} from "./menuKeys";
import {useEffect,useRef,useState} from "react";
import {basicSetup} from "codemirror";
import {EditorView,gutter,GutterMarker} from "@codemirror/view";
import {EditorState,Compartment} from "@codemirror/state";
import {codeLanguage} from "./codeSyntax";
function language(path:string){return codeLanguage(path.split(".").at(-1)||"")||[];}
class CommentGutterMarker extends GutterMarker {
 constructor(readonly line:number,readonly open:(line:number)=>void){super();}
 eq(other:GutterMarker){return other instanceof CommentGutterMarker&&other.line===this.line;}
 toDOM(){const button=document.createElement("button");button.type="button";button.className="cm-add-comment";button.setAttribute("aria-label",`Add or view comment on line ${this.line}`);button.textContent="+";button.addEventListener("mousedown",event=>event.preventDefault());button.addEventListener("click",event=>{event.stopPropagation();this.open(this.line);});return button;}
}
export default function CodeEditor({path,value,onChange,wrap,disabled,comments=[],onComments}:{path:string;value:string;onChange:(value:string)=>void;wrap:boolean;disabled:boolean;comments?:ReviewComment[];onComments?:Dispatch<SetStateAction<ReviewComment[]>>}){
 const [context,setContext]=useState<{x:number;y:number;from:number;to:number;document:string;paste:boolean}|null>(null);const [menuError,setMenuError]=useState("");const contextEpoch=useRef(0);const popup=useRef<HTMLDivElement>(null);
 const openContext=(event:MouseEvent,editor:EditorView)=>{event.preventDefault();const range=editor.state.selection.main;const epoch=++contextEpoch.current;setMenuError("");setContext({x:Math.max(8,Math.min(event.clientX,window.innerWidth-178)),y:Math.max(8,Math.min(event.clientY,window.innerHeight-158)),from:range.from,to:range.to,document:editor.state.doc.toString(),paste:false});void readText().then(text=>{if(contextEpoch.current===epoch)setContext(current=>current?{...current,paste:Boolean(text)}:null);}).catch(()=>{});return true;};
 const closeContext=()=>{contextEpoch.current++;setContext(null);};
 useEffect(()=>{if(!context)return;const release=markCustomMenu(host.current);popup.current?.querySelector<HTMLButtonElement>("button:not(:disabled)")?.focus();const outside=(event:PointerEvent)=>{if(!popup.current?.contains(event.target as Node))closeContext();};document.addEventListener("pointerdown",outside);window.addEventListener("openade-dismiss-menus",closeContext);return()=>{release();document.removeEventListener("pointerdown",outside);window.removeEventListener("openade-dismiss-menus",closeContext);};},[Boolean(context)]);
 const contextAction=async(action:"Cut"|"Copy"|"Paste"|"Select All")=>{const editor=view.current,selection=context;if(!editor||!selection)return;closeContext();editor.focus();try{if(action==="Select All"){editor.dispatch({selection:{anchor:0,head:editor.state.doc.length}});return;}if(action==="Copy"||action==="Cut")await copyText(selection.document.slice(selection.from,selection.to));const text=action==="Paste"?await readText():"";if(action==="Copy")return;if(disabled||view.current!==editor||editor.state.doc.toString()!==selection.document)throw Error("The document changed; select the text again before editing.");if(action==="Paste"&&!text)return;if(new TextEncoder().encode(selection.document.length?selection.document.slice(0,selection.from)+text+selection.document.slice(selection.to):text).length>2*1024*1024)throw Error("Text files are limited to 2 MiB.");editor.dispatch({changes:{from:selection.from,to:selection.to,insert:text},selection:{anchor:selection.from+text.length},userEvent:action==="Cut"?"delete.cut":"input.paste"});editor.focus();}catch(reason){setMenuError(reason instanceof Error?reason.message:"Clipboard operation failed.");}};
 const host=useRef<HTMLDivElement>(null),editorMount=useRef<HTMLDivElement>(null);const view=useRef<EditorView|null>(null);const callback=useRef(onChange);callback.current=onChange;const config=useRef(new Compartment());
 const [commentLine,setCommentLine]=useState<number|null>(null),[commentTop,setCommentTop]=useState(8),[draft,setDraft]=useState<{value:string;editing?:string}|null>(null);
 const commentsRef=useRef(comments),onCommentsRef=useRef(onComments),commentLineRef=useRef(commentLine),suppressAnchorMap=useRef(false);
 commentsRef.current=comments;onCommentsRef.current=onComments;commentLineRef.current=commentLine;
 const openLineRef=useRef<(line:number)=>void>(()=>{});
 const measureComment=()=>{const editor=view.current,node=host.current;if(!editor||!node||commentLine===null)return;const line=editor.state.doc.line(Math.min(commentLine,editor.state.doc.lines));const coords=editor.coordsAtPos(line.from);if(!coords)return;const bounds=node.getBoundingClientRect();setCommentTop(Math.max(8,Math.min(bounds.height-205,coords.top-bounds.top+20)));};
 openLineRef.current=(line:number)=>{if(!onComments)return;setCommentLine(line);setDraft({value:""});};
 useEffect(()=>{if(commentLine===null)return;measureComment();const editor=view.current,node=host.current;if(!editor||!node)return;const scroll=()=>measureComment();editor.scrollDOM.addEventListener("scroll",scroll);const observer=new ResizeObserver(scroll);observer.observe(node);return()=>{editor.scrollDOM.removeEventListener("scroll",scroll);observer.disconnect();};},[commentLine,path]);
 useEffect(()=>{setCommentLine(null);setDraft(null);},[path]);
 const saveComment=()=>{if(!draft?.value.trim()||commentLine===null||!onComments)return;const body=draft.value.trim();onComments(current=>draft.editing?current.map(comment=>comment.id===draft.editing?{...comment,body}:comment):[...current,{id:crypto.randomUUID(),path,line:commentLine,body,source:"file"}]);setDraft(null);};
 useEffect(()=>{if(!editorMount.current)return;const editor=new EditorView({parent:editorMount.current,state:EditorState.create({doc:value,extensions:[basicSetup,gutter({class:"cm-comment-gutter",lineMarker:(editor,line)=>new CommentGutterMarker(editor.state.doc.lineAt(line.from).number,number=>openLineRef.current(number))}),EditorView.domEventHandlers({contextmenu:openContext}),syntaxHighlighting(HighlightStyle.define([{tag:tags.keyword,color:"var(--syntax-keyword)"},{tag:[tags.string,tags.regexp],color:"var(--syntax-string)"},{tag:[tags.number,tags.bool,tags.null],color:"var(--syntax-number)"},{tag:[tags.typeName,tags.className],color:"var(--syntax-type)"},{tag:tags.variableName,color:"var(--syntax-variable)"},{tag:tags.propertyName,color:"var(--syntax-property)"},{tag:tags.punctuation,color:"var(--syntax-punctuation)"},{tag:tags.tagName,color:"var(--syntax-tag)"},{tag:tags.attributeName,color:"var(--syntax-attribute)"},{tag:tags.invalid,color:"var(--syntax-invalid)"},{tag:tags.comment,color:"var(--syntax-comment)",fontStyle:"italic"},{tag:tags.function(tags.variableName),color:"var(--syntax-function)"}])),language(path),config.current.of([EditorView.editable.of(!disabled),...(wrap?[EditorView.lineWrapping]:[])]),EditorView.contentAttributes.of({'aria-label':`Edit ${path}`,'role':'textbox','aria-multiline':'true'}),EditorView.updateListener.of(update=>{
   if(!update.docChanged)return;
   callback.current(update.state.doc.toString());
   if(suppressAnchorMap.current)return;
   const mapped=new Map<string,number>();
   for(const comment of commentsRef.current){if(comment.source!=="file"||comment.path!==path)continue;const oldLine=update.startState.doc.line(Math.min(comment.line,update.startState.doc.lines));const position=update.changes.mapPos(oldLine.from,1);const line=update.state.doc.lineAt(position).number;if(line!==comment.line)mapped.set(comment.id,line);}
   if(mapped.size){const next=commentsRef.current.map(comment=>mapped.has(comment.id)?{...comment,line:mapped.get(comment.id)!}:comment);commentsRef.current=next;onCommentsRef.current?.(next);}
   if(commentLineRef.current!==null){const oldLine=update.startState.doc.line(Math.min(commentLineRef.current,update.startState.doc.lines));const line=update.state.doc.lineAt(update.changes.mapPos(oldLine.from,1)).number;if(line!==commentLineRef.current){commentLineRef.current=line;setCommentLine(line);}}
  }),EditorView.theme({'&':{height:'100%',fontSize:'var(--code-size)',color:'var(--text)',backgroundColor:'transparent'},'.cm-scroller':{fontFamily:'var(--code-font)',overflow:'auto'},'.cm-gutters':{backgroundColor:'transparent',color:'var(--faint)',borderRight:'1px solid var(--line)'},'.cm-activeLine,.cm-activeLineGutter':{backgroundColor:'color-mix(in srgb,var(--accent) 6%,transparent)'},'.cm-cursor':{borderLeftColor:'var(--text)'},'.cm-selectionBackground':{backgroundColor:'color-mix(in srgb,var(--accent) 25%,transparent) !important'},'.cm-content':{padding:'8px 0'}})]})});view.current=editor;editor.dom.querySelector(".cm-gutters")?.setAttribute("aria-hidden","false");return()=>{editor.destroy();view.current=null;};},[path]);
 useEffect(()=>{const editor=view.current;if(editor&&editor.state.doc.toString()!==value){suppressAnchorMap.current=true;try{editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:value}});}finally{suppressAnchorMap.current=false;}}},[value]);
 useEffect(()=>{view.current?.dispatch({effects:config.current.reconfigure([EditorView.editable.of(!disabled),...(wrap?[EditorView.lineWrapping]:[])])});},[wrap,disabled]);
 const lineComments=comments.filter(comment=>comment.source==="file"&&comment.path===path&&comment.line===commentLine);
 return <><div className="code-editor-host" ref={host}><div className="code-editor-mount" ref={editorMount}/>{commentLine!==null&&<div className="file-comment-popover" style={{top:commentTop}}><header><span>{path}:{commentLine}</span><button aria-label="Close file comments" onClick={()=>{setCommentLine(null);setDraft(null);view.current?.focus();}}>×</button></header>{lineComments.filter(comment=>comment.id!==draft?.editing).map(comment=><ReviewCommentCard key={comment.id} comment={comment} hideLocation onEdit={()=>setDraft({value:comment.body,editing:comment.id})} onRemove={()=>onComments?.(current=>current.filter(item=>item.id!==comment.id))}/>)}{draft&&<ReviewCommentDraft path={path} line={commentLine} value={draft.value} hideLocation onChange={value=>setDraft(current=>current?{...current,value}:null)} onSave={saveComment} onCancel={()=>{setDraft(null);if(!lineComments.length)setCommentLine(null);}}/>}{!draft&&<button className="file-comment-add" onClick={()=>setDraft({value:""})}>Add another comment</button>}</div>}</div>{menuError&&<p className="inline-error" role="alert">{menuError}</p>}{context&&createPortal(<div ref={popup} className="editor-context-menu select-popover" role="menu" aria-label="Editor actions" style={{position:"fixed",left:context.x,top:context.y,width:170}} onKeyDown={event=>menuKeys(event,closeContext,()=>view.current?.focus())}>{(["Cut","Copy","Paste","Select All"] as const).map(action=><button type="button" role="menuitem" key={action} disabled={action==="Cut"?disabled||context.from===context.to:action==="Copy"?context.from===context.to:action==="Paste"?disabled||!context.paste:false} onClick={()=>void contextAction(action)}>{action}</button>)}</div>,host.current?.closest(".ade")??document.body)}</>;
}
