import {HighlightStyle,syntaxHighlighting} from "@codemirror/language";
import {tags} from "@lezer/highlight";
import {createPortal} from "react-dom";
import {copyText,readText} from "./clipboard";
import {markCustomMenu,menuKeys} from "./menuKeys";
import {useEffect,useRef,useState} from "react";
import {basicSetup} from "codemirror";
import {EditorView} from "@codemirror/view";
import {EditorState,Compartment} from "@codemirror/state";
import {javascript} from "@codemirror/lang-javascript";
import {json} from "@codemirror/lang-json";
import {markdown} from "@codemirror/lang-markdown";
import {python} from "@codemirror/lang-python";
import {html} from "@codemirror/lang-html";
import {css} from "@codemirror/lang-css";
function language(path:string){const ext=path.split('.').at(-1);if(['js','jsx','ts','tsx'].includes(ext||''))return javascript({typescript:ext==='ts'||ext==='tsx',jsx:ext==='jsx'||ext==='tsx'});if(ext==='json')return json();if(ext==='md')return markdown();if(ext==='py')return python();if(['html','htm'].includes(ext||''))return html();if(ext==='css')return css();return [];}
export default function CodeEditor({path,value,onChange,wrap,disabled}:{path:string;value:string;onChange:(value:string)=>void;wrap:boolean;disabled:boolean}){
 const [context,setContext]=useState<{x:number;y:number;from:number;to:number;document:string;paste:boolean}|null>(null);const [menuError,setMenuError]=useState("");const contextEpoch=useRef(0);const popup=useRef<HTMLDivElement>(null);
 const openContext=(event:MouseEvent,editor:EditorView)=>{event.preventDefault();const range=editor.state.selection.main;const epoch=++contextEpoch.current;setMenuError("");setContext({x:Math.max(8,Math.min(event.clientX,window.innerWidth-178)),y:Math.max(8,Math.min(event.clientY,window.innerHeight-158)),from:range.from,to:range.to,document:editor.state.doc.toString(),paste:false});void readText().then(text=>{if(contextEpoch.current===epoch)setContext(current=>current?{...current,paste:Boolean(text)}:null);}).catch(()=>{});return true;};
 const closeContext=()=>{contextEpoch.current++;setContext(null);};
 useEffect(()=>{if(!context)return;const release=markCustomMenu(host.current);popup.current?.querySelector<HTMLButtonElement>("button:not(:disabled)")?.focus();const outside=(event:PointerEvent)=>{if(!popup.current?.contains(event.target as Node))closeContext();};document.addEventListener("pointerdown",outside);window.addEventListener("openade-dismiss-menus",closeContext);return()=>{release();document.removeEventListener("pointerdown",outside);window.removeEventListener("openade-dismiss-menus",closeContext);};},[Boolean(context)]);
 const contextAction=async(action:"Cut"|"Copy"|"Paste"|"Select All")=>{const editor=view.current,selection=context;if(!editor||!selection)return;closeContext();editor.focus();try{if(action==="Select All"){editor.dispatch({selection:{anchor:0,head:editor.state.doc.length}});return;}if(action==="Copy"||action==="Cut")await copyText(selection.document.slice(selection.from,selection.to));const text=action==="Paste"?await readText():"";if(action==="Copy")return;if(disabled||view.current!==editor||editor.state.doc.toString()!==selection.document)throw Error("The document changed; select the text again before editing.");if(action==="Paste"&&!text)return;if(new TextEncoder().encode(selection.document.length?selection.document.slice(0,selection.from)+text+selection.document.slice(selection.to):text).length>2*1024*1024)throw Error("Text files are limited to 2 MiB.");editor.dispatch({changes:{from:selection.from,to:selection.to,insert:text},selection:{anchor:selection.from+text.length},userEvent:action==="Cut"?"delete.cut":"input.paste"});editor.focus();}catch(reason){setMenuError(reason instanceof Error?reason.message:"Clipboard operation failed.");}};
 const host=useRef<HTMLDivElement>(null);const view=useRef<EditorView|null>(null);const callback=useRef(onChange);callback.current=onChange;const config=useRef(new Compartment());
 useEffect(()=>{if(!host.current)return;const editor=new EditorView({parent:host.current,state:EditorState.create({doc:value,extensions:[basicSetup,EditorView.domEventHandlers({contextmenu:openContext}),syntaxHighlighting(HighlightStyle.define([{tag:tags.keyword,color:"var(--syntax-keyword)"},{tag:[tags.string,tags.regexp],color:"var(--syntax-string)"},{tag:[tags.number,tags.bool,tags.null],color:"var(--syntax-number)"},{tag:[tags.typeName,tags.className],color:"var(--syntax-type)"},{tag:tags.variableName,color:"var(--syntax-variable)"},{tag:tags.propertyName,color:"var(--syntax-property)"},{tag:tags.punctuation,color:"var(--syntax-punctuation)"},{tag:tags.tagName,color:"var(--syntax-tag)"},{tag:tags.attributeName,color:"var(--syntax-attribute)"},{tag:tags.invalid,color:"var(--syntax-invalid)"},{tag:tags.comment,color:"var(--syntax-comment)",fontStyle:"italic"},{tag:tags.function(tags.variableName),color:"var(--syntax-function)"}])),language(path),config.current.of([EditorView.editable.of(!disabled),...(wrap?[EditorView.lineWrapping]:[])]),EditorView.contentAttributes.of({'aria-label':`Edit ${path}`,'role':'textbox','aria-multiline':'true'}),EditorView.updateListener.of(update=>{if(update.docChanged)callback.current(update.state.doc.toString());}),EditorView.theme({'&':{height:'100%',fontSize:'var(--code-size)',color:'var(--text)',backgroundColor:'transparent'},'.cm-scroller':{fontFamily:'var(--code-font)',overflow:'auto'},'.cm-gutters':{backgroundColor:'transparent',color:'var(--faint)',borderRight:'1px solid var(--line)'},'.cm-activeLine,.cm-activeLineGutter':{backgroundColor:'color-mix(in srgb,var(--accent) 6%,transparent)'},'.cm-cursor':{borderLeftColor:'var(--text)'},'.cm-selectionBackground':{backgroundColor:'color-mix(in srgb,var(--accent) 25%,transparent) !important'},'.cm-content':{padding:'8px 0'}})]})});view.current=editor;return()=>{editor.destroy();view.current=null;};},[path]);
 useEffect(()=>{const editor=view.current;if(editor&&editor.state.doc.toString()!==value)editor.dispatch({changes:{from:0,to:editor.state.doc.length,insert:value}});},[value]);
 useEffect(()=>{view.current?.dispatch({effects:config.current.reconfigure([EditorView.editable.of(!disabled),...(wrap?[EditorView.lineWrapping]:[])])});},[wrap,disabled]);
 return <><div className="code-editor-host" ref={host}/>{menuError&&<p className="inline-error" role="alert">{menuError}</p>}{context&&createPortal(<div ref={popup} className="editor-context-menu select-popover" role="menu" aria-label="Editor actions" style={{position:"fixed",left:context.x,top:context.y,width:170}} onKeyDown={event=>menuKeys(event,closeContext,()=>view.current?.focus())}>{(["Cut","Copy","Paste","Select All"] as const).map(action=><button type="button" role="menuitem" key={action} disabled={action==="Cut"?disabled||context.from===context.to:action==="Copy"?context.from===context.to:action==="Paste"?disabled||!context.paste:false} onClick={()=>void contextAction(action)}>{action}</button>)}</div>,host.current?.closest(".ade")??document.body)}</>;
}
