import { useEffect, useRef, useState } from "react";
import { ArrowClockwise, Copy, FileArrowUp, FolderSimple, LinkBreak, PencilSimple, Trash, FolderOpen } from "@phosphor-icons/react";
import { importThemeFiles, installThemeLibrary, isSnapshotTheme, libraryThemeId, removeCustomTheme, themes, Theme } from "./themes";
import { duplicateThemeSource, listThemeLibrary, nativeThemePickerAvailable, nativeThemeRevealAvailable, reloadThemeSource, removeThemeSource, revealNativeThemeSource, ThemeLibraryEntry, unlinkThemeSource } from "./theme-library-api";
import { ThemeImportDialog } from "./ThemeImportDialog";
import { Select } from "./Select";
import "./custom-themes.css";

type Preferences={light_theme:string;dark_theme:string};
type SourceAction="reload"|"unlink"|"reveal"|"snapshot"|"editable"|"remove";

export function CustomThemeManager({preferences,onChange}:{preferences:Preferences;onChange:(next:Preferences)=>void}) {
 const picker=useRef<HTMLInputElement>(null),folderPicker=useRef<HTMLInputElement>(null),importButton=useRef<HTMLButtonElement>(null);const [replaceId,setReplaceId]=useState("");const [message,setMessage]=useState("");const [entries,setEntries]=useState<ThemeLibraryEntry[]>([]);const [sourceReady,setSourceReady]=useState(false);const [version,setVersion]=useState(0),[importOpen,setImportOpen]=useState(false);
 const snapshots=themes.filter(theme=>isSnapshotTheme(theme.id));
 const refresh=async()=>{try{const next=await listThemeLibrary();installThemeLibrary(next);setEntries(next);setSourceReady(true);setVersion(value=>value+1);}catch{setSourceReady(false);}};
 useEffect(()=>{void refresh();},[]);
 const importFiles=async(files:FileList|null)=>{if(!files?.length)return;try{const result=await importThemeFiles(Array.from(files),replaceId||undefined);setMessage(result.map(item=>`${item.name} imported${item.replaced?" and replaced":""}.`).join(" "));setReplaceId("");setVersion(value=>value+1);}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{if(picker.current)picker.current.value="";}};
 const apply=(theme:Theme)=>onChange(theme.appearance==="light"?{...preferences,light_theme:theme.id}:{...preferences,dark_theme:theme.id});
 const fallback=(theme:Theme)=>onChange({...preferences,light_theme:preferences.light_theme===theme.id?"zeron-light":preferences.light_theme,dark_theme:preferences.dark_theme===theme.id?"zeron-dark":preferences.dark_theme});
 const fallbackEntry=(entry:ThemeLibraryEntry)=>{const next={...preferences};for(const variant of entry.variants){const id=libraryThemeId(entry.id,variant.id);if(variant.appearance==="light"&&next.light_theme===id)next.light_theme="zeron-light";if(variant.appearance==="dark"&&next.dark_theme===id)next.dark_theme="zeron-dark";}if(next.light_theme!==preferences.light_theme||next.dark_theme!==preferences.dark_theme)onChange(next);};
 const remove=(theme:Theme)=>{try{removeCustomTheme(theme.id);fallback(theme);setMessage(`${theme.name} removed.`);setVersion(value=>value+1);}catch(error){setMessage(error instanceof Error?error.message:String(error));}};
 const closeImport=()=>{setImportOpen(false);requestAnimationFrame(()=>importButton.current?.focus());};
 const sourceAction=async(entry:ThemeLibraryEntry,action:SourceAction)=>{try{if(action==="reveal"){if(!entry.source.path)throw Error("This snapshot has no source to reveal.");await revealNativeThemeSource(entry.id);setMessage(`${entry.name} revealed in Finder.`);return;}if(action==="reload")await reloadThemeSource(entry.id);if(action==="unlink")await unlinkThemeSource(entry.id);if(action==="snapshot"||action==="editable")await duplicateThemeSource(entry.id,action);if(action==="remove")await removeThemeSource(entry.id);if(action==="remove")fallbackEntry(entry);setMessage(action==="reload"?`${entry.name} reloaded.`:action==="unlink"?`${entry.name} is now a snapshot.`:action==="editable"?"Editable family created.":action==="snapshot"?"Snapshot copy created.":`${entry.name} removed.`);await refresh();}catch(error){setMessage(error instanceof Error?error.message:String(error));await refresh();}};
 return <section className="custom-theme-manager" aria-label="Custom themes" data-version={version}><div className="custom-theme-heading"><div><h2>Custom themes</h2><p>Import a snapshot, or link a local VS Code source in the native app.</p></div><span className="custom-theme-actions">{nativeThemePickerAvailable()?<button ref={importButton} type="button" onClick={()=>setImportOpen(true)}><FileArrowUp/>Import themes…</button>:<><button type="button" onClick={()=>picker.current?.click()}><FileArrowUp/>Import file</button><button type="button" onClick={()=>folderPicker.current?.click()}><FolderSimple/>Import extension</button></>}</span></div>
  <input ref={picker} className="custom-theme-file-picker" type="file" accept=".json,application/json" onChange={event=>void importFiles(event.currentTarget.files)} aria-label="Choose VS Code theme JSON file"/>
  <input ref={folderPicker} className="custom-theme-file-picker" type="file" multiple onChange={event=>void importFiles(event.currentTarget.files)} {...({webkitdirectory:""} as Record<string,string>)} aria-label="Choose VS Code extension folder"/>
  {snapshots.length>0&&<label className="custom-theme-replace">Replace imported snapshot <Select aria-label="Replace existing theme" value={replaceId} onChange={event=>setReplaceId(event.target.value)}><option value="">Import as new theme</option>{snapshots.map(theme=><option value={theme.id} key={theme.id}>{theme.name} · {theme.appearance}</option>)}</Select></label>}
  {message&&<p className="custom-theme-message" role="status">{message}</p>}
  {snapshots.length>0&&<div className="custom-theme-list">{snapshots.map(theme=><SnapshotRow key={theme.id} theme={theme} preferences={preferences} onApply={apply} onRemove={remove}/>)}</div>}
  {sourceReady&&<section className="linked-theme-library" aria-label="Theme library"><h3>Theme library</h3>{entries.length?<div className="custom-theme-list">{entries.map(entry=><LibraryRow entry={entry} preferences={preferences} onApply={apply} onAction={sourceAction} key={entry.id}/>)}</div>:<p className="custom-theme-empty">No saved themes yet.</p>}</section>}
  {importOpen&&<ThemeImportDialog onClose={closeImport} onImported={entry=>{setMessage(`${entry.name} imported.`);void refresh();closeImport();}}/>}
 </section>;
}

function SnapshotRow({theme,preferences,onApply,onRemove}:{theme:Theme;preferences:Preferences;onApply:(theme:Theme)=>void;onRemove:(theme:Theme)=>void}){return <div className="custom-theme-item"><Swatch theme={theme}/><span className="custom-theme-info"><strong>{theme.name}</strong><small>{theme.appearance} · snapshot</small></span><button type="button" onClick={()=>onApply(theme)}>{(theme.appearance==="light"?preferences.light_theme:preferences.dark_theme)===theme.id?<><ArrowClockwise/>Applied</>:"Apply"}</button><button type="button" className="custom-theme-remove" aria-label={`Remove ${theme.name}`} onClick={()=>onRemove(theme)}><Trash/></button></div>}
function LibraryRow({entry,preferences,onApply,onAction}:{entry:ThemeLibraryEntry;preferences:Preferences;onApply:(theme:Theme)=>void;onAction:(entry:ThemeLibraryEntry,action:SourceAction)=>void}) {const linked=entry.source.kind==="linkedFile"||entry.source.kind==="linkedPackage",editable=entry.source.kind==="editableFile",reloadable=linked||editable,reveal=nativeThemeRevealAvailable()&&!!entry.source.path;return <div className="linked-theme-item"><div className="linked-theme-title"><span><strong>{entry.name}</strong><small>{entry.source.kind.replace(/([A-Z])/g," $1").toLowerCase()}{entry.status.state==="warning"?" · needs attention":""}</small></span>{entry.status.message&&<span className="linked-theme-warning" role="status">{entry.status.message}</span>}</div><div className="linked-theme-variants">{entry.variants.map(variant=>{const id=libraryThemeId(entry.id,variant.id),theme=themes.find(item=>item.id===id);return theme&&<div className="custom-theme-item" key={id}><Swatch theme={theme}/><span className="custom-theme-info"><strong>{theme.name}</strong><small>{theme.appearance}</small></span><button type="button" onClick={()=>onApply(theme)}>{(theme.appearance==="light"?preferences.light_theme:preferences.dark_theme)===theme.id?"Applied":"Apply"}</button></div>})}</div><div className="linked-theme-actions">{reloadable&&<button type="button" onClick={()=>void onAction(entry,"reload")}><ArrowClockwise/>Reload</button>}{linked&&<button type="button" onClick={()=>void onAction(entry,"unlink")}><LinkBreak/>Unlink</button>}{reveal&&<button type="button" onClick={()=>void onAction(entry,"reveal")}><FolderOpen/>Reveal</button>}<button type="button" onClick={()=>void onAction(entry,"snapshot")}><Copy/>Snapshot</button><button type="button" onClick={()=>void onAction(entry,"editable")}><PencilSimple/>Editable</button><button type="button" className="custom-theme-remove" aria-label={`Remove ${entry.name}`} onClick={()=>void onAction(entry,"remove")}><Trash/></button></div></div>}
function Swatch({theme}:{theme:Theme}){return <span className="custom-theme-swatch" aria-hidden="true"><i style={{background:theme.colors.shell}}/><i style={{background:theme.colors.background}}/><i style={{background:theme.accent.primary}}/></span>}
