import {ArrowClockwise,Check,Columns,GitBranch} from "@phosphor-icons/react";
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";
import {fetchHistory,getHistory,GitCommit,GitHistoryPage,Session} from "./api";
import {HistoryColumn,Preferences} from "./preferences";
import {markCustomMenu,menuKeys} from "./menuKeys";
import {branchRefKey,collapseHistoryBranches,HistoryGraph,layoutHistoryGraph} from "./HistoryGraph";

const labels:Record<HistoryColumn,string>={author:"Author",date:"Date",sha:"SHA"};
const defaults:Pick<Preferences,"history_columns"|"history_order"|"history_widths"|"history_author_display">={history_columns:{author:true,date:true,sha:true},history_order:["author","date","sha"],history_widths:{author:88,date:88,sha:74},history_author_display:"avatar"};
const bounds:Record<HistoryColumn,[number,number]>={author:[44,220],date:[68,180],sha:[58,140]};
const empty:GitHistoryPage={branch:"",commits:[],branch_tips:[],head_sha:"",next_cursor:null,total_count:0,head_commit_count:0};
type ViewMode="all"|"tips";

export function HistoryPanel({session,preferences,onPreferences,onOpenCommit}:{session:Session;preferences:Preferences;onPreferences:(next:Preferences)=>void;onOpenCommit:(commit:GitCommit)=>void}){
 const [commits,setCommits]=useState<GitCommit[]>([]),[tips,setTips]=useState<GitCommit[]>([]),[headSHA,setHeadSHA]=useState("");
 const [nextCursor,setNextCursor]=useState<number|null>(null),[totalCount,setTotalCount]=useState<number|null>(null),[headCount,setHeadCount]=useState<number|null>(null),[comparison,setComparison]=useState<GitHistoryPage["comparison"]>();
 const [searchText,setSearchText]=useState(""),[query,setQuery]=useState(""),[mode,setMode]=useState<ViewMode>("all"),[version,setVersion]=useState(0);
 const [error,setError]=useState(""),[fetchError,setFetchError]=useState(""),[loading,setLoading]=useState(false),[loadingOlder,setLoadingOlder]=useState(false),[fetching,setFetching]=useState(false);
 const [menu,setMenu]=useState<"columns"|"author"|null>(null),[copied,setCopied]=useState("");
 const [collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const menuRef=useRef<HTMLDivElement>(null),columnsButton=useRef<HTMLButtonElement>(null),authorButton=useRef<HTMLButtonElement>(null),generation=useRef(0);
 const listRef=useRef<HTMLDivElement>(null),[scrollTop,setScrollTop]=useState(0),[viewportHeight,setViewportHeight]=useState(560);
 const foldAnchor=useRef<{sha:string;offset:number}|null>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>setQuery(searchText.trim()),180);return()=>window.clearTimeout(timer);},[searchText]);
 useEffect(()=>{setMode("all");setCollapsed(new Set());setSearchText("");setQuery("");},[session.id]);
 useEffect(()=>{const current=++generation.current;setLoading(true);setError("");setCommits([]);setNextCursor(null);
  void (session.branch?getHistory(session.id,0,query):Promise.resolve(empty)).then(page=>{if(current!==generation.current)return;setCommits(page.commits);setTips(page.branch_tips);setHeadSHA(page.head_sha);setNextCursor(page.next_cursor);setTotalCount(page.total_count);setHeadCount(page.head_commit_count);setComparison(page.comparison);}).catch(reason=>{if(current===generation.current)setError(String(reason));}).finally(()=>{if(current===generation.current)setLoading(false);});
  return()=>{generation.current++;};
 },[session.id,session.branch,query,version]);
 useEffect(()=>{if(!menu)return;const outside=(event:PointerEvent)=>{if(!menuRef.current?.contains(event.target as Node)&&!columnsButton.current?.contains(event.target as Node)&&!authorButton.current?.contains(event.target as Node))setMenu(null);};document.addEventListener("pointerdown",outside);return()=>document.removeEventListener("pointerdown",outside);},[menu]);
 useEffect(()=>{if(!menu)return;const unmark=markCustomMenu(menuRef.current);const frame=requestAnimationFrame(()=>menuRef.current?.querySelector<HTMLButtonElement>("button")?.focus());return()=>{cancelAnimationFrame(frame);unmark();};},[menu]);
 useEffect(()=>{if(!copied)return;const timer=window.setTimeout(()=>setCopied(""),1600);return()=>window.clearTimeout(timer);},[copied]);
 useEffect(()=>{const host=listRef.current;if(!host)return;const observer=new ResizeObserver(()=>setViewportHeight(host.clientHeight));observer.observe(host);setViewportHeight(host.clientHeight);return()=>observer.disconnect();},[]);
 useEffect(()=>{listRef.current?.scrollTo(0,0);setScrollTop(0);},[mode,query,session.id]);
 const searching=Boolean(query),showTips=mode==="tips"&&!searching;
 const folded=useMemo(()=>collapseHistoryBranches(commits,collapsed,headSHA),[commits,collapsed,headSHA]);
 const visible=useMemo(()=>showTips?tips.map(tip=>({...tip,parents:""})):searching?commits:folded.commits,[commits,folded.commits,tips,showTips,searching]);
 const graph=useMemo(()=>layoutHistoryGraph(visible,headSHA),[visible,headSHA]);
 useLayoutEffect(()=>{const anchor=foldAnchor.current,host=listRef.current;if(!anchor||!host)return;foldAnchor.current=null;const index=visible.findIndex(item=>item.sha===anchor.sha);if(index>=0){host.scrollTop=Math.max(0,index*36-anchor.offset);setScrollTop(host.scrollTop);}},[visible]);
 const rowHeight=36,windowStart=Math.max(0,Math.floor(scrollTop/rowHeight)-8),windowEnd=Math.min(visible.length,Math.ceil((scrollTop+viewportHeight)/rowHeight)+8);
 const count=searching?totalCount:showTips?tips.length:headCount??totalCount;
 const order=preferences.history_order.filter(key=>preferences.history_columns[key]);
 const columns=`minmax(160px,1fr) ${order.map(key=>`${preferences.history_widths[key]}px`).join(" ")}`;
 const update=(patch:Partial<Preferences>)=>onPreferences({...preferences,...patch});
 const move=(key:HistoryColumn,offset:number)=>{const next=[...preferences.history_order],from=next.indexOf(key),to=Math.max(0,Math.min(next.length-1,from+offset));if(from===to)return;next.splice(from,1);next.splice(to,0,key);update({history_order:next});};
 const beginResize=(event:React.PointerEvent,key:HistoryColumn)=>{event.preventDefault();event.stopPropagation();const handle=event.currentTarget as HTMLElement,start=event.clientX,initial=preferences.history_widths[key];handle.setPointerCapture(event.pointerId);const movePointer=(next:PointerEvent)=>{const [min,max]=bounds[key];onPreferences({...preferences,history_widths:{...preferences.history_widths,[key]:Math.min(max,Math.max(min,Math.round(initial+next.clientX-start)))}});};const stop=(next:PointerEvent)=>{handle.releasePointerCapture(next.pointerId);handle.removeEventListener("pointermove",movePointer);handle.removeEventListener("pointerup",stop);handle.removeEventListener("pointercancel",stop);};handle.addEventListener("pointermove",movePointer);handle.addEventListener("pointerup",stop);handle.addEventListener("pointercancel",stop);};
 const loadOlder=()=>{if(nextCursor===null||loadingOlder||loading)return;const current=generation.current,cursor=nextCursor;setLoadingOlder(true);setError("");void getHistory(session.id,cursor,query).then(page=>{if(current!==generation.current)return;setCommits(previous=>{const known=new Set(previous.map(item=>item.sha));return [...previous,...page.commits.filter(item=>!known.has(item.sha))];});setNextCursor(page.next_cursor);if(page.total_count!==null)setTotalCount(page.total_count);}).catch(reason=>{if(current===generation.current)setError(String(reason));}).finally(()=>{if(current===generation.current)setLoadingOlder(false);});};
 const fetchAll=()=>{if(fetching)return;setFetching(true);setFetchError("");void fetchHistory(session.id).then(()=>setVersion(value=>value+1)).catch(reason=>setFetchError(String(reason))).finally(()=>setFetching(false));};
 const copySHA=(event:React.MouseEvent,sha:string)=>{event.stopPropagation();void navigator.clipboard.writeText(sha).then(()=>setCopied(sha)).catch(reason=>setError(String(reason)));};
 const focusRow=(index:number)=>{const host=listRef.current;if(!host||index<0||index>=visible.length)return;const top=index*rowHeight;if(top<host.scrollTop)host.scrollTop=top;else if(top+rowHeight>host.scrollTop+host.clientHeight)host.scrollTop=top+rowHeight-host.clientHeight;setScrollTop(host.scrollTop);requestAnimationFrame(()=>host.querySelector<HTMLElement>(`[data-history-index="${index}"]`)?.focus());};
 const toggleFold=(event:React.MouseEvent,commit:GitCommit,key:string)=>{event.stopPropagation();const host=listRef.current,index=visible.findIndex(item=>item.sha===commit.sha);if(host&&index>=0)foldAnchor.current={sha:commit.sha,offset:index*rowHeight-host.scrollTop};setCollapsed(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});};
 const graphCell=(commit:GitCommit,index:number)=>{const reference=!showTips&&!searching?commit.refs.find(ref=>branchRefKey(ref)!==undefined):undefined;const key=reference?branchRefKey(reference):undefined;const isCollapsed=key?collapsed.has(key):false;const hidden=key?folded.hidden.get(key)??0:0;return <span className="history-graph-wrap"><HistoryGraph row={graph.rows[index]} lanes={graph.lanes}/>{key&&<button className={`history-fold ${isCollapsed?"collapsed":""}`} style={{left:Math.min(graph.rows[index].lane,6)*13+12}} aria-label={`${isCollapsed?"Expand":"Collapse"} ${reference!.label}${isCollapsed&&hidden?` (${hidden} hidden)`:""}`} title={`${isCollapsed?"Expand":"Collapse"} ${reference!.label}`} onClick={event=>toggleFold(event,commit,key)}>{isCollapsed?"+":"−"}</button>}</span>;};
 const cell=(commit:GitCommit,key:HistoryColumn)=>key==="author"?preferences.history_author_display==="avatar"?<span className="history-avatar" title={commit.author} aria-label={commit.author}>{commit.author.trim().charAt(0).toUpperCase()}</span>:<span title={commit.author}>{commit.author}</span>:key==="date"?<time dateTime={commit.date} title={new Date(commit.date).toLocaleString()}>{new Date(commit.date).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time>:<button className="history-sha" aria-label={`${copied===commit.sha?"Copied":"Copy"} SHA ${commit.sha.slice(0,7)}`} title={copied===commit.sha?"Copied full SHA":commit.sha} onClick={event=>copySHA(event,commit.sha)}>{copied===commit.sha?"Copied":commit.sha.slice(0,7)}</button>;
 return <section className="history-panel">
  <header><GitBranch/><span>{session.branch||"No repository"}</span><small>{count??commits.length} {searching?"matches":showTips?"tips":"commits"}</small>{comparison&&<small className="history-comparison" title={`Compared with ${comparison.base}`}>↑{comparison.ahead} ↓{comparison.behind}</small>}<button className="history-fetch" disabled={fetching||!session.branch} onClick={fetchAll}>{fetching?"Fetching…":"Fetch all"}</button><button className="icon-button" aria-label={showTips?"Show all commits":"Show branch tips"} aria-pressed={showTips} disabled={!session.branch} onClick={()=>{if(mode==="tips")setCollapsed(new Set());setMode(current=>current==="tips"?"all":"tips");}}><GitBranch/></button><button className="icon-button" aria-label="Refresh history" onClick={()=>setVersion(value=>value+1)}><ArrowClockwise/></button></header>
  <div className="history-search"><input aria-label="Search history" placeholder="Search commits" value={searchText} onChange={event=>setSearchText(event.target.value)}/><button ref={columnsButton} aria-label="History columns" aria-expanded={menu==="columns"} aria-haspopup="menu" onClick={()=>setMenu(current=>current==="columns"?null:"columns")}><Columns/></button>{menu==="columns"&&<div ref={menuRef} className="history-menu history-columns-menu" role="menu" aria-label="History columns" onKeyDown={event=>menuKeys(event,()=>setMenu(null),()=>columnsButton.current?.focus())}>{(["author","date","sha"] as HistoryColumn[]).map(key=><button role="menuitemcheckbox" aria-checked={preferences.history_columns[key]} key={key} onClick={()=>update({history_columns:{...preferences.history_columns,[key]:!preferences.history_columns[key]}})}><span>{labels[key]}</span>{preferences.history_columns[key]&&<Check/>}</button>)}<button role="menuitem" onClick={()=>{update(defaults);setMenu(null);}}>Reset columns</button></div>}</div>
  {fetchError&&<p className="history-error" role="alert">Fetch failed: {fetchError}</p>}{error&&<p className="history-error" role="alert">{error}</p>}
  <div className="history-heading" style={{gridTemplateColumns:columns}}><span><span className="history-graph-space" style={{width:Math.max(22,Math.min(7,graph.lanes)*13+9)}}/>Commit</span>{order.map(key=><div className="history-column" key={key} draggable onDragStart={event=>{event.dataTransfer.setData("text/plain",key);event.dataTransfer.effectAllowed="move";}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const source=event.dataTransfer.getData("text/plain") as HistoryColumn;if((source==="author"||source==="date"||source==="sha")&&source!==key)move(source,preferences.history_order.indexOf(key)-preferences.history_order.indexOf(source));}}><button ref={key==="author"?authorButton:undefined} aria-label={`${labels[key]} column`} aria-haspopup={key==="author"?"menu":undefined} aria-expanded={key==="author"?menu==="author":undefined} title={key==="author"?"Author display and column order":"Drag to reorder; Option+Arrow to reorder"} onClick={()=>key==="author"&&setMenu(current=>current==="author"?null:"author")} onKeyDown={event=>{if(event.altKey&&["ArrowLeft","ArrowRight"].includes(event.key)){event.preventDefault();move(key,event.key==="ArrowLeft"?-1:1);}}}>{labels[key]}</button><span className="history-resize" role="separator" aria-label={`Resize ${labels[key]} column`} aria-orientation="vertical" tabIndex={0} onPointerDown={event=>beginResize(event,key)} onKeyDown={event=>{if(["ArrowLeft","ArrowRight"].includes(event.key)){event.preventDefault();const [min,max]=bounds[key];update({history_widths:{...preferences.history_widths,[key]:Math.min(max,Math.max(min,preferences.history_widths[key]+(event.key==="ArrowLeft"?-4:4)))}});}}}/>{key==="author"&&menu==="author"&&<div ref={menuRef} className="history-menu history-author-menu" role="menu" aria-label="Author display" onKeyDown={event=>menuKeys(event,()=>setMenu(null),()=>authorButton.current?.focus())}>{(["avatar","name"] as const).map(choice=><button role="menuitemradio" aria-checked={preferences.history_author_display===choice} key={choice} onClick={()=>{update({history_author_display:choice});setMenu(null);}}><span>{choice==="avatar"?"Avatar":"Name"}</span>{preferences.history_author_display===choice&&<Check/>}</button>)}</div>}</div>)}</div>
  <div className="history-table" ref={listRef} onScroll={event=>setScrollTop(event.currentTarget.scrollTop)}>{loading?<p className="history-empty" role="status">Loading history…</p>:<><div className="history-spacer" style={{height:windowStart*rowHeight}}/>{visible.slice(windowStart,windowEnd).map((commit,offset)=>{const index=windowStart+offset;return <div className="history-row" role="group" tabIndex={0} data-history-index={index} style={{gridTemplateColumns:columns}} key={commit.sha} onClick={()=>onOpenCommit(commit)} onKeyDown={event=>{if(event.target!==event.currentTarget)return;if(event.key==="ArrowDown"||event.key==="ArrowUp"){event.preventDefault();focusRow(index+(event.key==="ArrowDown"?1:-1));}else if(["Enter"," "].includes(event.key)){event.preventDefault();onOpenCommit(commit);}}} aria-label={`Commit row ${commit.subject}`}><span className="history-subject">{graphCell(commit,index)}<button className="history-open" aria-label={`Open commit ${commit.subject}`} title={commit.subject}>{commit.subject||"(no subject)"}</button>{commit.refs.length>0&&<span className="history-refs" title={commit.refs.map(ref=>`${ref.kind}: ${ref.label}`).join("\n")}>{commit.refs.slice(0,2).map(ref=><span className={`history-ref ${ref.kind}`} key={`${ref.kind}:${ref.label}`}>{ref.label}</span>)}{commit.refs.length>2&&<span className="history-ref">+{commit.refs.length-2}</span>}</span>}</span>{order.map(key=><span className="history-cell" key={key}>{cell(commit,key)}</span>)}</div>;})}<div className="history-spacer" style={{height:(visible.length-windowEnd)*rowHeight}}/></>}{!loading&&!visible.length&&<p className="history-empty">{searching?"No matching commits":showTips?"No branch tips found":"No commits found"}</p>}{!showTips&&nextCursor!==null&&<div className="history-load-more"><button disabled={loadingOlder} onClick={loadOlder}>{loadingOlder?"Loading older…":"Load older"}</button></div>}</div>
 </section>;
}
