import {createPortal} from 'react-dom';
import {useEffect,useMemo,useRef,useState} from 'react';
import type {RefObject} from 'react';
import type {ChatTurn} from './chat-model';
import {parseAttachments} from './Attachments';
import {parseReviewComments} from './ReviewComments';
import './message-rail.css';

export function MessageRail({turns,timeline,onJump}:{turns:ChatTurn[];timeline:RefObject<HTMLDivElement|null>;onJump:(index:number)=>void}){
 const [size,setSize]=useState({width:0,height:600}),[active,setActive]=useState(''),[hover,setHover]=useState<number|null>(null),[bounds,setBounds]=useState({left:0,top:0});const frame=useRef(0);
 const ticks=useMemo(()=>{const result:{id:string;index:number;prompt:string;reply:string}[]=[];let reply="";for(let index=turns.length-1;index>=0;index--){const turn=turns[index];if(turn.role==='assistant')reply=turn.markdown;else result.push({id:turn.id,index,prompt:parseAttachments(parseReviewComments(turn.markdown).text).text||'Attached image(s)',reply});}return result.reverse();},[turns]);
 const enabled=size.width>=768&&ticks.length>=2;
 useEffect(()=>{const node=timeline.current,scroll=node?.closest<HTMLElement>('.messages');if(!node||!scroll)return;const measure=()=>setSize({width:scroll.clientWidth,height:scroll.clientHeight});const update=()=>{frame.current=0;const line=scroll.getBoundingClientRect().top+24;let current='';for(const row of node.querySelectorAll<HTMLElement>('[data-message-id]')){if(row.getBoundingClientRect().top<=line)current=row.dataset.messageId!;else break;}if(!current)current=node.querySelector<HTMLElement>('[data-message-id]')?.dataset.messageId||'';setActive(current);};const schedule=()=>{if(!frame.current)frame.current=requestAnimationFrame(update);};const observer=new ResizeObserver(()=>{measure();schedule();});observer.observe(scroll);scroll.addEventListener('scroll',schedule,{passive:true});measure();schedule();return()=>{observer.disconnect();scroll.removeEventListener('scroll',schedule);cancelAnimationFrame(frame.current);};},[timeline,turns.length]);
 useEffect(()=>{const scroll=timeline.current?.closest('.messages');scroll?.classList.toggle('has-message-rail',enabled);return()=>scroll?.classList.remove('has-message-rail');},[enabled,timeline]);
 const host=timeline.current?.closest('.conversation');if(!enabled||!host)return null;
 const activeTurn=turns.findIndex(turn=>turn.id===active);let activeTick=0;for(let i=0;i<ticks.length;i++){if(ticks[i].index<=activeTurn)activeTick=i;else break;}
 const count=Math.min(ticks.length,12,Math.max(1,Math.floor((Math.max(10,size.height-48)+3)/13)));const buckets=Array.from({length:count},(_,index)=>({start:Math.floor(index*ticks.length/count),end:Math.floor((index+1)*ticks.length/count)}));
 const selected=hover===null?null:buckets[hover];const representative=selected?ticks[activeTick>=selected.start&&activeTick<selected.end?activeTick:selected.start]:null;
 const preview=(value:string,max:number)=>{const normalized=value.replace(/\s+/g,' ').trim();return [...normalized].length>max?[...normalized].slice(0,max).join('')+'…':normalized;};
 return createPortal(<><nav className="message-rail" aria-label="Conversation outline" onMouseLeave={()=>setHover(null)}>{buckets.map((bucket,index)=>{const isActive=activeTick>=bucket.start&&activeTick<bucket.end,tick=ticks[isActive?activeTick:bucket.start];const show=(node:HTMLElement)=>{const rect=node.getBoundingClientRect();setBounds({left:Math.min(window.innerWidth-296,rect.right+8),top:Math.max(8,Math.min(window.innerHeight-160,rect.top-30))});setHover(index);};return <button key={index} aria-label={`Jump to message ${bucket.start+1}: ${preview(tick.prompt,80)}`} aria-current={isActive?'location':undefined} onMouseEnter={event=>show(event.currentTarget)} onFocus={event=>show(event.currentTarget)} onBlur={()=>setHover(null)} onClick={()=>{setHover(null);setActive(tick.id);onJump(tick.index);}}><span/></button>;})}</nav>{representative&&createPortal(<div role="tooltip" className="message-rail-preview" style={{position:'fixed',...bounds}}><p>{preview(representative.prompt,160)}</p>{representative.reply&&<small>{preview(representative.reply,200)}</small>}{selected&&selected.end-selected.start>1&&<em>{selected.end-selected.start} prompts</em>}</div>,document.querySelector(".ade")||document.body)}</>,host);
}
