import {useEffect,useId,useRef,useState} from "react";
import {ArrowLeft,Desktop,Folder,House,MagnifyingGlass,Plus} from "@phosphor-icons/react";
import {getProjectDirectories,ProjectDirectoryListing,registerProject} from "./api";
import {markCustomMenu} from "./menuKeys";

export function ProjectPalette({onClose,onAdded,onCommands}:{onClose:()=>void;onAdded:(path:string)=>void;onCommands:()=>void}){
 const [step,setStep]=useState<"device"|"folders">("device"),[listing,setListing]=useState<ProjectDirectoryListing>({path:"",parent:"",entries:[]}),[query,setQuery]=useState(""),[active,setActive]=useState(0),[busy,setBusy]=useState(false),[choosing,setChoosing]=useState(false),[error,setError]=useState("");
 const card=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),epoch=useRef(0);const id=useId();
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const release=markCustomMenu(card.current);input.current?.focus();return()=>{epoch.current++;release();if(previous?.isConnected)previous.focus();};},[]);
 const load=async(path="")=>{const request=++epoch.current;setBusy(true);setError("");try{const result=await getProjectDirectories(path);if(request===epoch.current){setListing(result);setStep("folders");setQuery("");setActive(0);}}catch(reason){if(request===epoch.current)setError(reason instanceof Error?reason.message:"Cannot open this folder.");}finally{if(request===epoch.current){setBusy(false);input.current?.focus();}}};
 const entries=step==="device"?[{name:"Local",path:""}].filter(entry=>entry.name.toLowerCase().includes(query.toLowerCase())):listing.entries.filter(entry=>query.toLowerCase().split(/\s+/).every(word=>entry.name.toLowerCase().includes(word)));
 const current=Math.min(active,Math.max(0,entries.length-1));
 useEffect(()=>{card.current?.querySelector(`[data-folder-index="${current}"]`)?.scrollIntoView({block:"nearest"});},[current,listing.path,query]);
 const back=()=>{if(busy)return;if(step==="device"){onClose();onCommands();}else if(!listing.path){setStep("device");setQuery("");setActive(0);}else void load(listing.parent===listing.path?"":listing.parent);};
 const add=async()=>{const request=++epoch.current;setBusy(true);setError("");try{const result=await registerProject(listing.path);if(request===epoch.current){onAdded(result.path);onClose();}}catch(reason){if(request===epoch.current)setError(reason instanceof Error?reason.message:"Cannot add this project.");}finally{if(request===epoch.current)setBusy(false);}};
 const browse=async()=>{if(choosing)return;const attempt=++epoch.current;setBusy(false);setChoosing(true);setError("");const bridge=window as typeof window&{go?:{main?:{App?:{SelectRepository?:()=>Promise<string>}}}};try{const path=await bridge.go?.main?.App?.SelectRepository?.();if(attempt!==epoch.current)return;setChoosing(false);if(path)void load(path);}catch(reason){if(attempt===epoch.current)setError(reason instanceof Error?reason.message:"Folder selection failed.");}finally{if(attempt===epoch.current)setChoosing(false);}};
 return <div className="command-palette-overlay" onPointerDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}}><div ref={card} className="command-palette project-palette" role="dialog" aria-modal="true" aria-label="New project" onKeyDown={event=>{if(event.nativeEvent.isComposing)return;if(event.key==="Escape"){event.preventDefault();event.stopPropagation();onClose();}else if(event.key==="Tab"){event.preventDefault();const controls=[...card.current!.querySelectorAll<HTMLElement>('input,button:not(:disabled)')].filter(el=>el.tabIndex>=0);const index=controls.indexOf(document.activeElement as HTMLElement);controls[(index+(event.shiftKey?-1:1)+controls.length)%controls.length]?.focus();}else if(["ArrowDown","ArrowUp"].includes(event.key)){event.preventDefault();setActive((current+(event.key==="ArrowDown"?1:-1)+entries.length)%Math.max(1,entries.length));}else if(event.key==="ArrowLeft"&&event.target!==input.current){event.preventDefault();back();}else if(event.key==="Enter"&&event.target===input.current){event.preventDefault();if(event.repeat||busy)return;if(step==="folders"&&(/^(\/|~\/|[A-Za-z]:[\\/])/.test(query))){void load(query);return;}if(entries[current])void load(entries[current].path);}}}>
  <header><MagnifyingGlass/><input ref={input} role="combobox" aria-label={step==="device"?"Search devices":"Search locations and folders"} aria-controls={id} aria-expanded="true" aria-activedescendant={entries[current]?`${id}-${current}`:undefined} placeholder={step==="device"?"Search devices…":"Search folders or enter a path…"} value={query} onChange={event=>{setQuery(event.target.value);setActive(0);}}/><kbd>esc</kbd></header>
  <div className="project-palette-breadcrumb"><button type="button" aria-label="Back" disabled={busy} onClick={back}><ArrowLeft/></button><span>New project</span>{step==="folders"&&<><span>›</span><Desktop/><span>Local</span>{listing.path&&<><span>›</span><span title={listing.path}>{listing.path}</span></>}</>}</div>
  <div className="command-palette-results" role="listbox" aria-label="Project folders" id={id}>{entries.map((entry,index)=><button type="button" role="option" id={`${id}-${index}`} key={entry.path} data-folder-index={index} tabIndex={-1} aria-selected={index===current} disabled={busy} className={index===current?"highlighted":""} onPointerMove={()=>setActive(index)} onClick={()=>void load(entry.path)}>{step==="device"?<Desktop/>:entry.name==="Home"?<House/>:<Folder/>}<span>{entry.name}</span>{step==="device"&&<i className="status-dot completed"/>}</button>)}{busy&&<p role="status">Loading…</p>}{!busy&&!entries.length&&<p>No folders found</p>}</div>
  {error&&<p className="inline-error" role="alert">{error}</p>}{listing.limited&&<p className="project-picker-note">Showing the first 1,000 folders. Enter a path to open another location.</p>}
  {step==="folders"&&listing.path&&<div className="project-palette-add"><span>{listing.git?"Git project":"Folder workspace"}</span><button type="button" disabled={busy||Boolean(error)} onClick={()=>void add()}><Plus/>Add project</button></div>}
  <footer><span>↑ ↓ Navigate</span><span>↵ Select</span>{step==="folders"&&Boolean((window as typeof window&{go?:{main?:{App?:{SelectRepository?:()=>Promise<string>}}}}).go?.main?.App?.SelectRepository)&&<button type="button" disabled={choosing} onClick={()=>void browse()}>Browse folders…</button>}<span>Esc Close</span></footer>
 </div></div>;
}
