import {createPortal} from "react-dom";
import {useEffect,useLayoutEffect,useRef,useState} from "react";
import {getProviderState,ProviderRequest,ProviderState,replyToProvider} from "./api";
import "./provider-interaction.css";
const empty:ProviderState={connected:false,steering:false,requests:[],context:{tokens:null,window:null}};
export function useProviderState(id:string,active:boolean,visible:boolean){
 const [state,setState]=useState(empty),[error,setError]=useState("");const [revision,setRevision]=useState(0);
 useEffect(()=>{setState(empty);setError("");},[id]);
 useEffect(()=>{if(!visible)return;let disposed=false;let timer:number|undefined;let controller:AbortController|undefined;
 const poll=async()=>{if(disposed||document.hidden){timer=window.setTimeout(poll,1000);return;}controller=new AbortController();try{const next=await getProviderState(id,controller.signal);if(!disposed){setState(next);setError("");}}catch(reason){if(!disposed)setError(String(reason));}finally{if(!disposed)timer=window.setTimeout(poll,active?500:5000);}};
 void poll();return()=>{disposed=true;clearTimeout(timer);controller?.abort();};
 },[id,active,visible,revision]);
 return{state,error,refresh:()=>setRevision(value=>value+1)};
}
export function ProviderInteraction({id,request,onResolved}:{id:string;request:ProviderRequest;onResolved:()=>void}){
 const [page,setPage]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState("");const root=useRef<HTMLFormElement>(null),timer=useRef<number|undefined>(undefined);const alive=useRef(true),ownedFocus=useRef(false);
 useLayoutEffect(()=>{alive.current=true;const panel=root.current;const owner=panel?.closest(".session-workspace");panel?.focus();return()=>{const restore=Boolean(panel?.contains(document.activeElement))||(ownedFocus.current&&document.activeElement===document.body);alive.current=false;clearTimeout(timer.current);if(restore)requestAnimationFrame(()=>{const composer=owner?.querySelector<HTMLTextAreaElement>(".session-composer textarea:not(:disabled)");if(composer?.getClientRects().length&&!composer.closest("[hidden],[inert]"))composer.focus();});};},[]);
 const question=request.questions[page];
 const submit=async(values:Record<string,string>,decision?:string)=>{if(busy)return;setBusy(true);setError("");try{await replyToProvider(id,request,decision?{decision}:{answers:Object.fromEntries(Object.entries(values).map(([key,value])=>[key,[value]]))});onResolved();}catch(reason){if(alive.current){setError(String(reason));setBusy(false);}}};
 const advance=(values=answers)=>{if(!question||!values[question.id]?.trim())return;if(page+1<request.questions.length){setPage(page+1);requestAnimationFrame(()=>root.current?.focus());}else void submit(values);};
 const pick=(label:string)=>{if(busy)return;clearTimeout(timer.current);const values={...answers,[question.id]:label};setAnswers(values);timer.current=window.setTimeout(()=>advance(values),220);};
 return <form ref={root} className="provider-interaction" role="dialog" aria-modal="false" aria-label={request.title} tabIndex={-1} onFocusCapture={()=>{ownedFocus.current=true;}} onBlurCapture={event=>{if(event.relatedTarget&&!event.currentTarget.contains(event.relatedTarget as Node))ownedFocus.current=false;}} onSubmit={event=>{event.preventDefault();advance();}} onKeyDown={event=>{if(event.nativeEvent.isComposing||event.ctrlKey||event.metaKey||event.altKey)return;if(!(event.target instanceof HTMLInputElement)&&request.kind==="question"&&/^[1-9]$/.test(event.key)){const option=question.options?.[Number(event.key)-1];if(option){event.preventDefault();event.stopPropagation();pick(option.label);}}if(event.key==="Escape"){event.stopPropagation();clearTimeout(timer.current);}}}>
 {request.kind==="approval"?<><h2>{request.title}</h2><pre>{request.detail}</pre><footer>{request.decisions.map(decision=><button type="button" disabled={busy} key={decision} onClick={()=>void submit({},decision)}>{({accept:"Allow once",decline:"Deny",cancel:"Stop turn"} as Record<string,string>)[decision]}</button>)}</footer></>:<><header><span>{question.header||"Question"}</span>{request.questions.length>1&&<span>{page+1}/{request.questions.length}</span>}</header><h2>{question.question}</h2><div className="provider-options">{question.options?.map((option,index)=><button type="button" disabled={busy} key={`${index}-${option.label}`} title={option.description||undefined} aria-description={option.description||undefined} aria-pressed={answers[question.id]===option.label} onClick={()=>pick(option.label)}><span><strong>{option.label}</strong></span>{index<9&&<kbd>{index+1}</kbd>}</button>)}</div>{(question.isOther||!question.options?.length)&&<input type={question.isSecret?"password":"text"} aria-label={question.isSecret?"Private answer":"Your answer"} placeholder="Type your answer…" autoComplete="off" maxLength={65536} value={answers[question.id]??""} disabled={busy} onChange={event=>{clearTimeout(timer.current);setAnswers({...answers,[question.id]:event.target.value});}}/>}<footer>{page>0&&<button type="button" disabled={busy} onClick={()=>{clearTimeout(timer.current);setPage(page-1);}}>Back</button>}<button type="submit" disabled={busy||!answers[question.id]?.trim()}>{busy?"Sending…":page+1<request.questions.length?"Next":"Submit"}</button></footer></>}
 {error&&<p role="alert">{error}</p>}
 </form>;
}
export function ContextUsage({context,visible=true}:{context:ProviderState["context"];visible?:boolean}){
 const [open,setOpen]=useState(false);const ref=useRef<HTMLDivElement>(null),popup=useRef<HTMLDivElement>(null);const [bounds,setBounds]=useState({left:0,top:0});
 useEffect(()=>{if(!visible)setOpen(false)},[visible]);
 useLayoutEffect(()=>{if(!open||!visible)return;const place=()=>{const r=ref.current!.getBoundingClientRect(),h=popup.current?.offsetHeight??100;setBounds({left:Math.max(8,Math.min(r.right-240,window.innerWidth-248)),top:Math.max(8,Math.min(r.top-h-6,window.innerHeight-h-8))});};place();window.addEventListener("resize",place);window.addEventListener("scroll",place,true);return()=>{window.removeEventListener("resize",place);window.removeEventListener("scroll",place,true);};},[open,visible,context.tokens,context.window]);const known=context.tokens!==null&&context.window!==null&&context.window>0;const fraction=known?Math.min(1,context.tokens!/context.window!):0;const label=known?`${Math.round(fraction*100)}%`:"—";
 useEffect(()=>{if(!open)return;const close=(event:MouseEvent)=>{if(!ref.current?.contains(event.target as Node)&&!popup.current?.contains(event.target as Node))setOpen(false);};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setOpen(false);ref.current?.querySelector<HTMLButtonElement>("button")?.focus();}};const dismiss=()=>setOpen(false);document.addEventListener("mousedown",close);document.addEventListener("keydown",escape);window.addEventListener("openade-dismiss-menus",dismiss);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",escape);window.removeEventListener("openade-dismiss-menus",dismiss);};},[open]);
 return <div ref={ref} className="context-usage-anchor"><button type="button" className={`context-usage ${fraction>=.9?"danger":fraction>=.75?"warning":""}`} aria-label={`Context usage ${label}`} aria-expanded={open} onClick={()=>setOpen(value=>!value)}><svg viewBox="0 0 16 16" aria-hidden="true"><circle className="track" cx="8" cy="8" r="6"/><circle cx="8" cy="8" r="6" strokeDasharray={`${fraction*37.7} 37.7`} transform="rotate(-90 8 8)"/></svg>{label}</button>{open&&visible&&createPortal(<div ref={popup} style={{position:"fixed",...bounds,width:240}} className="context-usage-popover" role="dialog" aria-label="Context usage details"><strong>Context usage</strong><p>{known?`${context.tokens!.toLocaleString()} of ${context.window!.toLocaleString()} tokens`:"The provider has not reported its context window."}</p></div>,ref.current?.closest(".ade")??document.body)}</div>;
}
