import { CaretDown, Check, MagnifyingGlass } from "@phosphor-icons/react";
import { Children, isValidElement, ReactNode, useEffect, useId, useLayoutEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";

type Choice = { value: string; label: ReactNode; text: string; disabled?: boolean };
type Props = { children: ReactNode; value?: string | number | readonly string[]; onChange?: (event: { target: { value: string } }) => void; disabled?: boolean; "aria-label"?: string; className?: string; searchable?: boolean; icon?: ReactNode; placeholder?: string; footer?: ReactNode };
function textOf(value: ReactNode): string { return Children.toArray(value).map(child => isValidElement<{ children?: ReactNode }>(child) ? textOf(child.props.children) : String(child)).join(""); }

// One in-app popup surface for all choices; no platform select or hidden select.
export function Select({ children, value, onChange, disabled, "aria-label": label = "Choose option", className = "", searchable, icon, placeholder, footer }: Props) {
 const choices: Choice[] = Children.toArray(children).flatMap(child => isValidElement<{value?: string | number; children?: ReactNode; disabled?: boolean}>(child) ? [{value:String(child.props.value ?? textOf(child.props.children)),label:child.props.children,text:textOf(child.props.children),disabled:child.props.disabled}] : []);
 const selected=choices.find(choice=>choice.value===String(value));
 const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[active,setActive]=useState(0),[bounds,setBounds]=useState({left:0,top:0,width:220,maxHeight:320});
 const trigger=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null),typeahead=useRef({text:"",at:0});const id=useId();
 const filtered=choices.filter(choice=>choice.text.toLowerCase().includes(query.toLowerCase()));const canSearch=searchable??choices.length>7;
 const close=(restore=true)=>{setOpen(false);if(restore)trigger.current?.focus();};
 const choose=(choice:Choice)=>{if(choice.disabled)return;onChange?.({target:{value:choice.value}});close();};
 const move=(direction:number)=>{setActive(current=>{for(let step=1;step<=filtered.length;step++){const next=(current+direction*step+filtered.length)%filtered.length;if(!filtered[next].disabled)return next;}return current;});};
 useLayoutEffect(()=>{if(!open)return;const place=()=>{const rect=trigger.current!.getBoundingClientRect();const width=Math.min(Math.max(rect.width,canSearch?270:210),window.innerWidth-16);const height=Math.min(360,filtered.length*32+(canSearch?45:12)+(footer?96:0));const below=window.innerHeight-rect.bottom-12;const above=rect.top-12;const up=below<height&&above>below;const maxHeight=Math.max(80,Math.min(height,up?above:below));setBounds({left:Math.max(8,Math.min((trigger.current?.closest(".preference-row,.sidebar-menu-row,.reasoning-choice")||label==="Choose project"?rect.right-width:rect.left),window.innerWidth-width-8)),top:up?rect.top-maxHeight-6:rect.bottom+6,width,maxHeight});};place();window.addEventListener("resize",place);window.addEventListener("scroll",place,true);return()=>{window.removeEventListener("resize",place);window.removeEventListener("scroll",place,true);};},[open,filtered.length,canSearch,Boolean(footer)]);
 useEffect(()=>{if(!open)return;setQuery("");setActive(Math.max(0,choices.findIndex(choice=>choice.value===String(value))));if(canSearch)search.current?.focus();else popup.current?.focus();const root=trigger.current?.closest(".ade");root?.classList.add("has-custom-menu");const outside=(event:PointerEvent)=>{if(!trigger.current?.contains(event.target as Node)&&!popup.current?.contains(event.target as Node))close(false);};document.addEventListener("pointerdown",outside);return()=>{document.removeEventListener("pointerdown",outside);root?.classList.remove("has-custom-menu");};},[open]);
 useEffect(()=>{if(open)popup.current?.querySelector(`[data-index="${active}"]`)?.scrollIntoView({block:"nearest"});},[active,open]);
 const keys=(event:React.KeyboardEvent)=>{
  // Footer inputs keep normal editing keys and Tab can reach Browse.
  if(event.target!==search.current&&event.target instanceof HTMLInputElement){if(event.key==="Escape"){event.preventDefault();event.stopPropagation();close();}return;}
  if(["ArrowDown","ArrowUp","Home","End","Enter"," ","Escape"].includes(event.key)&&!(event.target===search.current&&event.key===" ")){event.preventDefault();event.stopPropagation();}
  if(event.key==="Escape")close();else if(event.key==="ArrowDown")move(1);else if(event.key==="ArrowUp")move(-1);else if(event.key==="Home")setActive(filtered.findIndex(choice=>!choice.disabled));else if(event.key==="End")setActive(filtered.length-1-[...filtered].reverse().findIndex(choice=>!choice.disabled));else if(event.key==="Enter"||(event.key===" "&&event.target!==search.current)){if(filtered[active])choose(filtered[active]);}else if(event.key.length===1&&event.target!==search.current){const now=Date.now();typeahead.current={text:(now-typeahead.current.at<600?typeahead.current.text:"")+event.key.toLowerCase(),at:now};const index=filtered.findIndex(choice=>!choice.disabled&&choice.text.toLowerCase().startsWith(typeahead.current.text));if(index>=0)setActive(index);}
 };
 const root=trigger.current?.closest(".ade")??document.body;
 return <><button type="button" ref={trigger} role="combobox" aria-label={label} aria-expanded={open} aria-haspopup="listbox" aria-controls={open?id:undefined} data-value={String(value??"")} disabled={disabled} className={`custom-select ${className}`} onClick={()=>setOpen(v=>!v)} onKeyDown={event=>{if(["ArrowDown","ArrowUp","Enter"," "].includes(event.key)){event.preventDefault();event.stopPropagation();setOpen(true);}}}>{icon}<span>{selected?.label??placeholder??String(value??"Choose…")}</span><CaretDown/></button>{open&&createPortal(<div ref={popup} className="select-popover" tabIndex={-1} style={{position:"fixed",...bounds}} onKeyDown={keys} onPointerDown={event=>event.stopPropagation()} onBlur={event=>{if(event.relatedTarget&&!popup.current?.contains(event.relatedTarget as Node)&&event.relatedTarget!==trigger.current)close(false);}}>{canSearch&&<label className="select-search"><MagnifyingGlass/><input ref={search} aria-label={`Search ${label.toLowerCase()}`} placeholder="Search…" value={query} onChange={event=>{setQuery(event.target.value);setActive(0);}}/></label>}<div role="listbox" aria-label={label} id={id} aria-activedescendant={filtered[active]?`${id}-${active}`:undefined}>{filtered.map((choice,index)=><button key={choice.value} type="button" role="option" aria-selected={choice.value===String(value)} disabled={choice.disabled} id={`${id}-${index}`} data-index={index} data-value={choice.value} className={index===active?"highlighted":""} tabIndex={-1} onMouseEnter={()=>setActive(index)} onClick={()=>choose(choice)}><span>{choice.label}</span>{choice.value===String(value)&&<Check/>}</button>)}{!filtered.length&&<p>No matching options</p>}</div>{footer&&<div className="select-footer">{footer}</div>}</div>,root)}</>;
}
