import {useFontCatalog} from "./useFontCatalog";
import { Select } from "./Select";
import {accentFor,themes,Theme,themeId} from "./themes";
import { CustomThemeManager } from "./CustomThemeManager";
import { ArrowLeft, Bell, Check, Desktop, Folder, Gear, Keyboard, SlidersHorizontal, SquaresFour, Archive, Sun, Moon } from "@phosphor-icons/react";
import { ProviderIcon } from "./ProviderIcon";
import { copyText } from "./clipboard";
import { ReactNode, useState } from "react";
import { Meta, Session, signInProvider } from "./api";
import { defaultShortcuts, displayShortcut, shortcutLabels, MAX_BACKGROUND_TRANSPARENCY, Preferences, settingsSections, SettingsSection } from "./preferences";
export {settingsSections};
export type {SettingsSection};
const icons=[Gear,SlidersHorizontal,Bell,Keyboard,SquaresFour,Desktop,Folder,Archive];
export function SettingsNavigation({section,onSection,onBack}:{section:SettingsSection;onSection:(section:SettingsSection)=>void;onBack:()=>void}) {
 return <aside className="sidebar settings-navigation"><button className="settings-back" onClick={onBack}><ArrowLeft/>Back</button><nav role="tablist" aria-label="Settings sections">{settingsSections.map((label,i)=>{const Icon=icons[i];return <button role="tab" aria-selected={section===label} className={section===label?"active":""} key={label} onClick={()=>onSection(label)}><Icon/>{label}</button>;})}</nav></aside>;
}
function ThemeChoice({theme,children}:{theme:Theme;children:string}) {return <span className="theme-choice-label"><span className="theme-choice-swatch" aria-hidden="true">{[theme.colors.shell,theme.colors.background,theme.accent.primary].map((color,i)=><i key={i} style={{background:color}}/>)}</span>{children}</span>;}
function Row({label,description,children,icon}:{label:string;description?:string;children:ReactNode;icon?:ReactNode}) {return <div className="preference-row">{icon&&<span className="provider-icon-tile">{icon}</span>}<span><strong>{label}</strong>{description&&<small>{description}</small>}</span>{children}</div>;}
function Group({title,children}:{title?:string;children:ReactNode}) {return <section className="preference-group">{title&&<h2>{title}</h2>}<div className="preference-card">{children}</div></section>;}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}) {return <button type="button" role="switch" aria-label={label} aria-checked={checked} className="preference-switch" onClick={()=>onChange(!checked)}><span/></button>;}
const providerLabels:Record<string,string>={claude:"Claude Code",codex:"Codex",copilot:"Copilot CLI",opencode:"OpenCode",grok:"Grok",shell:"Local shell"};
export function SettingsPage({activeAppearance="dark",resolvedMaterial,nativeMaterial="browser",preferences,onChange,section="General",meta,sessions=[],onRestore,onSetup}:{activeAppearance?:string;resolvedMaterial?:string;nativeMaterial?:string;preferences:Preferences;onChange:(next:Preferences)=>void;section?:SettingsSection;meta?:Meta|null;sessions?:Session[];onRestore?:(id:string)=>void;onSetup?:(session:Session)=>void}) {
 const fonts=useFontCatalog();
 const [capturing,setCapturing]=useState<string|null>(null); const [notice,setNotice]=useState("");
 const update=<K extends keyof Preferences>(key:K,value:Preferences[K])=>onChange({...preferences,[key]:value});
 const boolRow=(label:string,key:keyof Preferences,description?:string)=><Row label={label} description={description}><Toggle label={label} checked={Boolean(preferences[key])} onChange={value=>onChange({...preferences,[key]:value})}/></Row>;
 const chooseProjectRoot=async()=>{ const bridge=window as typeof window & {go?:{main?:{App?:{SelectRepository?:()=>Promise<string>}}}}; try {const root=await bridge.go?.main?.App?.SelectRepository?.(); if(root)update("project_root",root); else if(!bridge.go) setNotice("Enter your workspace folder below.");}catch(error){setNotice(String(error));} };
 const requestNotifications=async()=>{if(!("Notification" in window)){setNotice("Desktop notifications are unavailable in this window.");return;} const permission=await Notification.requestPermission(); update("notifications",permission==="granted"); if(permission!=="granted")setNotice("Notifications are blocked in this window’s permissions.");};
 return <div className="settings-page"><div className="settings-content"><header><h1>{section==="Shortcuts"?"Keyboard Shortcuts":section}</h1>{section==="Shortcuts"&&<p>Click a binding, then press the new key combination.</p>}{notice&&<p role="status">{notice}</p>}</header>
 {section==="General"&&<>
 <Group><Row label="Send messages with"><Select aria-label="Send messages with" value={preferences.send_behavior} onChange={e=>update("send_behavior",e.target.value as Preferences["send_behavior"])}><option value="enter">Enter</option><option value="mod-enter">⌘ / Ctrl + Enter</option></Select></Row><Row label="Compact mode" description="Collapse thinking and tools."><Toggle label="Compact mode" checked={preferences.activity_detail==="compact"} onChange={v=>update("activity_detail",v?"compact":"expanded")}/></Row>{boolRow("Open web links in OpenADE","open_web_links_in_app","Open chat and Markdown links in the workspace browser.")}{boolRow("Fit code blocks to content","code_fences_fit_content")}{boolRow("Stop agent with Escape","stop_on_escape","When no dialog or menu is open.")}</Group>
 <Group><Row label="Session experience" description="Open sessions in your preferred surface."><Select aria-label="Open sessions in" value={preferences.session_surface} onChange={e=>update("session_surface",e.target.value as Preferences["session_surface"])}><option value="chat">Native chat</option><option value="terminal">Direct TUI</option></Select></Row></Group>
 <Group title="Projects"><Row label="Workspace folder" description="Index local repositories and provider conversations."><button onClick={()=>void chooseProjectRoot()}>Choose folder</button></Row><Row label="Folder path"><input aria-label="Workspace folder path" placeholder="/path/to/workspace" value={preferences.project_root} onChange={e=>update("project_root",e.target.value)}/></Row></Group>
 </>}
 {section==="Appearance"&&<>
 <section className="color-scheme"><h2>Color scheme</h2><div>{([['system','System'],['paper','Light'],['graphite','Dark']] as const).map(([id,label])=><button key={id} aria-pressed={preferences.color_scheme===(id==="paper"?"light":id==="graphite"?"dark":"system")} onClick={()=>update("color_scheme",id==="paper"?"light":id==="graphite"?"dark":"system")}><SchemePreview mode={id} light={themes.find(theme=>theme.id===themeId(preferences.light_theme,"light"))!} dark={themes.find(theme=>theme.id===themeId(preferences.dark_theme,"dark"))!}/><span className="scheme-caption">{id==="system"?<Desktop/>:id==="paper"?<Sun/>:<Moon/>}{label}</span></button>)}</div></section>
 <Group><Row label="Light theme"><Select aria-label="Light theme" value={preferences.light_theme} onChange={e=>update("light_theme",e.target.value)}>{themes.filter(theme=>theme.appearance==="light").map(theme=><option key={theme.id} value={theme.id}><ThemeChoice theme={theme}>{theme.name}</ThemeChoice></option>)}</Select></Row><Row label="Dark theme"><Select aria-label="Dark theme" value={preferences.dark_theme} onChange={e=>update("dark_theme",e.target.value as Preferences["dark_theme"])}>{themes.filter(theme=>theme.appearance==="dark").map(theme=><option key={theme.id} value={theme.id}><ThemeChoice theme={theme}>{theme.name}</ThemeChoice></option>)}</Select></Row><Row label="Accent color" description="Theme default"><div className="accent-swatches">{["default","#8b7cf6","#fb923c","#fbbf24","#4ade80","#22d3ee","#60a5fa","#f472b6"].map((color,i)=><button aria-label={["Theme default","Zeron","Orange","Amber","Green","Cyan","Blue","Pink"][i]} aria-pressed={preferences.accent===color} key={color} onClick={()=>update("accent",color)} style={{background:color==="default"?"var(--theme-accent)":accentFor(color,activeAppearance)}}>{preferences.accent===color&&<Check/>}</button>)}</div></Row></Group>
 <CustomThemeManager preferences={preferences} onChange={next=>onChange({...preferences,...next})}/>
 <Group title="Material and background"><Row label="Glass" description={nativeMaterial==="reduced-transparency"?"Solid surfaces — macOS Reduce Transparency is on":nativeMaterial==="increased-contrast"?"Solid surfaces — macOS Increase Contrast is on":nativeMaterial==="unsupported"?"Solid fallback — native materials unavailable":nativeMaterial==="liquid"?"Native macOS Liquid Glass":nativeMaterial==="liquid-fallback"?"Frosted fallback — native Liquid Glass unavailable":nativeMaterial==="opaque"||resolvedMaterial==="opaque"?"Solid surfaces":nativeMaterial==="browser"?"Browser approximation — desktop translucency requires the native app":"Native macOS frosted material"}><Select aria-label="Glass" value={preferences.glass} onChange={e=>update("glass",e.target.value as Preferences["glass"])}><option value="default">Theme default</option><option value="frosted">Frosted</option><option value="liquid">Liquid Glass (macOS 26+)</option><option value="opaque">Opaque</option></Select></Row><Row label="Transparency" description="More transparent lets more background color through."><div className="transparency-control"><input type="range" onPointerDown={event=>event.currentTarget.focus({preventScroll:true})} onPointerUp={event=>event.currentTarget.focus({preventScroll:true})} aria-label="Background transparency" aria-valuetext={`${preferences.transparency}% transparent`} min="0" max={MAX_BACKGROUND_TRANSPARENCY} step="1" value={preferences.transparency} disabled={resolvedMaterial==="opaque"||preferences.glass==="opaque"||["opaque","unsupported","browser","reduced-transparency","increased-contrast"].includes(nativeMaterial)} onChange={e=>{e.currentTarget.focus({preventScroll:true});update("transparency",Number(e.target.value));}}/><output>{preferences.transparency}%</output></div></Row></Group>
 <Group title="Fonts and layout"><Row label="Interface font" description="Menus and conversations"><Select searchable searchPlaceholder="Search fonts…" aria-label="Interface font" value={preferences.interface_font} onChange={e=>update("interface_font",e.target.value as Preferences["interface_font"])}>{fonts.map(font=><option key={font.family}>{font.family}</option>)}</Select><Select aria-label="Interface font size" value={preferences.interface_size} onChange={e=>update("interface_size",Number(e.target.value))}>{[12,13,14,15,16,18,20].map(n=><option key={n} value={n}>{n} px</option>)}</Select></Row><Row label="Terminal font"><Select searchable searchPlaceholder="Search monospace fonts…" aria-label="Terminal font" value={preferences.terminal_font} onChange={e=>update("terminal_font",e.target.value)}>{fonts.filter(font=>font.monospace).map(font=><option key={font.family}>{font.family}</option>)}</Select><Select aria-label="Terminal font size" value={preferences.terminal_size} onChange={e=>update("terminal_size",Number(e.target.value))}>{Array.from({length:25},(_,i)=>i+8).map(size=><option key={size} value={size}>{size} px</option>)}</Select></Row><Row label="Code & diff font"><Select searchable searchPlaceholder="Search fonts…" aria-label="Code and diff font" value={preferences.code_font} onChange={e=>update("code_font",e.target.value)}>{fonts.map(font=><option key={font.family}>{font.family}</option>)}</Select><Select aria-label="Code and diff font size" value={preferences.code_size} onChange={e=>update("code_size",Number(e.target.value))}>{Array.from({length:49},(_,i)=>8+i*.5).map(size=><option key={size} value={size}>{size} px</option>)}</Select></Row><Row label="Conversation width" description="Maximum width for messages and the composer."><input aria-label="Conversation width" type="range" min="560" max="1200" step="16" value={preferences.conversation_width} onChange={e=>update("conversation_width",Number(e.target.value))}/></Row></Group></>}
 {section==="Notifications"&&<><Group title="Desktop"><Row label="Desktop notifications"><Toggle label="Desktop notifications" checked={preferences.notifications} onChange={value=>value?void requestNotifications():update("notifications",false)}/></Row>{boolRow("Only when in the background","background_only")}</Group><Group title="Sounds">{boolRow("Session sounds","sounds")}{boolRow("Task completed","sound_completed")}{boolRow("Input required","sound_input")}{boolRow("Errors and disconnections","sound_errors")}</Group></>}
 {section==="Shortcuts"&&<><button className="restore-shortcuts" onClick={()=>update("shortcuts",{...defaultShortcuts})}>Restore defaults</button>{[["Chats",["commandPalette","newProject","newSession","next","previous"]],["Jump to chat",Array.from({length:9},(_,i)=>`jump${i+1}`)],["Composer",["focusComposer","model"]],["Panels",["sidebar","panel","files","terminal","browser","diffs","history","closePanel","nextPanel","previousPanel","searchFiles"]],["App",["settings"]]].map(([title,keys])=><Group key={String(title)} title={String(title)}>{(keys as string[]).map(key=><Row key={key} label={shortcutLabels[key]}><button aria-label={`Change ${key} shortcut`} onClick={()=>setCapturing(key)} onKeyDown={e=>{if(capturing!==key)return;e.preventDefault();e.stopPropagation();if(e.key==="Escape"){setCapturing(null);return;}if(["Meta","Control","Shift","Alt"].includes(e.key))return;const value=[e.metaKey?"Mod":e.ctrlKey?"Ctrl":"",e.altKey?"Alt":"",e.shiftKey?"Shift":"",e.key].filter(Boolean).join("+");if(!(e.ctrlKey||e.metaKey||e.altKey)){setNotice("Use a modifier key to avoid interrupting typing.");return;}if(Object.entries(preferences.shortcuts).some(([k,v])=>k!==key&&v.toLowerCase()===value.toLowerCase())){setNotice("That shortcut is already assigned.");return;}update("shortcuts",{...preferences.shortcuts,[key]:value});setCapturing(null);setNotice("");}}>{capturing===key?"Press keys…":displayShortcut(preferences.shortcuts[key])}</button></Row>)}</Group>)}</>}
 {section==="Providers"&&<><Group>{Object.entries(providerLabels).map(([id,label])=>{const provider=meta?.agents.find(a=>a.id===id);const available=provider?.available??false;const docs:Record<string,string>={codex:"https://github.com/openai/codex",claude:"https://code.claude.com/docs/en/setup",copilot:"https://github.com/github/copilot-cli",opencode:"https://opencode.ai/docs/"};return <div className="provider-preferences" key={id}><Row icon={<ProviderIcon provider={id}/>} label={label} description={available?"CLI installed · Uses its existing sign-in.":"Install and sign in to this CLI to enable."}>{available?<Toggle label={`Enable ${label}`} checked={!preferences.disabled_providers.includes(id)} onChange={enabled=>update("disabled_providers",enabled?preferences.disabled_providers.filter(v=>v!==id):[...preferences.disabled_providers,id])}/>:docs[id]?<a href={docs[id]} target="_blank" rel="noreferrer" className="provider-install">Install</a>:null}</Row><details><summary>Preferences</summary><div className="provider-details">{provider?.path&&<p><span>Executable</span><code>{provider.path}</code></p>}<p>{["codex","claude"].includes(id)?"Native chat, resumable conversations and Direct TUI.":id==="shell"?"Independent project shells.":"Direct TUI. Models and sign-in are controlled by the provider."}</p>{available&&["codex","claude","copilot","opencode"].includes(id)&&<button onClick={()=>{setNotice(`Opening ${label} sign-in…`);void signInProvider(id).then(session=>{setNotice("");onSetup?.(session);}).catch(reason=>setNotice(String(reason)));}}>Sign in</button>}{available&&id!=="shell"&&<button onClick={()=>void copyText(id==="codex"?"codex login":id==="claude"?"claude auth login":id==="opencode"?"opencode auth login":id).then(()=>setNotice("Command copied.")).catch(()=>setNotice("Unable to copy command."))}>Copy CLI command</button>}{docs[id]&&<a href={docs[id]} target="_blank" rel="noreferrer">Setup instructions</a>}</div></details></div>;})}</Group><Group><Row label="Default provider"><Select aria-label="Default provider" value={preferences.default_agent} onChange={e=>update("default_agent",e.target.value)}>{Object.entries(providerLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</Select></Row></Group></>}

 {section==="Devices"&&<><p>Devices in this local workspace.</p><Group title="This device"><Row label="Local workspace" description={meta?"Daemon connected":"Reconnecting…"}><Desktop/></Row></Group><p className="settings-footnote">Sessions keep running when this window closes. Remote device sync is not available yet.</p></>}
 {section==="Files"&&<Group>{boolRow("Autosave","autosave","Save text edits after a short pause.")}<Row label="Autosave delay"><Select aria-label="Autosave delay" value={preferences.autosave_delay_ms} disabled={!preferences.autosave} onChange={event=>update("autosave_delay_ms",Number(event.target.value))}>{[300,600,900,1500,3000].map(delay=><option key={delay} value={delay}>{delay>=1000?`${delay/1000} s`:`${delay} ms`}</option>)}</Select></Row>{boolRow("Word wrap","word_wrap")}{boolRow("Show hidden files","show_hidden")}{boolRow("Show ignored files","show_ignored")}</Group>}
 {section==="Archived sessions"&&<><p>Archived chats appear in the sidebar’s Archived section.</p>{sessions.filter(s=>s.archived).length?<Group>{sessions.filter(s=>s.archived).map(s=><Row key={s.id} label={s.title}><button onClick={()=>onRestore?.(s.id)}>Restore</button></Row>)}</Group>:<div className="settings-empty"><Archive/><strong>Nothing archived</strong><p>Use a session’s actions to archive it.</p></div>}</>}
 </div></div>;
}

function SchemePreview({mode,light,dark}:{mode:string;light:Theme;dark:Theme}){
 const bars=<><i/><i/><i/><i/></>;
 const frame=(tone:string,theme:Theme)=><span className={`scheme-frame ${tone}`} style={{color:theme.colors.textMuted,background:theme.colors.shell}}><span>{bars}</span><span style={{background:theme.colors.background}}>{bars}</span></span>;
 const theme=mode==='paper'?light:dark;
 return <span className={`scheme-preview scheme-${mode}`} data-theme-preview={mode==='system'?'system':theme.id} style={{color:theme.colors.textMuted,background:mode==='system'?`linear-gradient(to right,${light.colors.shell} 50%,${dark.colors.shell} 50%)`:theme.colors.shell}}>{mode==='system'?<>{frame('preview-light',light)}{frame('preview-dark',dark)}</>:<><span>{bars}</span><span style={{background:theme.colors.background}}>{bars}</span></>}</span>;
}
