import catalog from "./theme-catalog.json";

export type Appearance = "light" | "dark";
type CatalogTheme = typeof catalog[number]["variants"][number];
export type Theme = Omit<CatalogTheme, "id" | "familyId" | "name" | "appearance" | "source"> & {
 id:string; familyId:string; name:string; appearance:Appearance;
 source:{format:string;url:string;revision:string;license:string;assetHash:string;libraryId?:string;variantId?:string;sourceKind?:string;status?:"ready"|"warning";statusMessage?:string};
};

const builtinThemes = catalog.flatMap(family => family.variants) as Theme[];
export let themes:Theme[] = [...builtinThemes];
const storageKey="openade.custom-themes.v1";
const maxThemeFileBytes=2*1024*1024, maxLibraryBytes=8*1024*1024, maxCustomVariants=256;
const listeners=new Set<()=>void>();
let byId=new Map<string,Theme>();
let localCustom:Theme[]=[];
let libraryCustom:Theme[]=[];
let legacyLibraryIds=new Map<string,Theme[]>();
const legacyIds:Record<string,string>={graphite:"zeron-dark",dusk:"gruvbox-dark",paper:"zeron-light"};
export function onThemeRegistryChange(listener:()=>void):()=>void {listeners.add(listener);return()=>listeners.delete(listener);}
function notify(){if(typeof window!=="undefined")window.dispatchEvent(new Event("openade-theme-registry-change"));for(const listener of listeners)listener();}
function setRegistry(custom:Theme[]){themes=[...builtinThemes,...custom];byId=new Map(themes.map(theme=>[theme.id,theme]));notify();}

function validHex(value:unknown):value is string{return typeof value==="string"&&/^#[\da-fA-F]{6}(?:[\da-fA-F]{2})?$/.test(value);}
function safeStoredTheme(value:unknown):value is Theme {
 if(!value||typeof value!=="object")return false;const theme=value as Theme;
 if(typeof theme.id!=="string"||!/^custom-[a-z0-9-]{1,80}$/.test(theme.id)||typeof theme.name!=="string"||!theme.name.trim()||!(["light","dark"] as string[]).includes(theme.appearance))return false;
 if(theme.recommendedSurfaceTreatment!=="frosted"&&theme.recommendedSurfaceTreatment!=="opaque"&&theme.recommendedSurfaceTreatment!=="liquid")return false;
 const roles=[theme.colors,theme.accent,theme.syntax,theme.terminal] as unknown[];
 if(!roles.every(item=>!!item&&typeof item==="object"&&Object.values(item).every(v=>Array.isArray(v)?v.every(validHex):validHex(v))))return false;
 const base=builtinThemes.find(item=>item.appearance===theme.appearance)!;
 const sameKeys=(a:object,b:object)=>Object.keys(a).length===Object.keys(b).length&&Object.keys(a).every(key=>key in b);
 return sameKeys(theme.colors,base.colors)&&sameKeys(theme.accent,base.accent)&&sameKeys(theme.syntax,base.syntax)&&sameKeys(theme.terminal,base.terminal)&&Array.isArray(theme.accent.glyph)&&theme.accent.glyph.length===3&&Array.isArray(theme.terminal.ansi)&&theme.terminal.ansi.length===16&&!!theme.source&&[theme.source.format,theme.source.url,theme.source.revision,theme.source.license,theme.source.assetHash].every(item=>typeof item==="string");
}
function readCustom():Theme[]{try{const raw=localStorage.getItem(storageKey);if(!raw)return[];if(raw.length>maxLibraryBytes)return[];const parsed:unknown=JSON.parse(raw);if(!Array.isArray(parsed))return[];const seen=new Set<string>();return parsed.filter(safeStoredTheme).filter(theme=>!theme.source.libraryId&&!builtinThemes.some(b=>b.id===theme.id)&&!seen.has(theme.id)&&!!seen.add(theme.id)).slice(0,maxCustomVariants);}catch{return[];}}
localCustom=readCustom();setRegistry(localCustom);
function persist(custom:Theme[]){const raw=JSON.stringify(custom);if(raw.length>maxLibraryBytes)throw Error("Custom theme library limit reached");localStorage.setItem(storageKey,raw);localCustom=custom;setRegistry([...localCustom,...libraryCustom]);}
export function libraryThemeId(entryId:string,variantId:string):string{return `native:${encodeURIComponent(entryId)}:${encodeURIComponent(variantId)}`;}
function pendingLibraryThemeId(value:string){if(value.length>1024||!value.startsWith("native:"))return false;const pair=value.slice(7).split(":");if(pair.length!==2)return false;try{const entryId=decodeURIComponent(pair[0]),variantId=decodeURIComponent(pair[1]);return !!entryId&&!!variantId&&libraryThemeId(entryId,variantId)===value;}catch{return false;}}
export function themeId(value:string,appearance:Appearance,allowPending=false):string {
 const legacy=legacyIds[value];if(legacy)return byId.get(legacy)?.appearance===appearance?legacy:`zeron-${appearance}`;
 const exact=byId.get(value);if(exact)return exact.appearance===appearance?exact.id:`zeron-${appearance}`;
 // A saved browser snapshot owns its ID even if a linked daemon variant uses
 // the same raw ID. The namespaced renderer ID remains distinct.
 const snapshot=localCustom.find(theme=>theme.id===value);if(snapshot)return snapshot.appearance===appearance?snapshot.id:`zeron-${appearance}`;
 const allAliases=legacyLibraryIds.get(value)??[];
 if(allAliases.length){const winner=allAliases[allAliases.length-1];return winner.appearance===appearance?winner.id:`zeron-${appearance}`;}
 const id=value;
 return allowPending&&!byId.has(id)&&id.length<=1024&&(/^custom-[a-z0-9-]+$/.test(id)||pendingLibraryThemeId(id))?id:`zeron-${appearance}`;
}
export function resolveTheme(preferences:{color_scheme:string;light_theme:string;dark_theme:string},systemLight:boolean):Theme {const light=preferences.color_scheme==="light"||preferences.color_scheme==="system"&&systemLight;const appearance=light?"light":"dark",selected=themeId(light?preferences.light_theme:preferences.dark_theme,appearance);return byId.get(selected)??byId.get(`zeron-${appearance}`)!;}
export function materialFor(theme:Theme,preference:string):string{return preference==="default"?theme.recommendedSurfaceTreatment:preference;}
const lightAccents:Record<string,string>={"#8b7cf6":"#5b43e8","#fb923c":"#c2410c","#fbbf24":"#a16207","#4ade80":"#15803d","#22d3ee":"#0e7490","#60a5fa":"#2563eb","#f472b6":"#be185d"};
export function accentFor(color:string,appearance:string):string{return appearance==="light"?lightAccents[color]??color:color;}
export function themeCssVariables(theme:Theme):Record<string,string>{
 const c=theme.colors as Record<string,string>,s=theme.syntax as Record<string,string>,a=theme.terminal.ansi;
 return {"--bg":c.background,"--sidebar":c.shell,"--surface":c.card,"--surface-2":c.hover,"--surface-3":c.raised,"--popup-surface":c.dialog,"--line":c.border,"--line-soft":c.border,"--text":c.text,"--muted":c.textMuted,"--muted-2":c.textFaint,"--faint":c.textFaint,"--accent":theme.accent.primary,"--accent-soft":theme.accent.wash,"--green":c.success,"--red":c.danger,"--orange":c.warning,"--diff-add":c.diffAdd,"--diff-delete":c.diffDelete,"--diff-hunk":c.diffHunk,"--terminal-bg":theme.terminal.background,"--terminal-fg":theme.terminal.foreground,"--terminal-selection":theme.terminal.selection,"--syntax-comment":s.comment,"--syntax-keyword":s.keyword,"--syntax-string":s.string,"--syntax-number":s.number,"--syntax-type":s.type,"--syntax-function":s.function,"--syntax-property":s.property,"--syntax-variable":s.variable,"--syntax-punctuation":s.punctuation,"--syntax-tag":s.tag,"--syntax-attribute":s.attribute,"--syntax-invalid":s.invalid,"--ansi-black":a[0],"--ansi-red":a[1],"--ansi-green":a[2],"--ansi-yellow":a[3],"--ansi-blue":a[4],"--ansi-magenta":a[5],"--ansi-cyan":a[6],"--ansi-white":a[7],"--ansi-bright-black":a[8],"--ansi-bright-red":a[9],"--ansi-bright-green":a[10],"--ansi-bright-yellow":a[11],"--ansi-bright-blue":a[12],"--ansi-bright-magenta":a[13],"--ansi-bright-cyan":a[14],"--ansi-bright-white":a[15]};
}

const roleColorKeys:Record<string,string[]>={background:["editor.background","sideBar.background"],shell:["sideBar.background","activityBar.background"],raised:["editorWidget.background","sideBarSectionHeader.background"],card:["editor.background"],dialog:["quickInput.background","notifications.background"],overlay:["editorWidget.background"],hover:["list.hoverBackground","toolbar.hoverBackground"],active:["list.activeSelectionBackground","list.activeSelectionBackground"],border:["panel.border","sideBar.border","editorWidget.border"],borderStrong:["focusBorder","contrastBorder"],text:["foreground","editor.foreground"],textMuted:["descriptionForeground","tab.inactiveForeground"],textFaint:["disabledForeground","input.placeholderForeground"],solid:["button.background"],onSolid:["button.foreground"],danger:["errorForeground","errorForeground"],dangerMuted:["editorError.foreground"],warning:["editorWarning.foreground","editorWarning.foreground"],warningMuted:["editorWarning.foreground"],success:["testing.iconPassed","testing.iconPassed"],successMuted:["testing.iconPassed"],input:["input.background"],cursor:["editorCursor.foreground"],diffAdd:["diffEditor.insertedTextBackground","diffEditor.insertedLineBackground"],diffDelete:["diffEditor.removedTextBackground","diffEditor.removedLineBackground"],diffHunk:["diffEditor.diagonalFill"]};
function firstColor(map:Record<string,unknown>,keys:string[],fallback:string){for(const key of keys){const value=map[key];if(validHex(value))return value;}return fallback;}
function toTheme(source:Record<string,unknown>,name:string,appearance:Appearance,id:string):Theme {
 const base=builtinThemes.find(t=>t.appearance===appearance)!;const colors=(source.colors&&typeof source.colors==="object"?source.colors:{}) as Record<string,unknown>;
 const output=structuredClone(base) as Theme;output.id=id;output.familyId=id;output.name=name.trim().slice(0,100);output.source={format:"vscode",url:"local import",revision:"local",license:"User supplied",assetHash:""};
 for(const [role,keys] of Object.entries(roleColorKeys))(output.colors as Record<string,string>)[role]=firstColor(colors,keys,(base.colors as Record<string,string>)[role]);
 const tokenColors=Array.isArray(source.tokenColors)?source.tokenColors:[];
 for(const item of tokenColors){if(!item||typeof item!=="object")continue;const row=item as Record<string,unknown>,settings=row.settings as Record<string,unknown>|undefined;if(!settings||!validHex(settings.foreground))continue;const declared=typeof row.scope==="string"?row.scope.split(",").map(scope=>scope.trim()).filter(Boolean):Array.isArray(row.scope)?row.scope.filter((scope):scope is string=>typeof scope==="string"):[];for(const scope of declared){const role=syntaxRoleForScope(scope);if(role)(output.syntax as Record<string,string>)[role]=settings.foreground;}}
 const semantic=source.semanticTokenColors&&typeof source.semanticTokenColors==="object"?source.semanticTokenColors as Record<string,unknown>:{};
 for(const [selector,style] of Object.entries(semantic).sort(([left],[right])=>left<right?-1:left>right?1:0)){const role=syntaxRoleForSemantic(selector),foreground=typeof style==="string"?style:style&&typeof style==="object"?(style as Record<string,unknown>).foreground:undefined;if(role&&validHex(foreground))(output.syntax as Record<string,string>)[role]=foreground;}
 const accent=firstColor(colors,["activityBar.activeBorder","button.background","focusBorder"],base.accent.primary);output.accent={primary:accent,strong:accent,wash:accent.slice(0,7)+"38",on:firstColor(colors,["button.foreground"],base.accent.on),selection:firstColor(colors,["editor.selectionBackground"],accent.slice(0,7)+"59"),caret:firstColor(colors,["editorCursor.foreground"],accent),activity:firstColor(colors,["activityBarBadge.background"],accent),glyph:[accent,accent,accent]};
 const terminalKeys=["terminal.ansiBlack","terminal.ansiRed","terminal.ansiGreen","terminal.ansiYellow","terminal.ansiBlue","terminal.ansiMagenta","terminal.ansiCyan","terminal.ansiWhite","terminal.ansiBrightBlack","terminal.ansiBrightRed","terminal.ansiBrightGreen","terminal.ansiBrightYellow","terminal.ansiBrightBlue","terminal.ansiBrightMagenta","terminal.ansiBrightCyan","terminal.ansiBrightWhite"];
 output.terminal.background=firstColor(colors,["terminal.background"],output.colors.background);output.terminal.foreground=firstColor(colors,["terminal.foreground"],output.colors.text);output.terminal.selection=firstColor(colors,["terminal.selectionBackground"],output.terminal.selection);output.terminal.ansi=terminalKeys.map(key=>firstColor(colors,[key],base.terminal.ansi[terminalKeys.indexOf(key)]));
 return output;
}
function syntaxRoleForScope(scope:string):string|undefined {const normalized=scope.toLowerCase();const mappings:[string,string][]=[["comment","comment"],["invalid","invalid"],["keyword","keyword"],["storage","keyword"],["string","string"],["constant.numeric","number"],["constant.language","boolean"],["entity.name.type","type"],["support.type","typeBuiltin"],["entity.name.function","function"],["support.function","functionBuiltin"],["entity.other.attribute","attribute"],["entity.name.tag","tag"],["variable.parameter","parameter"],["variable.other.property","property"],["variable","variable"],["constant","constant"],["keyword.operator","operator"],["punctuation","punctuation"]];return mappings.find(([needle])=>normalized.includes(needle))?.[1];}
function syntaxRoleForSemantic(selector:string):string|undefined {const token=selector.split(/[.:]/,1)[0]?.toLowerCase();const map:Record<string,string>={comment:"comment",keyword:"keyword",modifier:"keyword",string:"string",regexp:"string",number:"number",type:"type",class:"type",interface:"type",enum:"type",struct:"type",function:"function",method:"function",property:"property",enummember:"property",parameter:"parameter",variable:"variable",macro:"macro",decorator:"attribute"};return map[token];}

function slug(value:string){return value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,64)||"theme";}
function appearanceFrom(source:Record<string,unknown>,uiTheme?:unknown):Appearance {const declared=String(uiTheme??"").toLowerCase();if(declared==="vs"||declared.includes("light"))return "light";if(declared.includes("dark"))return "dark";const kind=String(source.type??source.name??"").toLowerCase();return kind.includes("light")?"light":"dark";}
function validateVscodeTheme(value:unknown):Record<string,unknown> {if(!value||typeof value!=="object"||Array.isArray(value))throw Error("Choose a VS Code theme JSON file or extension folder.");const source=value as Record<string,unknown>;if(!source.colors&&!source.tokenColors&&!source.semanticTokenColors)throw Error("This JSON does not contain VS Code theme colors or token rules.");if(source.colors!==undefined&&(!source.colors||typeof source.colors!=="object"||Array.isArray(source.colors)))throw Error("VS Code colors must be an object.");for(const [key,color] of Object.entries((source.colors??{}) as Record<string,unknown>)){if(typeof color!=="string"||!validHex(color))throw Error(`Unsupported color for “${key}”. Use #RRGGBB or #RRGGBBAA colors.`);}if(source.include!==undefined)throw Error("Theme includes need source compilation and are not supported by local import.");return source;}
function compileFile(data:string,name:string,id:string,uiTheme?:unknown):Theme {if(new TextEncoder().encode(data).length>maxThemeFileBytes)throw Error("Theme file exceeds the 2 MB import limit.");let parsed:unknown;try{parsed=JSON.parse(data);}catch{throw Error("Theme JSON must be valid standard JSON.");}return compileThemeDocument(parsed,name,id,uiTheme);}
export function compileThemeDocument(value:unknown,name:string,id:string,uiTheme?:unknown):Theme {const source=validateVscodeTheme(value);const themeName=typeof source.name==="string"?source.name:name.replace(/\.json$/i,"");return toTheme(source,themeName,appearanceFrom(source,uiTheme),id);}
export function installThemeLibrary(entries:{id:string;source:{kind:string};status:{state:"ready"|"warning";message?:string};variants:{id:string;name:string;appearance:Appearance;document:unknown}[]}[]):void {
 const next:Theme[]=[],aliases=new Map<string,Theme[]>();
 for(const entry of entries)for(const variant of entry.variants){try{const theme=compileThemeDocument(variant.document,variant.name,libraryThemeId(entry.id,variant.id),variant.appearance==="light"?"vs":"vs-dark");theme.familyId=entry.id;theme.source={...theme.source,format:"linked",url:entry.source.kind,revision:"local",license:"User supplied",assetHash:"",libraryId:entry.id,variantId:variant.id,sourceKind:entry.source.kind,status:entry.status.state,statusMessage:entry.status.message};next.push(theme);const prior=aliases.get(variant.id)??[];prior.push(theme);aliases.set(variant.id,prior);}catch{/* daemon excludes malformed documents; retain known-good browser registry */}}
 libraryCustom=next;legacyLibraryIds=aliases;setRegistry([...localCustom,...libraryCustom]);
}
export type ThemeImportResult={id:string;name:string;appearance:Appearance;replaced:boolean};
export async function importThemeFiles(files:File[],replaceId?:string):Promise<ThemeImportResult[]> {
 if(!files.length)throw Error("Choose a VS Code theme file or extension folder.");const total=files.reduce((sum,file)=>sum+file.size,0);if(total>maxThemeFileBytes)throw Error("Selected theme files exceed the 2 MB import limit.");
 const paths=new Map(files.map(file=>[file.webkitRelativePath||file.name,file]));let candidates:{source:File;label:string;uiTheme?:unknown}[]=[];
 const manifestFile=files.find(file=>file.name==="package.json");
 if(manifestFile){const manifest=JSON.parse(await manifestFile.text()) as Record<string,unknown>;const declarations=(manifest.contributes as {themes?:unknown}|undefined)?.themes;if(!Array.isArray(declarations)||!declarations.length)throw Error("package.json must declare contributes.themes.");if(declarations.length>maxCustomVariants)throw Error("Extension declares too many theme variants.");for(const entry of declarations){if(!entry||typeof entry!=="object")continue;const declaration=entry as Record<string,unknown>,relative=declaration.path;if(typeof relative!=="string"||relative.startsWith("/")||relative.split(/[\\/]/).includes(".."))continue;const file=paths.get(relative)||paths.get(files.length===1?relative:`${manifestFile.webkitRelativePath.split("/").slice(0,-1).join("/")}/${relative}`);if(file)candidates.push({source:file,label:typeof declaration.label==="string"?declaration.label:file.name,uiTheme:declaration.uiTheme});}if(!candidates.length)throw Error("No declared theme files were found in the selected extension folder.");
 }else{if(files.length!==1)throw Error("Select one VS Code theme JSON file, or a VS Code extension folder containing package.json.");candidates=[{source:files[0],label:files[0].name}];}
 if(candidates.length>maxCustomVariants)throw Error("Too many theme variants in this import.");const custom=localCustom;if(custom.length+candidates.length>maxCustomVariants&&!replaceId)throw Error("Custom theme library limit reached.");
 const next=[...custom],results:ThemeImportResult[]=[];for(let index=0;index<candidates.length;index++){const candidate=candidates[index],raw=await candidate.source.text(),suggested=slug(candidate.label.replace(/\.json$/i,""));const theme=compileFile(raw,candidate.label,`custom-${suggested}`,candidate.uiTheme);let target=replaceId&&candidates.length===1?next.find(item=>item.id===replaceId):undefined;if(target&&target.appearance!==theme.appearance)throw Error("Replacement theme must use the same appearance as the selected custom theme.");const conflict=next.find(item=>item.id===`custom-${suggested}-${theme.appearance}`||item.name.toLowerCase()===theme.name.toLowerCase()&&item.appearance===theme.appearance);if(target){theme.id=target.id;theme.familyId=target.familyId;next[next.indexOf(target)]=theme;}else{if(conflict)throw Error(`A custom ${theme.appearance} theme named “${theme.name}” already exists. Choose it in Replace existing, or rename the source.`);theme.id=`custom-${suggested}-${theme.appearance}`;theme.familyId=theme.id;next.push(theme);}results.push({id:theme.id,name:theme.name,appearance:theme.appearance,replaced:!!target});}
 if(!results.length)throw Error("No valid theme variants were found.");persist(next);return results;
}
export function removeCustomTheme(id:string):void {if(builtinThemes.some(theme=>theme.id===id))throw Error("Built-in themes cannot be removed.");const custom=localCustom;const next=custom.filter(theme=>theme.id!==id);if(next.length===custom.length)throw Error("Custom snapshot no longer exists.");persist(next);}
export function isCustomTheme(id:string){return !builtinThemes.some(theme=>theme.id===id)&&byId.has(id);}
export function isSnapshotTheme(id:string){return !builtinThemes.some(theme=>theme.id===id)&&localCustom.some(theme=>theme.id===id);}
